### ISSUE TITLE
[F REQ] ADT to correctly sign dynamic frameworks included packaged with iOS app

### ISSUE THREAD

**Issue by tuarua** [Gamua/Adobe-Runtime-Support#10]
## Problem Description

To be able to build ANEs using Swift developers must use dynamic frameworks.
These frameworks when included are not signed correctly by adt and a complex bash based workflow is needed to package the final ipa file.

The current workflow workaround is
1) Sign frameworks when building ANE in Xcode
2) Resign frameworks using codesign bash script
3) Package AIR ipa using adt, including any framework files
4) Resign AIR ipa using bash script

## Known Workarounds

I have produced an AIR based tool to manage the resigning of Frameworks and AIR app but it's not ideal
https://github.com/tuarua/AIR-iOS-Packager

**Comment by myflashlab** [comment]
Surely a +1 on this one. To add to what @tuarua described, I must say that as the time goes, there will be more and more iOS libraries being developed with dynamic Frameworks. currently, you need to use some nasty shell scripts to strip the non-ARM archs and then use some other nasty shells to sign the frameworks and finally, as @tuarua mentioned, you need to resign the .ipa again.

While the [AIR-iOS-Packager](https://github.com/tuarua/AIR-iOS-Packager) is helping devs to speed up the process, it would be super great to see Adobe is doing all these things automatically in ADT to begin with.

**Comment by myflashlab** [comment]
As @PrimaryFeather [suggested](https://github.com/Gamua/Adobe-Runtime-Support#b-this-is-a-new-issue), I created the *Feature Request* in Adobe Tracker also here: https://tracker.adobe.com/#/view/AIR-4198408

**Comment by tuarua** [comment]
AIR 27 beta now auto signs dynamic frameworks.
There are some project structural requirements.
See tracker for details.
https://tracker.adobe.com/#/view/AIR-4198407

**Comment by tuarua** [comment]
Air 28 has resolved issues with creating a valid ipa for AppStore.
Swift 4 also support added.
Xcode 9 Simulator functioning correctly.

**Comment by Xgamefactory** [comment]
this issue not fixed completely i donT get why my comment was removed.
this hub to  inform developers

**Comment by PrimaryFeather** [comment]
Which comment was removed, @Xgamefactory?

**Comment by Xgamefactory** [comment]
comment about that adobe air sdk still have issues signing ios third party dynamic frameworks

**Comment by Xgamefactory** [comment]
this codesign problem still exists on lates air sdk 29.122 win
i don't understand what adobe trying to do. 
Looks like they are only interested in photoshop,illustrator and other design products or there are many insiders from opponent companies trying to ruin what left from macromedias development department.
Official adobe forum is abandoned,it took ages to get any reply from stuff.
All support stuff hired from lazy countries hanging out in office doing nothing. :)
There are left only few developers outside adobe who are trying to do something but without official support adobe air will get vanished like flash.
It is still best tool than xamarin,reactjs etc but with such terrible support air gets more unreliable each day.

**Comment by PrimaryFeather** [comment]
Could you maybe create a new bug report on Adobe Tracker? Ideally with a small sample that showcases the problem? Adobe is probably not reviewing all the posts over here. 

And don't forget to post the link here so we can vote for it!
