### ISSUE TITLE
Will Harman make a 3d game engine for AIR?

### ISSUE THREAD

**Issue by fftidus** [Gamua/Adobe-Runtime-Support#101]
All 3d engines are stop maintenance，is there any plan to make a new one?

If so , it's more comfortable when buying.

**Comment by ajwfrost** [comment]
Hi

There are a number of open source 3D engines, so creating a new one wouldn't be a priority for us. If there are any issues in existing engines that are dependent upon fixes/updates in the AIR runtime then we'd like to hear about them of course.

thanks

**Comment by fftidus** [comment]
╮(╯_╰)╭ Hope to use an official maintenanced  engine, always3d and flare3d is great but nobody can help to fix the bugs.
