### ISSUE TITLE
can not download the sdk

### ISSUE THREAD

**Issue by matrix3d** [Gamua/Adobe-Runtime-Support#122]
https://airsdk.harman.com/sdks/AIRSDK_Windows.zip?id=16371

Can you increase the speed of the download server? I have downloaded it for many days and can't download it completely. After downloading the network, it will be broken. I am in China

**Comment by ajwfrost** [comment]
Hi - I've just been looking at some stats on the bandwidth, we may be able to switch the machine type to make this increase, next time we do a server update (hopefully soon, we're just fixing some bugs with it)..
In the meantime if you email us at adobe.support@harman.com, we can send you a link to download it from Harman's own servers (hopefully in APAC).
thanks

**Comment by ajwfrost** [comment]
Hi - we've been struggling with our internal file transfer tool too! although we stopped after a couple of attempts, due to the issues with 33.0.2.281; 33.0.2.288 is now available and is currently on a machine category that's meant to have higher speeds. But we'll also have another go at transferring the files manually..

**Comment by matrix3d** [comment]
`AIRSDK_Windows (3).zip
https://airsdk.harman.com/sdks/AIRSDK_Windows.zip?id=31652
9.6 KB/s - 416 KB，共 581 MB，还剩 17 小时

AIRSDK_Windows (2).zip
https://airsdk.harman.com/sdks/AIRSDK_Windows.zip?id=31652
9.6 KB/s - 480 KB，共 581 MB，还剩 17 小时

AIRSDK_Windows (1).zip
https://airsdk.harman.com/sdks/AIRSDK_Windows.zip?id=31652
`

**Comment by marchbold** [comment]
Speeds seem to have gotten worse for us

![Screen Shot 2019-10-18 at 10 13 40](https://user-images.githubusercontent.com/442356/67056651-482cf000-f190-11e9-978a-b90d3c8dd89d.png)

Probably not top priority, but really needs to be improved.
