### ISSUE TITLE
AIR SDK  33.0.2.281 - Application crashed on 32 bit android device when packaged with arch armv7

### ISSUE THREAD

**Issue by mprabhu33** [Gamua/Adobe-Runtime-Support#123]
Not able to open the app when packaged with AIR SDK  33.0.2.281 on 32 bit android device
Same app working fine when packaged with AIR SDK  33.0.2.246

Describe your problem in detail. Include the following information:

AIR SDK  33.0.2.281
Android version: 8.1.0
Android device: Moto G5 Plus

Packaged with command line

## Steps to Reproduce

adt -package -target apk-captive-runtime -arch armv7 -storetype pkcs12 -keystore xxxx.p12 TestMobilev7.apk TestMobile-app.xml TestMobile.swf

Working:(Packaged with AIR SDK  33.0.2.246)
[TestMobile_32.0.2.246.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/3716154/TestMobile_32.0.2.246.zip)

Not Working:(Packaged with AIR SDK  33.0.2.281)
[TestMobile_33_0_2_281.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/3716156/TestMobile_33_0_2_281.zip)

Crash Logs:
[Crash Logs.txt](https://github.com/Gamua/Adobe-Runtime-Support/files/3716160/Crash.Logs.txt)

## Known Workarounds

Package with AIR SDK  33.0.2.246

**Comment by ajwfrost** [comment]
Okay that's strange, a crash deep within the rendering engine in code which has been unchanged for ages.. perhaps would be related to the build settings for libCore. We'll take a look..

**Comment by ajwfrost** [comment]
FYI are you able to try without
<colorDepth>16bit</colorDepth>
in the descriptor file?

We'll check/fix this but our initial assumption is that this may be a reason why you're seeing this but we didn't pick it up..

**Comment by ajwfrost** [comment]
.. actually ignore that, one of the team just told me they're seeing this even with that line commented out...

**Comment by ajwfrost** [comment]
Okay so weirdly, this is a function pointer that is set up correctly during initialisation, but is being reset to null at some point during execution, despite having been called correctly several times prior to the crash location.

Building with a different optimisation setting means that the problem goes away. So either this is a strange bug in the compiler, or there's an optimisation that's causing this function pointer to be reset to null - possibly thread-related as this is a background rendering thread that causes the problem.

Needs a little more investigation to work out the best way to solve this one..

**Comment by ToadstoolJam** [comment]
I believe I'm having the same problem with an old app of mine that crashes immediately after the Harman splash screen disappears. I'm new to the Harman built version of the SDK, so I've started with v33.0.2.281 - how can I get hold a previous version so I can confirm this? Any ideas when this will be fixed?

**Comment by ajwfrost** [comment]
Should be a release coming out tomorrow that fixes this, we're just going through QA procedures now... if the call stacks are the same then yes this would be the same issue..

**Comment by ToadstoolJam** [comment]
Brilliant, many thanks. I've found that the armv8 build works correctly on my Pixel XL, but the armv7 build doesn't (but it should).

**Comment by hadisn** [comment]
Hi, my app also crashing... app loads correctly, ad is shown, then when start game is pressed app crashes (AIR - version 33.0.2.281). On AIR SDK 33.0.2.246 works nice. 

Regards

**Comment by mprabhu33** [comment]
Thanks @ajwfrost will check and close this issue.

**Comment by ToadstoolJam** [comment]
33.0.2.288 works for me on armv7 on Pixel XL, no more crashes. Hopefully the OP's issue is also fixed.

**Comment by mprabhu33** [comment]
Working fine with AIR SDK 33.0.2.288.
