### ISSUE TITLE
App crashed with  io_stats error v33.0.2.281

### ISSUE THREAD

**Issue by httpwebmedia** [Gamua/Adobe-Runtime-Support#125]
## Problem Description

Describe your problem in detail. Include the following information:

* Which AIR SDK did you use? 
v33.0.2.281
The prior version 33.0.2.246 works

* Describe the affected environment: Flash vs. AIR, Android vs. iOS, all devices vs. just specific models.
Tested on Android 8.1.0
Samsung Galaxy Tab A (2016) : SM-T580
[DebugLog.txt](https://github.com/Gamua/Adobe-Runtime-Support/files/3717843/DebugLog.txt)

## Steps to Reproduce
We could send you an example on private mailbox.

## Known Workarounds
The workaround is with prior version for now...

**Comment by ajwfrost** [comment]
Duplicate of Issue  #123
