### ISSUE TITLE
URLStream with not available URL throws unhandled error when unsubscribe from IOErrorEvent.IO_ERROR event at HTTPStatusEvent.HTTP_STATUS event handler

### ISSUE THREAD

**Issue by itlancer** [Gamua/Adobe-Runtime-Support#129]
## Problem Description
`URLStream` with not available URL throws unhandled error when unsubscribe from `IOErrorEvent.IO_ERROR` event at `HTTPStatusEvent.HTTP_STATUS` event handler.
It has been tested with many different AIR and Flash Player versions even with latests AIR 32.0.0.144 beta and AIR 33.0.2.281.
Tested with multiple devices across many OSes: Windows, Android, macOS, iOS. 
Same problem in all cases.

Related issue: https://github.com/Gamua/Adobe-Runtime-Support/issues/127

## Steps to Reproduce
Launch code below. It will try to load URL that not available via URLStream and wait for `HTTPStatusEvent.HTTP_STATUS` and `IOErrorEvent.IO_ERROR`. At `HTTPStatusEvent.HTTP_STATUS` event handler (and `IOErrorEvent.IO_ERROR` too) unsubscribe from all these events.
Application example with sources attached.
[urlstream_httpstatusevent_unhandled_error_bug.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/3724536/urlstream_httpstatusevent_unhandled_error_bug.zip)

Calling `URLStream::close()` method at `HTTPStatusEvent.HTTP_STATUS` event handler doesn't help 

```
package {
	import flash.display.Sprite;
	import flash.net.URLRequest;
	import flash.events.HTTPStatusEvent;
	import flash.net.URLStream;
	import flash.events.IOErrorEvent;
	
	public class URLStreamHTTPStatusEventUnhandledErrorBug extends Sprite {
		private var urlStream:URLStream = new URLStream();
		
		public function URLStreamHTTPStatusEventUnhandledErrorBug() {
			var urlRequest:URLRequest = new URLRequest("https://invalid.url/");//Any URL that cause IOErrorEvent.IO_ERROR event
			urlStream.addEventListener(IOErrorEvent.IO_ERROR, urlStream_ioError);
			urlStream.addEventListener(HTTPStatusEvent.HTTP_STATUS, urlStream_httpStatus);
			urlStream.load(urlRequest);
		}
		
		private function urlStream_httpStatus(e:HTTPStatusEvent):void {
			dispose();
		}
		
		//This function will never been called in this example, just to show real use case
		private function urlStream_ioError(e:IOErrorEvent):void {
			dispose();
		}
		
		//Unsubscribe all listeners and null link to urlStream
		private function dispose(): void {
			if (urlStream != null){
				urlStream.removeEventListener(IOErrorEvent.IO_ERROR, urlStream_ioError);
				urlStream.removeEventListener(HTTPStatusEvent.HTTP_STATUS, urlStream_httpStatus);
				urlStream = null;
			}
		}
	}
}
```

**Actual Result:**
Unhandled error `Error #2044: Unhandled IOErrorEvent:. text=Error #2032: Stream Error.` will be throwed by `URLStream` constructor **(!)** just after `HTTPStatusEvent.HTTP_STATUS` event handler will be executed.
```
Error #2044: Unhandled IOErrorEvent:. text=Error #2032: Stream Error.
	at URLStreamHTTPStatusEventUnhandledErrorBug()
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()
```

**Expected Result:**
URLStream complete its life cycle without throwing unhandled errors. Or some mechanism/method should be available at URLStream to prevent this behavior. Using `URLStream::close()` method doesn't help with this issue.

## Known Workarounds
none

**Comment by FliplineStudios** [comment]
The AS3 documentation mentions this for HTTPStatusEvent:

> HTTPStatusEvent objects are always sent before error or completion events.

So it's probably not a good idea to remove listeners and dispose of a URLStream from an HTTP status event, since you'd be prematurely closing it -- the life cycle isn't finished until the complete/ioError event at the end.  

I have noticed that listening for the AIR-specific HTTP_RESPONSE_STATUS instead of the Flash-based HTTP_STATUS seems to get around this problem, though I'm not sure if that's reliable or by design.

**Comment by itlancer** [comment]
> The AS3 documentation mentions this for HTTPStatusEvent:
> 
> > HTTPStatusEvent objects are always sent before error or completion events.
> 
> So it's probably not a good idea to remove listeners and dispose of a URLStream from an HTTP status event, since you'd be prematurely closing it -- the life cycle isn't finished until the complete/ioError event at the end.
> 
> I have noticed that listening for the AIR-specific HTTP_RESPONSE_STATUS instead of the Flash-based HTTP_STATUS seems to get around this problem, though I'm not sure if that's reliable or by design.

@FliplineStudios, thank you!
`HTTP_RESPONSE_STATUS` really works as expected. Seems with `HTTP_STATUS` it cannot be done by design, so I close this issue.
