### ISSUE TITLE
Issue affecting all Landscape AIR apps on iOS iPhone 11 & iPhone 11 Pro Max

### ISSUE THREAD

**Issue by James55p** [Gamua/Adobe-Runtime-Support#133]
## Problem Description

When using an AIR app in Landscape mode, the tap input seems to shift on 2 of Apple's latest devices - iPhone 11 & iPhone 11 Pro Max (appears to be fine on iPhone 11 Pro and all iOS devices below iPhone 11).
Essentially when you tap on the screen, the app seems to think you've tapped to the right (and sometimes diagonally down and to the right) of where you're finger is tapping.
This essentially renders the app unusable as you cannot tap on the User Interface.

*This has been replicated on AIR 32.0.0.116. We haven't updated to AIR 33 yet, but I believe this issue would exist on AIR 33 unless this issue has been specifically fixed, but i've seen no mention of this issue as these devices are fairly new.

*Specifically this issue is only occurring on 2 of Apple's Latest Devices: iPhone 11 and iPhone 11 Pro Max (iPhone 11 Pro appears to respond fine). iPhone X and below are fine.
* The issue only seems to be affecting apps in Landscape orientation.

* I've tested this on our own game: Farm & Craft: https://apps.apple.com/us/app/farm-craft-build-a-township/id953114884?ls=1
Also tested this on Diggy's Adventure: Secret Maze. https://apps.apple.com/US/app/id1067644352?l=en

I've attached a screenshot which shows in RED where my finger is tapping, and the Green Circle is where the app think's I've just tapped. 
![InputTapIssue_Diggy](https://user-images.githubusercontent.com/52780751/67474013-a3a52500-f64b-11e9-919c-c35faeb00965.png)

*NOTE: I don't own an iPhone 11, this has been tested using a real remote device. It would be great if more people who have a iPhone 11 and a landscape app could test this.

## Steps to Reproduce

1. Download and Install an AIR landscape app on iOS, specifically on iPhone 11 or iPhone 11 Pro Max.
2. Try tapping on UI buttons to see if they are responding to where you are tapping.
3. If buttons not responding, try tapping above the button or above and to the left of the button or directly to the left of the button (it seems to vary between apps/buttons).

## Known Workarounds

There are no known workarounds.

**Comment by ajwfrost** [comment]
Thanks for the details, we'll investigate this one when we get the iOS builds out.. 

Odd that it's not consistent here, wondering whether it's relative to the origin i.e. there's some scaling being applied, or whether it's just some sort of offset variable that's not properly zero-initialised..

**Comment by James55p** [comment]
Thanks for this.
Do you have a rough ETA for the iOS builds?

Thanks

**Comment by ajwfrost** [comment]
Hi - aiming for the end of November for this.
thanks

**Comment by FliplineStudios** [comment]
@James55p Any idea if the same issue is occurring on the iPhone XR or the XS Max?  Those have the same resolutions as the 11 and 11 Pro Max, just curious if it's affecting all devices with those resolutions or if it's somehow limited to only the newest ones.

**Comment by James55p** [comment]
@FliplineStudios The issue does not occur on the XS Max - I've just tested this and it's fine. I haven't been able to test it on the XR.
So just seems to be something specifically about the 11 and 11 Pro Max that causes this issue.
Thanks

**Comment by crooksy88** [comment]
Which service are you using to remote test?

**Comment by crooksy88** [comment]
I have just tested my latest landscape iOS app built with 32.0.0.144 on an actual iPhone 11 Pro Max and the touch point registration was perfect.

(app was downloaded from the live App Store).

**Comment by James55p** [comment]
Hi @crooksy88 
OK that's interesting to know.
I'm using a service called pcloudy.com. I've tested other (non AIR) apps in landscape on the iPhone 11 & Pro Max and the touch worked fine, yet both AIR apps on the same test device did not work.

Could you let me know what app you tested on your real device? I can then do the same on the remote device and see if we get the same.

Thanks

**Comment by crooksy88** [comment]
Sure. It was Tour Gallery. You can sign in with 9405.

**Comment by James55p** [comment]
Hi @crooksy88 
OK that's interesting as I can't tap on anything on the Tour Gallery app.

If you get a chance, just to finally put this down to an issue with remotely testing & not an actual AIR bug at all, could you test the touch input on either of these live games:
Farm Craft: Build a Township
Diggy's Adventure: Puzzle Room

Thanks

**Comment by crooksy88** [comment]
Those two app perform as expected on the iPhone 11 Pro Max.
i.e. touch registration is correct.

**Comment by James55p** [comment]
Thanks @crooksy88 
Think it's safe to say I can close this as a non-issue after all.

Thanks all!
