### ISSUE TITLE
IOS Problem,  'ERROR ITMS-90164'  when use a new create distribution .mobileprovision

### ISSUE THREAD

**Issue by KaseYu** [Gamua/Adobe-Runtime-Support#137]
Hello, today, when I submitted the new app to App Stroe, then i found this problem. This app is using a new .mobileprovision file generated from the website. The following message has been displayed during the delivery process:
```
ERROR ITMS-90164: "Invalid Code Signing Entitlements. The entitlements in your app bundle
Signature do not match the ones that are contained in the provisioning profile. According to the provisioning profile, the bundle contains a key value that is not allowed: 'true' for the key 'get-task-allow' in 'Payload/XXXXX. "
```
From the careful comparison of ipa, I found that .mobileprovision, which can be reviewed before, does not add `<key>get-task-allow</key><false/>`.
The content of the file indicated by the error message always has `<key>get-task-allow</key><true/>` (sdk29~sdk33 are the same, changing the 'manifest setting will not work), resulting in uploading The comparison has been wrong. This question hopes to be solved early, thanks.

**Comment by rewb0rn** [comment]
For your release build, make sure you have this in your application.xml:

`<key>aps-environment</key>
<string>production</string>
<key>get-task-allow</key>
<false/>`

**Comment by KaseYu** [comment]
Thank you for your reply. I have added this setting at the beginning. The Info.plist in ipa also appears, but there is still a `<key>get-task-allow</key><true/>` in the binary file.

**Comment by ajwfrost** [comment]
Looks like the provisioning profile format has changed slightly in terms of this entitlement and the differences between development and distribution builds. I think we can work around this so that we only add this entitlement in the bundle if it's explicitly set in the provisioning profile..

**Comment by KaseYu** [comment]
Thanks @ajwfrost ,  add below code is work.  
```
 <iPhone>
        <InfoAdditions><![CDATA[ … probably some things here … ]]></InfoAdditions>

        <Entitlements><![CDATA[

            <key>aps-environment</key>

            <string>production</string>

            <key>get-task-allow</key>

            <false/>

        ]]></Entitlements>
        …
    </iPhone>
```
Expected that @ajwfrost can find the problem of the certificate as soon as possible.

**Comment by ajwfrost** [comment]
The initial issue was due to us not recognising a production certificate as such; Apple have changed the format/description used in these.. easy to update, will get this into our forthcoming release..

**Comment by KaseYu** [comment]
In AIR SDK 33.0.2.315 is solved, thanks @ajwfrost .
