### ISSUE TITLE
Stage shift offset error on StageText focus

### ISSUE THREAD

**Issue by BenLeffler** [Gamua/Adobe-Runtime-Support#14]
## Problem Description

When the soft keyboard is invoked under certain circumstances, the Stage3D and classic display list layers shift further up than the StageText layer does. 

* A new ticket in the Adobe Bug Base has been opened here: [https://tracker.adobe.com/#/view/AIR-4198421](https://tracker.adobe.com/#/view/AIR-4198421)
* This appears to be not too dissimilar to a prior ticket reported (and closed) here: [https://tracker.adobe.com/#/view/AIR-4198258](https://tracker.adobe.com/#/view/AIR-4198258). 
* Air SDK v26.0.0.118 - (Also replicated on the current Air 27 BETA)
* Issue affects Air on Android.
* Replicated on a Galaxy S8+ running Android 7.0 with Samsung Experience 8.1 skin

## Steps to Reproduce

* build app with manifest stating "aspectRatio" set to portrait, and "fullScreen" set to false
* The Android bar that appears down the bottom can be dismissed in Samsung Experience 8.1 by tapping the dot on the far left of the bar:
![ss01](https://user-images.githubusercontent.com/3096583/29162525-1095a0c8-7dfd-11e7-8e50-066d87cf3ec5.jpg)
* This sends the app in to a semi fullscreen mode (The top bar remains, but the bottom bar becomes hidden - I believe this is a feature possibly introduced by latest Samsung's android skin): 
![ss02](https://user-images.githubusercontent.com/3096583/29162526-10a1ae5e-7dfd-11e7-81bd-f2625122721f.jpg)
* Add a StageText object to the app and the user taps it to assigns focus to it, thus invoking the soft keyboard. In doing this, the bottom bar will reappear beneath the soft keyboard:
![ss03](https://user-images.githubusercontent.com/3096583/29162527-10a44cfe-7dfd-11e7-9836-bfb26b6f3a16.jpg)
* When the bottom bar is reintroduced and focus is given to the StageText object (as per the above point), all layers are uniformly offset and render correctly:
![ss04](https://user-images.githubusercontent.com/3096583/29162528-10a8dd28-7dfd-11e7-9795-e1a4957e0f3b.jpg)

## Known Workarounds

None that I know of. However I have noticed that when the bottom bar has been collapsed in this way, the stage.stageHeight value is > the stage.fullScreenHeight value. So in theory it should be an issue that can be identified at runtime and adjustments made to the StageText object y position. But this is not ideal and can have ramifications when a user dismisses the soft keyboard without revoking focus from the StageText object.

**Comment by PrimaryFeather** [comment]
I was just notified by Adobe that this bug should be fixed in the latest AIR SDK beta version. Could you try that out, Ben, and close the bug if that's the case? Thanks a lot in advance!

**Comment by BenLeffler** [comment]
I can confirm that this issue has been fixed.

**Comment by PrimaryFeather** [comment]
Thanks, Ben!
