### ISSUE TITLE
No export in Flash Builder for Android with armv8 and no error is reported

### ISSUE THREAD

**Issue by Marcophono2** [Gamua/Adobe-Runtime-Support#140]
Hello!

Windows 10 (64)
Flash Builder 4.7 (with jre1.8.0_112)
AIR SDK 33 build 288
All ANE are on 64bit

As described I added the -arch armv8 parameter to the custom launch in Flash Builder. (But I did not add it behind "target" but before "storetype" as suggested in a forum. Otherwise the process stopped with an error.) Also I tried to uncomment the parameters in the adt.cfg. But it is not possibloe to export the apk file. The packaging process seems to work as usual and it finishes without any error. But in the target folder no apk file is placed. By the way also changing the parameter value to armv7 leads to the same result.
Am I the only one with that problem?

Best regards
Marc

**Comment by Marcophono2** [comment]
Solved it! I also edited the "APPLICATION" parameter. As a value I just added the absolute address where I want the apk be saved. No idea why Flash Phoner is not able to understand the relative path if adding the "arch" parameter. Stupid, stupid guys at Adobe! I found a 5 years old forum where that bug was described and there was noone able to fix it. 

Best regards
Marc

**Comment by armmywg** [comment]
Refer to your method, I can also work normally
thanks
