### ISSUE TITLE
Unable to install 64 bit version of APK.

### ISSUE THREAD

**Issue by OlalaEvolve** [Gamua/Adobe-Runtime-Support#154]
Compiled 32 bit and 64 bit APK. 32 bit is installed on the smartphone, 64 bit is not. Simply closes when installed without errors. Below is the Android log.

> ActivityManager
> START u0 {act=android.intent.action.VIEW dat=file:///storage/emulated/0/Download/MA3364.apk typ=application/vnd.android.package-archive flg=0x10000000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity} from uid 10248 on display 0
> ActivityManager
> START u0 {dat=file:///storage/emulated/0/Download/MA3364.apk cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallAppProgress (has extras)} from uid 10043 on display 0
> DefContainer
> Copying /storage/emulated/0/Download/MA3364.apk to base.apk

Animate CC 2019 + AIR 33.0.2.315
Smartphone Sony Xperia Z3 D6603, Android version 6.0.1
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

Also tested on different devices and on different versions of Android.

**Comment by Oldes** [comment]
Your phone is does not support armv8 (only 32bit), I would guess.

**Comment by OlalaEvolve** [comment]
The issue has been resolved. Indeed, all devices that put the app do not support ARMv8. D seek with support)) thank you.
