### ISSUE TITLE
Catalina AIR33.0.2.330 /compile-abc: Bad CPU type in executable

### ISSUE THREAD

**Issue by jasonJamEther** [Gamua/Adobe-Runtime-Support#160]
I was hoping that Air33.0.2.330 would allow me to publish my iOS app on Catalina (Adobe Animate) and submit it to the app store. When I publish I get the following error:

/var/folders/ks/ccypg9_12zlbbw917_vvszkc0000gn/T/cmd3619559645739052090.tmp: line 2: /Applications/Adobe Animate 2020/AIR33.0.2.330/lib/aot/bin/compile-abc/compile-abc: Bad CPU type in executable

When I publish with 33.0.2.315, the app compiles but I receive an error when uploading to the app store concerning arm64. This appears to be a known issue already documented. It sounded like 330 was the solution.

I do have quite a few ANEs by distriqt in my app but thought the error might be obvious enough to indicate the problem to someone smarter than I am.

**Comment by ajwfrost** [comment]
Hi
The 33.0.2.330 release had a problem in recognising Catalina, there's an updated ADT.jar file available from the link below that should correct this..
https://github.com/Gamua/Adobe-Runtime-Support/files/3904090/adt.zip

**Comment by jasonJamEther** [comment]
That seems to have done the trick. I replaced the ADT.jar file and it published correctly and I was able to upload it to the app store. Thank you!

**Comment by af-vs** [comment]
Hi!

Is there any place where we could find all the versions of the ADT so we can track if there are any updates? Thanks!

**Comment by af-vs** [comment]
@ajwfrost Thank you for your quick reply! 👍
