### ISSUE TITLE
iOS Interruptions such as incoming calls break audio (again)

### ISSUE THREAD

**Issue by douglasmccarroll** [Gamua/Adobe-Runtime-Support#161]
Problem Description:

In an iOS AIR app that plays audio using Sound.play(), if the app is interrupted audio no longer works.

The interruption can be an incoming phone call, the Clock app playing an alarm, etc.

Note: This behavior is the same as was reported and fixed in AIR 26 - [https://tracker.adobe.com/#/view/AIR-4198386](https://tracker.adobe.com/#/view/AIR-4198386)

I've attached a minimal demo app that demonstrates this behavior.

Steps to Reproduce:

1. Build the attached minimal sample app and install on iPhone using and AdHoc certificate.

2. Click button and note click sound.

3. Call phone from another phone.

4. Reject call, or answer call and then hang up.

5. Click button.

Actual Result: Silence (~90% of the time)

Expected Result: Click sound

Workaround: Press iPhone Home button. Return to app. Sound now works again.  

[MinimalApp_InterruptionsKillAudio.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/3913252/MinimalApp_InterruptionsKillAudio.zip)

**Comment by douglasmccarroll** [comment]
I neglected to mention: I'm using AIR 33

**Comment by douglasmccarroll** [comment]
I've solved my problem by doing this:
SoundMixer.audioPlaybackMode = AudioPlaybackMode.AMBIENT;

I suppose this is still a bug, as it doesn't seem that this behavior should occur with AudioPlaybackMode.MEDIA, but in my case, at least, using AMBIENT solves the problem.

**Comment by LarsLaborious** [comment]
Using _SoundMixer.audioPlaybackMode = AudioPlaybackMode.AMBIENT_ may lead to bad reviews (it has for me), because it enables the sound to be toggled off by using the sound switch on the side of iPhones and old iPads or the virtual sound icon (swipe up from the bottom or down from the top right corner on newer iPads). Unfortunately people can mute the sound by accident and when trying to raise the volume with the volume buttons there's still no sound and they assume there is a problem with the app.

**Comment by douglasmccarroll** [comment]
This workaround seems to work in my app (using Flex framework):

NativeApplication.nativeApplication.addEventListener(Event.ACTIVATE,onActivateApp);
NativeApplication.nativeApplication.addEventListener(Event.DEACTIVATE,onDeactivateApp);

private function onActivateApp(event:Event):void {
   SoundMixer.audioPlaybackMode = AudioPlaybackMode.MEDIA;
}

private function onDeactivateApp(event:Event):void { 
   SoundMixer.audioPlaybackMode = AudioPlaybackMode.AMBIENT;
}

**Comment by douglasmccarroll** [comment]
I'm sorry to report that the possible solution I reported above, i.e. setting SoundMixer.audioPlaybackMode when the app deactivates and activates isn't working reliably.

**Comment by douglasmccarroll** [comment]
I'm (exceedingly! :) happy to confirm that this issue is fixed. Closing.
