### ISSUE TITLE
Displaying a VideoTexture Eventually Freezes Visuals

### ISSUE THREAD

**Issue by esidegallery** [Gamua/Adobe-Runtime-Support#17]
## Problem Description
Running a VideoTexture for long enough will eventually cause the visuals to freeze. It's the equivalent of having skipUnchangedFrames set to true in Starling i.e. The sound continues and if the window is resized, then the frame updates.

- **AIR SDK used:** 26.0
- **Environment:** AIR for Windows (Captive runtime and otherwise). Windows 10 32-bit confirmed.
- **[Adobe Bug Tracker Issue](https://tracker.adobe.com/#/view/AIR-4198452)**

## Steps to Reproduce
1. Create an application that plays a video from a local file using `VideoTexture`
2. Cause the video to loop, in this case using the 'appendBytes' method to avoid [this issue](https://tracker.adobe.com/#/view/AIR-4198451).
3. Run the app. Usually, after a few hours of constant video playback, the video freezes.

[Here is a minimal application that exhibits the problem](https://www.dropbox.com/s/8jrtmq9djcrr84u/VideoTextureCrashAppendBytes.zip?dl=0). This zip file can be imported directly into Flash Builder.

Here are compiled versions of the above app that can be run straight away:
- [AIR File](https://www.dropbox.com/s/3g0k8qat5jxvyx5/VideoTextureCrashAppendBytes.air?dl=0)
- [Captive Runtime](https://www.dropbox.com/sh/91icxbmkf23dtic/AABKsOwAyJpnxoMtazCHJbppa?dl=0)

To minimise dependencies, and to rule out framework bugs, this app does not use Starling, but the same behaviour is exhibited when Starling is used.

## More Info
- [Specs of machine that exhibits the bug](https://www.dropbox.com/sh/h2wqkzucwsjns84/AABqaC8FRbjcurAaUthpnG6Oa?dl=0)
- [Specs of another machine that exhibits the bug](https://www.dropbox.com/sh/y6kxtghbqyr8bmr/AABPY6GRfp1E9VPoxrZTY0APa?dl=0)

## Known Workarounds
None that I am aware of. Perhaps if it were possible to detect when the problem arises and dispose of the context, triggering a rebuild.

**Comment by tuarua** [comment]
@esidegallery 

There was a surprise beta release today which appears to mention a fix for this in the release notes

> [AIR] crashing when playing video loops for many hours (FLASH-4190569)

http://fpdownload.macromedia.com/pub/labs/flashruntimes/shared/air31_flashplayer31_releasenotes.pdf

**Comment by esidegallery** [comment]
Thanks for bringing this to our attention @tuarua! Haven't had the chance to test yet, but will soon and post an update...

**Comment by itlancer** [comment]
For me this issue finally fixed with AIR 32.0.0.83 beta. Thanks for Adobe!

**Comment by esidegallery** [comment]
I have been able to run a video using the 'appendBytes' method for 3 days without any issues. Would like to try it on a few other machines too, but this looks promising. Thank you Team Adobe!

**Comment by PrimaryFeather** [comment]
That's great news, thanks a lot for testing this out, guys! I'll close this issue then. In case something *does* still pop up, we can still re-open it anytime.
