### ISSUE TITLE
How to enable Apple sign in  service for AIR like in Xcode11

### ISSUE THREAD

**Issue by AdamSun** [Gamua/Adobe-Runtime-Support#173]
## How to enable Apple sign in  service for AIR

Since AIR iOS packpage is not a Xcode project, how to enble  Apple sign in  service like selecting the option of "sign in with Apple" in the "Xcode11 Signing & Capabilities" page of Xcode11, the setting is like this:
![image](https://user-images.githubusercontent.com/7380017/70402723-4fc19480-1a6f-11ea-9045-95225a4a0439.png)

## Known Workarounds

None

**Comment by marchbold** [comment]
This should just be set in the entitlements section of your application descriptor and settings in the apple developer console.

**Comment by marchbold** [comment]
Add this to your entitlements:

```xml
<key>com.apple.developer.applesignin</key>
<array>
    <string>Default</string>
</array>
```

**Comment by AdamSun** [comment]
Hi, marchbold, I will try and thank you

**Comment by AdamSun** [comment]
solved
