### ISSUE TITLE
SystemIdleMode.NORMAL doesn't work on Android

### ISSUE THREAD

**Issue by marcanw** [Gamua/Adobe-Runtime-Support#176]
## Problem Description
I noticed lately that after using `NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.KEEP_AWAKE;`
and  later `NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.NORMAL`; the device stays awake forever.
I checked my manifest and both related permissions was present:
```
<uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
```

* Which AIR SDK did you use? Hint: always try the latest version from [Adobe Labs]
AIR 33.0.2.315
* Describe the affected environment: Flash vs. AIR, Android vs. iOS, all devices vs. just specific models.
Android (Huawei P20, One+, Samsung A5
* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?
All device tested

## Steps to Reproduce

use `NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.KEEP_AWAKE;`` then
NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.KEEP_NORMAL;`

## Known Workarounds
I would like

**Comment by marcanw** [comment]
It seems to work fine now...

**Comment by rdefalco** [comment]
As strange as it may seem... but I have exactly this issue forever on Android, even with AIR 51.2 + FeathersSDK + Starling

If I ever set 
`NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.KEEP_AWAKE;` 
trying to set it back to
`NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.NORMAL`
has no effect, the display stays on no matter how long you wait...

EDIT: it seems that in some manifest evolution over time, we removed the permissions WAKE_LOCK and DISABLE_KEYGUARD, and without these permissions the app kept the screen on (when asked) but couldn't restore the normal behavior. Once I've added the permissions again, the app started behaving correctly
