### ISSUE TITLE
Will Air publish to Html5?

### ISSUE THREAD

**Issue by fftidus** [Gamua/Adobe-Runtime-Support#181]
Apple has banned the html5 technology of APP,so other h5 engines can't publish app for Apple store next year!
If air can publish html5,it can be the  true cross-platform engine.

**Comment by neuronix** [comment]
Please read the FAQ: https://airsdk.harman.com/faq

To keep the issues list clean, please close your issue and next time check https://forum.starling-framework.org/ first where you will generally find quick & good answers :)

**Comment by rewb0rn** [comment]
As the year closes, it would be a great time to get an update on this or an update on the future of the Air roadmap in general. Html5 target would definitely be on our wishlist, apart from keeping the current platform targets alive and well (Harman is already doing a great job with this).

Meanwhile, porting our codebase from AS3 to Haxe has proven to be a good choice to both provide swf / Air targets as well as HTML5.

**Comment by ajwfrost** [comment]
Briefly..

Support for the other platforms is coming! slower than I had hoped, we've hit a few snags but are getting through them with support from Adobe. And we're looking forward to some of the changes we can then bring to the platform to address some of the bugs and add a few tweaks and new features in the APIs.

In terms of HTML based support, we have an interesting discussion going on with a third party that might be able to help enable this. We should know more around March/April time.

thanks

**Comment by tuarua** [comment]
> Support for the other platforms is coming!

@ajwfrost Is there an ETA on AIR being updated so that it is compiled against iOS SDK 13 ?
I have hit a blocker because it is still 12 and despite setting platformsdk I am getting linking issues against a Swift static library.
