### ISSUE TITLE
[Feature Request] Serial port communication support

### ISSUE THREAD

**Issue by itlancer** [Gamua/Adobe-Runtime-Support#187]
## Feature Description
Communication via serial port support could be very useful for AIR.
It could make easier to integrate with different hardware devices, sensors, Arduino, GPIO and RS232/COM-port peripherals.
Many POS-terminals, retail, museum and enterprise devices/solutions required such integrations.

Related issue: https://tracker.adobe.com/#/view/AIR-3803837

## Known Workarounds
- write native extension (or use something like that https://github.com/quetwo/as3-arduino-connector)
- use some hacks with redirecting serial communication to socket https://ravigeek.wordpress.com/2010/08/18/readwrite-to-serial-port-from-adobe-air/

**Comment by barisyild** [comment]
You can provide this feature by writing Native Extension.

**Comment by itlancer** [comment]
@barisyild,
Yes, I done. But there is no good open-source crossplatform native extension for AIR right now. May be there is no reason to include such functionality to AIR core - well documented cross platform native extension will be good for most developers who would like to easily implement solutions with AIR using serial port communication.

**Comment by JohnBlackburne** [comment]
I would think an ANE makes more sense too. It’s too niche to go into AIR itself, as only useful to a small number of users. None of iOS, Android and Mac have serial ports, and few Windows PCs do today (a ten year old Windows laptop I have here doesn’t). Most peripherals and connected devices now use USB, Wifi, Bluetooth or some combination, including Arduino.

At least this simplifies ANE development, as it only needs to support Windows, and can be tuned and tested for whichever particular device you want to use it with.

**Comment by itlancer** [comment]
Mostly agree with you about native extensions concern.
But serial communication is not only about old school big 9-pin COM port connector. It could look like mini audio jack, UART etc.
Many sensors inside laptop or phone still uses serial communication.
Devices doesn't need to have full native COM port. Many USB-to-COM adapters or other physical connectors could be used. Serial communication is just a data transfer mechanism, not a physical connection. So it still appliable to Windows, macOS and Android devices.
