### ISSUE TITLE
Can't build IPA on MacOS 10.15 Catalina --  ld: library not found for -lclang_rt.ios

### ISSUE THREAD

**Issue by shaymolho** [Gamua/Adobe-Runtime-Support#188]
Hi

I upgraded my Mac to the new version MacOS 10.15 and since then i cannot build the IPA.

I tried to build it as i used to with AIR 32 and failed. I read in another post in this forum that it is no longer possible to build with AIR 32 on the new mac version.
Then i tried with AIR 33. Got the first error about the "ld" Permissions issue. I fixed it as suggested in the post, and now i'm getting the following error:

```
     [exec] Compilation failed while executing : ld64
     [exec] ld: library not found for -lclang_rt.ios

```

Does anybody else encounter this problem?

**Comment by marchbold** [comment]
you will need to copy the library `libclang_rt.ios.a` into your AIR SDK and place it at: [AIR_SDK]/lib/aot/lib

You can grab the library file here: https://www.dropbox.com/s/kvhk8yxxomy3tpn/libclang_rt.ios.a?dl=0 or from the Xcode installation on your machine, something like:

```
/Applications/Xcode.app//Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/lib/darwin/libclang_rt.ios.a
```


We have asked Harman to start including this lib: https://github.com/Gamua/Adobe-Runtime-Support/issues/113

**Comment by shaymolho** [comment]
@marchbold you're everywhere :)

It worked.
Thank you!
