### ISSUE TITLE
Cannot launch and test application with AIR 33.1.0.16 and Adobe Animate CC

### ISSUE THREAD

**Issue by itlancer** [Gamua/Adobe-Runtime-Support#204]
## Problem Description
Cannot launch and test application with AIR 33.1.0.16 and Adobe Animate CC.
After application compilation IDE throws error about unknown namespace.

Tested with Adobe Animate CC 18.0.2 for Windows and with Adobe Animate CC 20.0 for macOS.
The same problem in both cases with any AIR project.
It works fine with AIR 33.0.2.338 and earlier.

Manually changing application descriptor namespace to 33.1 didn't resolve this issue - IDE override it.

## Steps to Reproduce
1) Open Adobe Animate CC, create new one AIR project (or open existing one).
2) Try to test it (or simply press Ctrl+Enter).

**Actual Result:**
Got error:
`invalid application descriptor: Unknown namespace: http://ns.adobe.com/air/application/33.0`

**Expected Result:**
Application will be compiled and launched.

## Known Workarounds
none
*use another IDE

**Comment by hcsuk** [comment]
Ah - so it looks like we left some invalid namespace values in the SDK, please can you edit:
samples\descriptor-sample.xml
and change the namespace at the start of that to be 33.1 rather than 33.0.

Thanks!

**Comment by itlancer** [comment]
Yeah, that did a trick. Now it works fine.
Hope to see this fix soon in production release.
Thank you!

**Comment by itlancer** [comment]
Fixed with latest AIR 33.1.1.50 production version.
Thank you!
