### ISSUE TITLE
[Windows][macOS] EncryptedLocalStore doesn't work with AIR 33

### ISSUE THREAD

**Issue by itlancer** [Gamua/Adobe-Runtime-Support#205]
## Problem Description
`EncryptedLocalStore` doesn't work with AIR 33 for Windows and macOS devices.
It just throw exception when you try to use it.
Tested with AIR 33.0.2.338 and AIR 33.1.0.16 with different Windows devices with different OS versions with 32-bit and 64-bit AIR applications with captive runtime. Also tested with AIR 33.1.0.16 on macOS Catalina 10.15.2.
Same problem in all cases.

It works fine for the same devices with the same OS version with AIR 32.0.0.89, AIR 32.0.0.144 beta and below.
Also it works fine with AIR 33.1.0.16 for Android, iOS and tvOS.
`EncryptedLocalStore.isSupported` always returns `true` in all these cases.

Related issue (not the same): https://github.com/Gamua/Adobe-Runtime-Support/issues/165

## Steps to Reproduce
Launch code below.

Application example with sources attached.
[encrypted_local_store_bug.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/4093956/encrypted_local_store_bug.zip)

```
var bytes:ByteArray = EncryptedLocalStore.getItem("test");
```

**Actual Result:**
Exception will be throwed:
```
Error: EncryptedLocalStore is out of memory
	at flash.data::EncryptedLocalStore$/processErrorCode()
	at flash.data::EncryptedLocalStore$/getItem()
	at EncryptedLocalStoreBug()
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()
```

**Expected Result:**
`EncryptedLocalStore.getItem` returns `ByteArray` with data of specified name without exceptions.

## Known Workarounds
none

**Comment by itlancer** [comment]
Issue still exists with latest AIR 33.1.1.50.

**Comment by toysonlocation** [comment]
And still exists with AIR 33.1.1.63

Has this thread been observed by support?

**Comment by ajwfrost** [comment]
Yes we’re aware of this. The encryption in AIR32 uses some components that are private to Adobe so we’re going to need to re-implement this functionality using a new mechanism.

**Comment by Formability** [comment]
I get this error on the debugger on Windows with version 33.0.2.338.

Error: EncryptedLocalStore is out of memory

Is there any other information I can provide you to aid in resolving this?

**Comment by ajwfrost** [comment]
Thanks - yes it says out of memory because the internal pointer is null so it assumes there was no memory left for creating the store, whereas actually the pointer is null because the feature is disabled...

**Comment by barisyild** [comment]
It works fine at 33.0 but not working at 33.1.
When will this problem be solved?

**Comment by ajwfrost** [comment]
We'll need to look at how best to re-implement this.. I can bump this into our next scheduled release (after the one that's coming out this week) so should be around the end of April.

**Comment by stoff99** [comment]
I can confirm that its not working on desktop ADL emulator. (MacOS)
On iOS and Android its working fine.
Waiting for news around the end of April. ;)

**Comment by Ender22** [comment]
This one is critical for me as well, can't use Air 33 until it is resolved

**Comment by mayainle** [comment]
Any news on this one? We have the same issue.

**Comment by tidus2020** [comment]
Come on , we go this too.....

**Comment by Danik** [comment]
I have the same issue, glad to hear you are aware of it!

**Comment by ajwfrost** [comment]
Hi all - just to provide an update on this, we looked into it and it initially appeared as if there would be some license-based challenges to get this working the same way that Adobe had done. However we've talked with them and it looks like it should be possible to reimplement this in the same way - there are a few delays due to the lockdown situation that may slow us further but we're actively looking at this again now so hoping to have better news soon..

thanks

**Comment by Danik** [comment]
That's great news, thanks for the update!

**Comment by ajwfrost** [comment]
Hi again.. further update as it appears that we do after all have some issues with code access for this.. which means we will need to have a break in compatibility I'm afraid. This means that it would not be possible for ELS data that was created using AIR 32 (or earlier) to be read by AIR 33 onwards..

This obviously isn't ideal but can I check whether for anyone on here it would make it completely useless? 

thanks

**Comment by Formability** [comment]
> Hi again.. further update as it appears that we do after all have some issues with code access for this.. which means we will need to have a break in compatibility I'm afraid. This means that it would not be possible for ELS data that was created using AIR 32 (or earlier) to be read by AIR 33 onwards..
> 
> This obviously isn't ideal but can I check whether for anyone on here it would make it completely useless?
> 
> thanks

Is that referring to the Windows/ Mac versions or will that include the iOS and Android versions?  It would be awkward but not completely useless if its just the windows/ Mac version.  If the mobile platforms are also included in this code change then that would not work for us.

**Comment by tidus2020** [comment]
> Hi again.. further update as it appears that we do after all have some issues with code access for this.. which means we will need to have a break in compatibility I'm afraid. This means that it would not be possible for ELS data that was created using AIR 32 (or earlier) to be read by AIR 33 onwards..
> 
> This obviously isn't ideal but can I check whether for anyone on here it would make it completely useless?
> 
> thanks

We use it to save a random meid on the iphone without ANE....

**Comment by Ender22** [comment]
> Hi again.. further update as it appears that we do after all have some issues with code access for this.. which means we will need to have a break in compatibility I'm afraid. This means that it would not be possible for ELS data that was created using AIR 32 (or earlier) to be read by AIR 33 onwards..
> 
> This obviously isn't ideal but can I check whether for anyone on here it would make it completely useless?
> 
> thanks

Since ios and android are currently fine I assume this change would only affect Windows and Mac? If so it will be fine for us, if not then all of our mobile users will get forcibly logged out which would be not great.

**Comment by itlancer** [comment]
@ajwfrost, we use ELS for Windows, macOS, Android and iOS to save critical data and user identifiers. Without backward compatibility all this data will be lost and we can't even migrate it. It not acceptable for us.

**Comment by ajwfrost** [comment]
Thanks for all the inputs. We wouldn't need to change the ones that currently work (Android for example isn't actually encrypted anyway so that's simple .. I'm interested if iOS works with 33.1, this might actually give us some clues as to the encryption mechanisms..)

Given the above comment in terms of backwards compatibility, we'll look further at reverse engineering and seeing whether we can work out how to open the current format ELS. Might take a bit of time I'm afraid..

thanks

**Comment by ajwfrost** [comment]
Okay so we've had a bit of a breakthrough here, and have this working (at least on Windows, but we believe we have the mechanisms to get this also working on MacOS as it was earlier). Needs tidying up but I thought I'd let you know this is on its way. We'll also look to fix #165 and maybe see what we could do about #229, although I think that one might need to come later..

So to confirm:
* Windows and MacOS - will work in the same way as previous, with Adobe's encryption mechanisms
* iOS and Android - already working with the same mechanism as they'd done previously

thanks

**Comment by DQvsRA** [comment]
Still have this problem on MacOS with latest AIR
```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G84
```
```
<?xml version="1.0"?>
<air-sdk-description>
<name>AIR 33.1.1</name>
<version>33.1.1</version>
<build>98</build>
</air-sdk-description>
```

**Comment by ajwfrost** [comment]
Yes, we've not yet released this. Have just got an update on MacOS - when you try to read an existing ELS file, it's asking for the keychain password to the user, so something's not right there... but we should be able to get this sorted and into a release later this month.

**Comment by Danik** [comment]
@ajwfrost Maybe this is unrelated, but I had the same issue when I updated the signing certificate of my AIR application from a self signed one to an Apple developer cert. The old ELS data could be read if the user just pressed Accept without any password, but the user had to delete the ELS folder and let it be recreated by the new application for the keychain popup to stop appearing.

**Comment by ajwfrost** [comment]
@Danik Thanks - yes we're finding that we can just hit 'Accept always' and it no longer appears - although in code, this comes just after something that tries to avoid any pop-ups from happening!

@hardcoremore that one is still under investigation, I had hoped we can still get it in but only if we get a breakthrough soon.. looking to release the next version prior to the end of this month, we have a few more tasks to complete on both Android and iOS first..

thanks

**Comment by hardcoremore** [comment]
Well as long as it works with latest iOS and Android its great but if AIR really has version 3.7.4 it means  that its from 2010 12 07, almost 10 years old :O As you can see from here

[https://www.sqlite.org/changes.html](https://www.sqlite.org/changes.html)

the biggest feature that I would like to be added into SQL lite is ability to change column names in a table.

**Comment by DQvsRA** [comment]
Just want to know what is progress on this issue?

**Comment by ajwfrost** [comment]
@DQvsRA  - we have this all working, it will be going into the release that we're preparing (for the end of this week as long as it passes the QA..)

thanks

**Comment by ajwfrost** [comment]
@DQvsRA just a quick update as you may have noticed, no release arrived because QA found two issues - which have both since been fixed so we're preparing the release now. Should be available in a couple of days... apologies for the delay!

**Comment by Devkjk** [comment]
I need to update iOS app asap,but for this error I can not preview swf.
Is there another way to update?And how to?
Anyway good luck new sdk release.

**Comment by itlancer** [comment]
@ajwfrost 
With latest AIR 33.1.1.176 `EncryptedLocalStore` seems work fine with macOS devices but with Windows devices it only works previously created ELS data (with AIR 32 or below).
If you try to launch code from this issue with AIR 33.1.1.176 without previously created ELS data (or just delete `c:\Users\<username>\AppData\Roaming\<app_id>\ELS` folder) then you will get exception:
```
Error: EncryptedLocalStore database access error
	at flash.data::EncryptedLocalStore$/processErrorCode()
	at flash.data::EncryptedLocalStore$/getItem()
	at EncryptedLocalStoreBug()
```
So this issue fixed only partially for Windows platform.

**Comment by ajwfrost** [comment]
@itlancer  just as an update, we found a problem in the key generation code which caused the problems when creating a new ELS on Windows. Fix will be out shortly..

**Comment by itlancer** [comment]
It works fine again with latest AIR 33.1.1.190 for Windows and macOS platforms.
Thank you!
But related issue still not fixed: https://github.com/Gamua/Adobe-Runtime-Support/issues/165
