### ISSUE TITLE
[Feature Request] Override "draw" for IBitmapDrawable

### ISSUE THREAD

**Issue by itlancer** [Gamua/Adobe-Runtime-Support#215]
## Feature Description
Override "draw" for `IBitmapDrawable` could be useful to change (or create) final `BitmapData` representation of `DisplayObject` or `IBitmapDrawable`. To make it possible to "render" (create) `IBitmapDrawable` `BitmapData` by yourself when you use `BitmapData::draw()`.
It could be `IBitmapDrawable` interface method or new interface.

Such feature very handy for many cases such as:
- Change only one (or few) `DisplayObject` representation as `BitmapData` in complex nested UI with multiple layers when you use `BitmapData::draw()` method to draw "root" object with "all other DisplayObjects included". Something like "controllable screenshot".
- Change some `DisplayObject` representation as `BitmapData` when you use `BitmapData::draw()`.
- Create "full screenshot" of stage (scene) where not only `DisplayObject` but also `StageWebView` or `Stage3D` layers. Using "empty Sprites" for example you can save "layers" ideology but easily draw such layers to final `BitmapData`.
- Easily make your own DRM, watermark etc to control what will be at the final `BitmapData` when you need to draw some part of application.
- Easily make screenshot with "layers" displayed via native extensions or some other way which is not `DisplayObject` but you can get it `BitmapData` representation with some other way.

## Known Workarounds
Write your own "draw" method with your own overriding and implementation and class types (interfaces) checks. Write something like renderer or `BitmapData` drawer.

**Comment by JohnBlackburne** [comment]
I have used `BitmapData.draw()` extensively when working with the classic Flash API, but I am unclear what you are asking for. `BitmapData.draw()` implements a couple of low level routines, one which “draws” a `BitmapData` into another `BitmapData`, and one which “draws” a `DisplayObject` into one, hooking into the drawing code in the right place to do this.

You can’t write code which works the same way, as you can’t hook into the drawing code. Also as the existing `BitmapData.draw()` can draw everything that’s drawable in the classic API it’s hard to see what you would add.

For a “controllable screenshot” do what is commonly done in rendering to deal with different rendering passes (e.g. for shadows), maintain multiple DisplayObjectContainer hierarchies, one for renderiing, one for screenshots.

**Comment by itlancer** [comment]
Mostly agree with your reasoning because we really cannot override internal drawing routines. Different rendering passes looks like best approach for that.
Thank you.
