### ISSUE TITLE
[Feature Request] WebSocket support

### ISSUE THREAD

**Issue by barisyild** [Gamua/Adobe-Runtime-Support#216]
WebSocket support must be added.

**Comment by marchbold** [comment]
Have you tried using a ServerSocket ?

**Comment by barisyild** [comment]
It is possible with 3rd party libraries, but I want native support.

**Comment by marchbold** [comment]
What advantage would inbuilt support give you? Please detail your request.

**Comment by barisyild** [comment]
If html5 target support is available in the future, it will be useful for us, and the third party libraries have high latency.

**Comment by zwetan** [comment]
> the third party libraries have high latency.

no they don't, not much or less than using the native `Socket` class

the [WebSocket API](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) is mainly dependant on connecting to a WebSocket server to "receive event-driven responses without having to poll the server for a reply"

so within AIR you're talking about implementing a WebSocket client
which would be better suited as library than a native implementation

you already have all the native parts with `Event` and `Socket`
