### ISSUE TITLE
Error #3672: Buffer creation failed. Internal error in Air27

### ISSUE THREAD

**Issue by yooni126** [Gamua/Adobe-Runtime-Support#23]
Im Using Air27

and see this error when i use videoPlayer(feather)
[Fault] exception, information=ArgumentError: Error #3672: Buffer creation failed. Internal error.
in windows,I dont have any issue but when I compile my app in mobile, I see wired errors with this videoPlayer like:
[Fault] exception, information=RangeError: Error #1125: The index 1 is out of range 1.
Fault, getBatchAt() at BatchProcessor.as:138

**Comment by PrimaryFeather** [comment]
Sorry for not commenting on this issue earlier!

This report is too vague for an "Adobe-Runtime-Support" issue. We need to have more information to be able to get this to Adobe's attention.

Furthermore, this somehow seems to be too different problems: one is the "buffer creation failed" error, which can indeed be a Stage3D issue. The other, the "RangeError" seems to be a problem in Starling.

If this is still happening to you, please create a report in [Starling's issue tracker](https://github.com/Gamua/Starling-Framework/issues) and try to add as much information as possible about what's happening and how we could reproduce it. Thanks a lot in advance!
