### ISSUE TITLE
[AIR 33.1.0.37 beta+][macOS][Android] HARMAN splash screen with license

### ISSUE THREAD

**Issue by itlancer** [Gamua/Adobe-Runtime-Support#231]
## Problem Description
HARMAN splash screen appears with valid `adt.lic` license file usage when you build application for Windows, macOS or Android platform when you use AIR 33.1.0.37 beta or AIR 33.1.0.43 beta.

It has been tested with latest AIR 33.1.0.37 beta and AIR 33.1.0.43 beta with Windows, macOS and Android devices. Tested with different applications.
Same problem in all cases.

It works fine with iOS.
Also It works fine with AIR 33.0.2.338 with any platform.

## Steps to Reproduce
Build and launch any AIR application with Windows, macOS or Android device with AIR 33.1.0.37 beta or AIR 33.1.0.43 beta.

**Actual Result:**
HARMAN splash screen appears.

**Expected Result:**
No HARMAN splash screen.

## Known Workarounds
none
*Use AIR 33.0.2.338 production version.

**Comment by ajwfrost** [comment]
How are you launching it? If using ADL, then yes on MacOS it wasn't set up properly yet; on Windows, it should be okay with ADL.exe but not with ADL64.exe...  But if building the bundles, then in all cases this should work.

For APKs it should also have been working, are you able to send us one of the problematic APKs and we can examine it?

thanks

**Comment by itlancer** [comment]
@ajwfrost 
Indeed with Windows without ADL.exe usage (with final bundle) it works fine.
But with MacOS splash screen appears in both cases (via ADL launch and with bundle).
I'm using Animate CC 18.0.2 with Windows and Adobe Animate CC 20.0 with macOS for packaging.
Also still have a problem with Android.
Sample of APK with such problem which build with AIR 33.1.0.43 beta sended to you. This APK was built via Animate CC 18.0.2 with Windows.
Thanks.

**Comment by ajwfrost** [comment]
@itlancer There was a problem in reading in the license files that we generated, not quite sure how we managed to miss that on the Android side of things! Should all be sorted now with 33.1..

thanks

**Comment by itlancer** [comment]
With latest AIR 33.1.1.50 now it works fine with cases:
- ADL launch with macOS
- bundle with macOS
- Android app
- bundle with Windows

But this issue still exists with ADL launching at Windows device via Animate CC 18.0.2.

**Comment by itlancer** [comment]
Completely fixed with AIR 33.1.1.63.
Thank you!
