### ISSUE TITLE
[AIR 33.1.0.43 beta][Windows] Cannot install application to iOS via ADT

### ISSUE THREAD

**Issue by itlancer** [Gamua/Adobe-Runtime-Support#232]
## Problem Description
Cannot install application to iOS device via ADT with AIR 33.1.0.43 beta from Windows device.

It has been tested with latest AIR 33.1.0.43 beta with Windows 8.1 64-bit device and iPhone 5s with iOS 12.3.
Animate CC 18.0.2 also doesn't "see" iOS devices with AIR 33.1.0.43 beta usage. Just display empty list of available devices.
Doesn't tested from macOS yet.
Doesn't tested with iOS 13 yet.

It works fine with AIR 33.0.2.338 and below.

Related issue: https://github.com/Gamua/Adobe-Runtime-Support/issues/112

## Steps to Reproduce
Execute via command line with Windows device:
`adt -devices -platform iOS`
from `AIR 33.1.0.43 beta/bin` directory.

**Actual Result:**
```
List of attached devices:
Handle  DeviceClass     DeviceUUID                                      DeviceName
Failure reading connected devices
```

**Expected Result:**
```
List of attached devices:
Handle  DeviceClass     DeviceUUID                                      DeviceName
   2    iPhone          xxxxxxxxxxxxxxxxxx(UUID)                        iPhone (UserName)
```

## Known Workarounds
none
*Use AIR 33.0.2.338 production version.

**Comment by ajwfrost** [comment]
@itlancer  So we have now updated both the Windows and the Mac versions of this and hopefully have captured all of the dependencies! as well as switching back to the USB ID for the 'handle' value.

thanks

**Comment by itlancer** [comment]
`adt -devices -platform iOS`
Command line execution with Windows device and latest AIR 33.1.1.50 now gets correct (expected) output with connected devices list.
Installation via command line
`adt -installApp -platform iOS -package test.ipa`
works fine.
But Animate CC 18.0.2 doesn't "see" iOS devices. Just display empty list of available devices. So installation doesn't work via that IDE.

**Comment by itlancer** [comment]
Issue still exists with AIR 33.1.1.63.

**Comment by itlancer** [comment]
Also with AIR 33.1.1.63 no errors in output (if it occurs: "Application verification failed" etc) with installation via command line via:
`adt -installApp -platform iOS -package test.ipa`
It works fine wih AIR 33.0.2.338

**Comment by itlancer** [comment]
It works fine wih AIR 33.1.1.190.
Thank you!
