### ISSUE TITLE
pls Matrix3D.rawdata not get the copy

### ISSUE THREAD

**Issue by matrix3d** [Gamua/Adobe-Runtime-Support#241]

**Comment by marchbold** [comment]
Please describe your issue in detail including the version of AIR you are using, the platform and how to replicate.

**Comment by matrix3d** [comment]
Matrix3D.rawData now returns a new array. If you directly manipulate this array, it will not change Matrix3D. Can return trueRawData for an api

**Comment by ajwfrost** [comment]
The data isn't stored internally in a Vector, it's held in an internal C++ structure. So there's no way that we can return an ActionScript representation of this for it to be directly manipulated.

The closest we could perhaps come to this is to add an API such as:
```
public function getRawValue(row : uint, col : uint) : Number;
public function setRawValue(row : uint, col : uint, newValue : Number) : void;
```
if you think that would be useful?

**Comment by matrix3d** [comment]
I use copyRawDataFrom instead，thanks
