### ISSUE TITLE
pls update flashplayer.swc and airglobal.swf in AIRSDK_Windows_33.1.1.50.zip

### ISSUE THREAD

**Issue by matrix3d** [Gamua/Adobe-Runtime-Support#243]

**Comment by ajwfrost** [comment]
Oh that's annoying - our packaging script had missed out airglobal.swc... Am attaching that file here.
There isn't a new "playerglobal.swc" though, this is just a build for AIR..

[airglobal_33.1.1.50.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/4265441/airglobal_33.1.1.50.zip)
