### ISSUE TITLE
[AIR 33.1.1.50] Feathers 4 LayoutGroup now crashes app.

### ISSUE THREAD

**Issue by Dimensionscape** [Gamua/Adobe-Runtime-Support#252]
Adding Feathers 4 LayoutGroup to stage crashes adl on all platforms with AIR 33.1.1.50 and no exception thrown.
Upon trying to debug in the LayoutGroup class, tracing a value out before and after super() is called seems to bizarrely fix it.

**Comment by Dimensionscape** [comment]
Using a delayed call to draw the display object worked. Something is wrong with the native splash code causing the issue when you draw right away.

**Comment by ajwfrost** [comment]
Hi - are you able to attach a test SWF? This issue may he fixed in our forthcoming update as there were a few problems like this in the 31.1.1.50 release, but it would be good if we can confirm it..

Thanks

**Comment by Dimensionscape** [comment]
[LayoutGroupTest.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/4293902/LayoutGroupTest.zip)
It doesn't happen all of the time. Here's the test project files.
