### ISSUE TITLE
Air 33.1.1.50 missing file objects-13.0+.nib

### ISSUE THREAD

**Issue by ChacHauLam** [Gamua/Adobe-Runtime-Support#253]
I overlaid Air 33.1.1.50 with Flex as normal, but I now get an error when I build an out to iOS from Flash Develop:

“SDK is missing file objects-13.0+.nib”

**Comment by leossmith** [comment]
Did you make sure that MainWindow.nib and MainWindow-iPad.nib folders were copied correctly at \lib\aot\lib ? I had issues overlaying the latest sdk over Flex and had to delete 2 files and then manually copy these.

**Comment by ajwfrost** [comment]
Similar to the issue in #234 

Files are in the SDK folder: `\lib\aot\lib` (and `\lib\aot\lib-tvos`)
Previously MainWindow.nib and MainWindow-iPad.nib were files.
Now they are folders, with file contents or MainWindow[-iPad].nib and objects-13.0+.nib.

**Comment by ChacHauLam** [comment]
Ah brilliant! Thanks both that worked!
