### ISSUE TITLE
[Android IOS] AIR SDK 33.1.1.63 when use ANE  crashing on startup

### ISSUE THREAD

**Issue by KaseYu** [Gamua/Adobe-Runtime-Support#259]
## Problem Description
I have the same problem here. The same problem occurs with the packaging of my app using SDK 33.1.1.63. On Android, ANE will become NULL, and on iOS, it will crash. 

## Known Workarounds
Returning to 32.0.2.338 will be normal

Thanks.

**Comment by neuronix** [comment]
Hi KaseYu, I don't know what you expect Harman to do with this report. There is nothing to work with in your report... many other devs have had no issue building with .63 so this is most probably an isolated issue, but without any error message, logs or information, no way to judge so please either detail your report or close the issue.

**Comment by ajwfrost** [comment]
Actually just to add here - we had this report from someone else too, we believe there is an issue which is caused by a combination of ANE usage plus splash screen display. KaseYu raise this report from the original issue where it was mentioned, but that issue had a different cause hence I asked that this separate one be created.

Neuronix I do appreciate that message though, we do have some reports where we really don't have anything to really work with to reproduce it! In general it's particularly helpful if folk can provide a package that demonstrates the problem (if you package using apk-debug for Android, we can inject a debug version into it to get a lot more information out of it..). So, thanks for your attempts to clean up this long list of issues we have to work through! :-)

cheers

**Comment by KaseYu** [comment]
@ajwfrost  The above description reminded me that when using 33.1, an error message appears, I have not yet added adt.lic, I just reconfirmed it again, and it can start normally after joining.
However, the apk file that does not include adt.lic is also attached below. If necessary, you can tell me how to cooperate. 
Thanks.

[33.0.2.338 is work](https://drive.google.com/open?id=1IzBPG4TpE7uXNcU6Kj6QCptPV0A7jonl)
[33.1.1.63 is error](https://drive.google.com/open?id=19kRAjLODFv5AaSJo6ayvQUGusbc1FX-D)

**Comment by TobiasHeidingsfeld** [comment]
I also report this problem

**Comment by TobiasHeidingsfeld** [comment]
I could "fix" the Problem by removing the Facebook SDK from compiling into the app. Hope that helps.

**Comment by DLGames** [comment]
My flash labs ANE are crashing randomly. You should talk with them. Returning to old AIR fixes the problem...

**Comment by ajwfrost** [comment]
The crash with ANEs are due to the splash screen problems so we’re working to fix this shortly..

We can’t just adapt trademarks how we want them unfortunately, there are restrictions on how much we can do here! But thanks for the suggestions and feedback.

cheers

**Comment by PauloZung** [comment]
I believe I'm having the same problem here.

Distriqt's ANEs just worked fine on SDK 32. Now on 33.1.1.63, every time I point to a Class from the ANE I get one of the following errors:

`VerifyError: Error #1014: Class com.distriqt.extension.pushnotifications.events::AuthorisationEvent could not be found.`

`ReferenceError: Error #1065: Variable com.distriqt.extension.core::Core is not defined.`

Any workarounds? 
Thank you.

**Comment by marchbold** [comment]
We are getting lots of reports of this, if there's anything we can do to help identify the issue, please let me know.

**Comment by DLGames** [comment]
@ajwfrost Don't worry unity logos were ugly at fist also! If you want AIR&Harman to be taken seriously you need to find a way to improve that. Don't forget that unity wouldn't have been where it is now without the FREE tier users that spread the word!

**Comment by PauloZung** [comment]
I am about to miss the release date of my app because of this problem. Does anyone can provide me a link to the SDK version 33.0.2.338 to solve this problem temporarily?

**Comment by marchbold** [comment]
Agreed! This one is critical. It's blocking builds at the moment.

**Comment by ajwfrost** [comment]
@PauloZung we're trying to get our updated release out asap but facing some delays I'm afraid. To get at 33.0.2.338, you may need to bypass some browser security as this purports to be from airsdk.harman.com, but if you use the below link you should be able to download it..

https://e30c36a4c1f0b3847b9d628a8aba7dd2-1278174957.us-east-2.elb.amazonaws.com/download

**Comment by orcuncun** [comment]
link is faulty, Can I get it too? to this version. AIR 33.1.0.37 or AIR 33.0.2.338.
Thanks.

**Comment by PauloZung** [comment]
> link is faulty, Can I get it too? to this version. AIR 33.1.0.37 or AIR 33.0.2.338.
> Thanks.

You must choose to ignore the SSL certificate.

**Comment by orcuncun** [comment]
This site can’t be reachede30c36a4c1f0b3847b9d628a8aba7dd2-1278174957.us-east-2.elb.amazonaws.com’s server IP address could not be found.

**Comment by ajwfrost** [comment]
Try insecure approach?

http://e30c36a4c1f0b3847b9d628a8aba7dd2-1278174957.us-east-2.elb.amazonaws.com/download

**Comment by orcuncun** [comment]
I tried all the ways but could not download. Is there another solution?

**Comment by jimmymjing** [comment]
I'm having similar issue. The ADL crashes immediately at startup on iOS devices. The problematic ANE is Advert from Distriqt. (other ANEs are fine from Distriqt though)
Environment: Windows, AIR_SDK_33.1.0.16, iOS SDK 12.4

**Comment by marchbold** [comment]
@jimmymjing I've responded on our forum, but my guess is this is a missing configuration option.

**Comment by ajwfrost** [comment]
@KaseYu we've just release 33.1.1.86, are you able to check and confirm that the ANE crash is fixed now?

**Comment by orcuncun** [comment]
yes, crash is fixed now , thanks.

**Comment by KaseYu** [comment]
@ajwfrost 33.1.1.86 is ok,  thanks.
