### ISSUE TITLE
RemoteNotificationEvent returns token in wrong format on iOS 13

### ISSUE THREAD

**Issue by gaurangtalwadkar** [Gamua/Adobe-Runtime-Support#263]
## Problem Description

**Environment:**
AIR SDK: 33.1.1.50
OS: iOS 13

**Description:**
In iOS 13, Apple has changed the implementation of its description method for NSData class. This is breaking the Push notification feature in AIR with RemoteNotifier class.
Token returned on iOS 13 from RemoteNotificationEvent.TOKEN event is something like this 
`{LENGTH=32,BYTES=0X9FBEB00A2818ED56DB133E825710BC6C...257A99F80E490DD9}`

Please update the push token retrieval implementation to handle this changes.

**Links:**
[https://nshipster.com/apns-device-tokens/](https://nshipster.com/apns-device-tokens/)
[https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications](https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/
)

## Known Workarounds
Reverting back to AIR SDK 32.0.0.116 works fine.

**Comment by gaurangtalwadkar** [comment]
@ajwfrost Is there any update on this?

**Comment by ajwfrost** [comment]
@gaurangtalwadkar yes the token format was updated in 33.1.1.86 now available - are you able to confirm this fix please?

**Comment by gaurangtalwadkar** [comment]
Working fine with AIR SDK 33.1.1.98.

**Comment by ajwfrost** [comment]
Thanks for confirming, closing this as fixed now.
cheers
