### ISSUE TITLE
[FEATURE REQUEST] On some Android phones, the full-screen display cannot be full, such as google pixel 4 xl

### ISSUE THREAD

**Issue by KaseYu** [Gamua/Adobe-Runtime-Support#266]
## Problem Description
Hi,
Using the latest SDK 33.1.1.63, the left and right of the full screen display will be cut off on certain Android devices (the following pictures are attached). I hope that future versions can fix this part of the problem. 
Thanks.

[screenshot](https://drive.google.com/file/d/1PidcnaE_yZrRLl3-mD_NkhFBwQFLb-9d/view?usp=sharing)

**Comment by ajwfrost** [comment]
Have you got the wide aspect ratio setting in the application descriptor file?
```
<android>
<manifestAdditions><![CDATA[
<manifest android:installLocation="auto">
<!-- other tags here -->
<application>
<meta-data android:name="android.max_aspect" android:value="2.4"/>
</application>
</manifest>
]]></manifestAdditions>
</android>
```

**Comment by KaseYu** [comment]
@ajwfrost Thank you, I did not make a wide aspect ratio setting, and just added it to display correctly.
