### ISSUE TITLE
Debugging with IntelliJ and iOS not possible with 33.1.1.86

### ISSUE THREAD

**Issue by stoff99** [Gamua/Adobe-Runtime-Support#283]
## Problem Description
The building of the application and ipa is working but when you start debugging in IntelliJ (latest version 2019.3) you will get following error message. Check screenshot:
![Install_iOS_Application_und_ETeamApp___Development_WorkSpaceIntelliJ_AS3_AIRMobile_PlentyCards_Release_Mobile_V_2_13_0_ETeamApp__-__Development_WorkSpaceIntelliJ_AS3_AIRMobile_PlentyCards_Release_Mobile_V_2_13_0_Library_src_com_sf_util_Andr](https://user-images.githubusercontent.com/892820/77888473-a1836a00-726c-11ea-9599-f68d7e0686d2.png)

BUT the application is installed and visible on the device. So there is some crash after installing and starting the debugger session.

* Which AIR SDK did you use? 
- Air 33.1.1.86
- IntelliJ 2019.3

* Describe the affected environment: Flash vs. AIR, Android vs. iOS, all devices vs. just specific models.
- iPhone 7 iOS 13.1.3
- iPad (5. Generation) iOS 12.4.1

## Steps to Reproduce
Just start debugging with IntelliJ IDEA on an iOS device.

Does somebody else have this issue?

Thx 
Stefan

**Comment by ajwfrost** [comment]
Yes see https://github.com/Gamua/Adobe-Runtime-Support/issues/112#issuecomment-605447195

There's a potential fix with an ADT.jar file that can be downloaded to your "lib" folder, if this link is now working:
https://transfer.harman.com/messages/qdjLTmOfudEd2mmKMFE6zB/attachments/cmPs4hJqRDjQ8VU1QhQkXT/download/adt.jar

**Comment by marchbold** [comment]
Closing, as duplicate.

**Comment by stoff99** [comment]
Hi @ajwfrost,

thx for that, i was searching for a similar issue but don't found the #112 .
Its working with the file in your link.
