### ISSUE TITLE
what's happening to Air 33.1.1.86?

### ISSUE THREAD

**Issue by marcanw** [Gamua/Adobe-Runtime-Support#288]
I saw this morning that the last AIR sdk 33.1.1.86 was removed from the release page and replaced by the previous 33.1.63.
I didn't see any explanation about it.
Could you tell me more about this?
I have a release in production that was build with AIR sdk 33.1.1.86, What do I have to do?
Thx

**Comment by ajwfrost** [comment]
Hi - that was a sync issue, one of the guys pushed some changes to the website documentation but had overwritten the previous HTML - the zip files were apparently still .86.

I believed it’s back to the right version now..

Thanks

**Comment by marcanw** [comment]
Pfiouh! ;-)
