### ISSUE TITLE
TouchEvent and MouseMovements Lost

### ISSUE THREAD

**Issue by ErdincBARUT** [Gamua/Adobe-Runtime-Support#289]
FlashBuilder + Starling Framework with  AIRSDK version 33.1.1.86  

Tested on: Android device & Simulator 

I migrated to Airsdk 33.1.1.86  

now TOUCH is gone! Previous version touch is working that version of airsdk lost touch.

stage.addEventListener(TouchEvent.TOUCH,onTouch); not working anymore.

stage.addEventListener(MouseEvent.MOUSE_MOVE,onMouseMove) not working anymore.

**Comment by ajwfrost** [comment]
Hi - this is working for us, with a basic test app. Are you able to share a test case to demonstrate this? and ideally a build with apk-debug?


thanks

**Comment by ErdincBARUT** [comment]
Finally ,I found problem is not  AirSdk problem. I am sorry for this issue.
 I updated AirSdk + Starling 2.4 to 2.6.
Starling Update is blocking TouchEvents.

[added 'Starling.nativeOverlayBlocksTouches' property, which makes native overlay behave more intuitively (#861)]


**Starling.current.nativeOverlayBlocksTouches =false;** 
That code is solve my problem.

You can delete that case.
Thank you.
