### ISSUE TITLE
[iOS] executeInBackground stopped working

### ISSUE THREAD

**Issue by marcanw** [Gamua/Adobe-Runtime-Support#293]
Hello
I noticed that executeInBackground stops working on iOS.
I noticed it lately. I can't say if it's related to the last Air Sdk, the last iOS 13 upgrade or if I missed something.
I mainly use it to notify our server that the user is deactivating the app but now it sends it when the user is getting back to the app...
Normally iOS was giving five seconds to make critical tasks but it doesn't and even using executeInBackground doesn't make it.

Am I the only one who has this problem?
Is it a bug or did I miss something?

Thank you for your help

**Comment by ajwfrost** [comment]
Hi

We had been testing background execution specifically in the last release as we've added some code in there to allow background execution also for folk using the proximity sensor. 

Are you able to create a simple test app that demonstrates the problem and if it's still blocking/terminating when going to the background, we can check this further..

thanks

**Comment by marcanw** [comment]
I made a test project an actually the problem seems to come from the fact that I'm using ApplicationStateEvent.BACKGROUND from Distriqt Application ane rather than Event.ACTIVATE.
So I guess executeInBackground is only effective when it's called from the Event.ACTIVATE handler.
@marchbold Are you aware of this? Do you think you will have a fix soon or do I have to switch to Event.ACTIVATE?

**Comment by ajwfrost** [comment]
A call to set executeInBackground should be valid at any point - as long as you make this change before it actually goes to the background!

Just to double-check of course, you don't have 'UIApplicationExitsOnSuspend' in your descriptor..?

**Comment by marcanw** [comment]
Well I use both Event.ACTIVATE and ApplicationStateEvent.BACKGROUND now and clearly setting executeInBackground to true from ApplicationStateEvent.BACKGROUND doesn't have any effect while from Event.ACTIVATE it works.

**Comment by marcanw** [comment]
I close the issue because it's not related to the air sdk.
I use Event.ACTIVATE for managing executeInBackground now and it works fine.
Thank you ajwfrost for your help.

**Comment by ajwfrost** [comment]
Okay thanks - for completeness, looking at the description of ApplicationStateEvent.BACKGROUND, I think this will be dispatched whilst we are going into the background - at which point it will just be too late to take any notice of the executeInBackground flag, we would have needed that to be set up earlier...

**Comment by marchbold** [comment]
Yes, the `ApplicationStateEvent.BACKGROUND` event really is a last call, dispatched on the applicationwillresignactive delegate call. Too late to change any flags, you should use the `ApplicationStateEvent.DEACTIVATE` event (or the standard `Event.DEACTIVATE`) for that (I assume you meant DEACTIVATE and not ACTIVATE? )

**Comment by marcanw** [comment]
Yes sorry DEACTIVATE,
Actually I had to play with the four events but it works now.
