### ISSUE TITLE
Crash at Android AppEntry [DeadObjectException]

### ISSUE THREAD

**Issue by mumeka** [Gamua/Adobe-Runtime-Support#299]
Hello,

My app started to crash yesterday. Maybe it was happening before, I did not noticed. It always runs at first run after deploying to device. It can start crashing after closing it and reopening.

App uses Starling, Feathers, lots of Distriqt ANES. However it is crashing at start, so I don't know if it related.

After noticing crash I tried with AIR SDKs, It crashes at all, sometimes I need to reopen it 5-6 times:
AIR 32.0.0.116
AIR 33.0.2.338 (licensed)
AIR 33.1.1.98 (licensed)

It does not crash at Samsung S7, but crashes at Samsung A10.

I can provide the development APK which is 46MB currently.

It crashes before Scout gather any data (not even frame 1 information), so only adb log exist without much information:

I added long adb log, however short version ending:

```
onRemoved AppWindowToken{913cdc3 token=Token{b14d572 ActivityRecord{701827d u0 com.gamess.okey/.AppEntry t714}}}#0 

    id=2304 onRemoved Letterbox - left#0 

04-20 00:39:21.177 4049-4079/? D/WindowManager: reportFocusChangedSerialized, focused=false, inTouchMode=true, win=Window{45f3682 u0 com.gamess.okey/com.gamess.okey.AppEntry}

04-20 00:39:21.233 4049-4079/? E/WindowManager: RemoteException occurs on reporting focusChanged, w=Window{45f3682 u0 com.gamess.okey/com.gamess.okey.AppEntry}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1145)
        at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)
        at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3950)
        at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5485)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
```

[adbLog.txt](https://github.com/Gamua/Adobe-Runtime-Support/files/4500442/adbLog.txt)

[adbLog2.txt](https://github.com/Gamua/Adobe-Runtime-Support/files/4500595/adbLog2.txt)
In this log InputMethodManagerService also gives DeadObjectException before crash.

If you can tell me how to gather more information, I can provide them.

Edit: I deleted license from SDK, it looks like it crashes after Harman Splash Screen.

- When no crash: game opens after displaying 8 second harman splash.

- When crash:  8 seconds harman splash -> 2 seconds black screen -> return to android home.

Maybe this is a memory error. Game uses 19 texture atlases with 313MB GPU memory, at initialization it also uses 640MB+ to RAM according to SCOUT. I'm open to all suggestions.

**Comment by neuronix** [comment]
Hi @mumeka, did you updated any ANEs? 

This issue sounds too early in the launch to be related to textures but 313Mo GPU memory is far too much, you'll definitely encounter issues on lower end Android devices. I'd recommend you encode your textures into ETC1 only ATFs. It's the best of both worlds: atf files remain not too large, they will load faster and you'll reduce GPU memory to about 50Mo. ETC1 is available on all platforms. You can find details in the Starling manual.

**Comment by mumeka** [comment]
Hello @neuronix  I tried ATF approach, used all atlases with ATF JXR and RAM usage gone below 50 MB, AIR does not create bitmap data this way thanks.

GPU memory is still at 300mb because all atlases are 2048x2048, however game opening time doubled. I made a chart like this for android:

![paradox](https://user-images.githubusercontent.com/3039771/79802117-175c8c00-8368-11ea-919d-abfc6dca2d70.png)

I want it to be fast, however low in size, if I read right information, I need ETC2 and ETC1 together so file size will go bigger, much bigger than png approach, compression also increase GPU upload speed. How do you solve this?

ETC2 opens with 35 millisecond while ETC1 costs 231 millisecond when uncompressed with JXR.

**Comment by neuronix** [comment]
Ok, You are mixing things up, don't worry took me a while to understand it properly too :)

You have 3 groups of texture formats:

**Bitmap**: PNG, JPG : they are optimized for disk usage, not for GPUs. They have to be converted for use by the GPU.
Pro: Small disk usage (for jpg)
Con: Load slowly to GPU
Con: Not a GPU compressed texture, high GPU memory usage

**Hybrid**: ATF(JPEGXR). It's just a JPEG file wrapped in a ATF container.  
Pro: Small disk usage
Pro: Loads quickly to GPU
Con: Not a GPU compressed texture, high GPU memory usage

You create JPEGXR Atfs with: 
`png2atf -i image.png -o image.atf`

**Compressed**: ATF ( ETC1 / ETC2 / DXT / PVRTC). These are very high optimized files that can be directly loaded into the GPU memory, resulting in very fast loading times and very low GPU memory usage.
Pro: Load quickly to GPU
Pro: Real GPU Compressed texture, very low GPU memory usage (8x less)
Con: Big disk usage (2x-4x a PNG). However, once your app is built into an apk/ipa/exe, these files will be zipped and they will be as small as jgs ! So this is not even a real con :)

You create compressed Atfs with:
`png2atf -c -i image.png -o image.atf`

However, just "-c" includes ETC1+DXT+PVRTC. Historically this was to support all devices, but it's no longer needed, iOS, Android 4.3+ and Windows all support ETC1.

You create ETC1 only Atfs with:
`png2atf -c e -i image.png -o image.atf`

You can make your Atfs smaller by omitting mipmaps with "-n 0,0":
`png2atf -c e -n 0,0 -i image.png -o image.atf`

We have a game that used about 280Mo GPU memory with JPEGXR atfs, I converted all our textures to ETC1 atfs and now we use about 50Mo GPU memory, the app loads faster and the total apk/ipa size hasn't changed by much.

**Comment by mumeka** [comment]
Hello @neuronix this is the most detailed explanation I have read about the subject. Thank you.

At AIR 30+ if device is supporting ETC2, ETC1 using software support so it is slow at GPU upload.

**ETC2** = 35 ms
**ETC1** = 226 ms

If they are using JXR compression, this devices also spent ~200ms to decompress each texture file. 
**ETC2 with JXR** = 257 ms
**ETC1 with JXR** = 439 ms

Also it seems like Hybrid: **ATF(JPEGXR)** is the worst with 493 ms.

So I think I will combine ETC2 and ETC1 together to reach blazing fast speed at all devices.

And it is correct APK size is still very small even tough ATF files are large.

**Comment by neuronix** [comment]
Happy to be able to help @mumeka ! One remark though, I experienced issues with ETC2 on some iOS devices (some textures without any opacity would appear black and with incorrect sizes, although appearing properly in the ATFViewer). So we stuck to ETC1 only. Good luck with your app :)

**Comment by mumeka** [comment]
Thank you for the information @neuronix, see you :)
