### ISSUE TITLE
Immediately crashing on startup

### ISSUE THREAD

**Issue by flatgames2** [Gamua/Adobe-Runtime-Support#301]
iOS app is immediately crashing on startup when packaged with AIR AIR 33.1.1.98 (latest)
Some details about the app:
AIR 33.1.1.98
Windows 10
GPU RenderMode
Tested on iPhone X running iOS 13.4.1
Using Harman free license (splash)

We have removed all the ANE files and tried to run app on iPhoneX but still did not work. There is not any errors on output. The game works on computer without any errors. What could be the reason for it? Why the app crashes on startup? 

Thanks

**Comment by Michoko92** [comment]
AIR 33.0.0.168 is definitely not the latest version. Latest version for now is AIR 33.1.1.98. You may want to try updating first.

**Comment by flatgames2** [comment]
> AIR 33.0.0.168 is definitely not the latest version. Latest version for now is AIR 33.1.1.98. You may want to try updating first.

Hi, sorry i wrote it by mistake. We are using AIR 33.1.1.98(latest). We are getting the bug with the latest version. Any solutions? Thanks

**Comment by ajwfrost** [comment]
Hi - can you find any details on the crash from the analytics log on the phone?
Settings -> Privacy -> Analytics & Improvements -> Analytics Data -> package name


thanks

**Comment by flatgames2** [comment]
Here is the crash: 

[Bug.txt](https://github.com/Gamua/Adobe-Runtime-Support/files/4516951/Bug.txt)

**Comment by j3k0** [comment]
Might be related. Some ANEs crash with `33.1.1.98` because they use a private APIs that has seemingly changed with build `98`:

https://stackoverflow.com/questions/8766698/how-do-i-get-onactivityresult-to-run-in-an-adobe-air-native-extension

It's questionable whether they should or shouldn't... Maybe there's no better way to monitor the state of the app? I don't know.

That's the logcat:

```yaml
04-25 08:06:45.693 21423 21423 W System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/adobe/air/StateChangeCallback;
04-25 08:06:45.693 21423 21423 W System.err:    at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
04-25 08:06:45.693 21423 21423 W System.err:    at com.adobe.air.customHandler.handleMessage(customHandler.java:22)
04-25 08:06:45.693 21423 21423 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:105)
04-25 08:06:45.693 21423 21423 W System.err:    at android.os.Looper.loop(Looper.java:164)
04-25 08:06:45.693 21423 21423 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6944)
04-25 08:06:45.693 21423 21423 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
04-25 08:06:45.693 21423 21423 W System.err:    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
04-25 08:06:45.693 21423 21423 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
04-25 08:06:45.693 21423 21423 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.adobe.air.StateChangeCallback" on path: DexPathList[[zip file "/data/app/air.nl.goliathgames.triominos-6HthfSkCU0GI3iNz3mbOww=$
/base.apk"],nativeLibraryDirectories=[/data/app/air.nl.goliathgames.triominos-6HthfSkCU0GI3iNz3mbOww==/lib/arm64, /data/app/air.nl.goliathgames.triominos-6HthfSkCU0GI3iNz3mbOww==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64$
]
04-25 08:06:45.693 21423 21423 W System.err:    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
04-25 08:06:45.693 21423 21423 W System.err:    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
04-25 08:06:45.693 21423 21423 W System.err:    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-25 08:06:45.693 21423 21423 W System.err:    ... 8 more
```

**Comment by flatgames2** [comment]
The crash is resolved when we delete the below keys from app.xml. 

<key>UILaunchStoryboardName</key>
  <string>LaunchScreen</string>
