### ISSUE TITLE
Change in build 98 makes ANEs crash at startup

### ISSUE THREAD

**Issue by j3k0** [Gamua/Adobe-Runtime-Support#303]
Some ANEs crash with `33.1.1.98`.

I believe it's because they use a private APIs that has seemingly changed with build `98`:

https://stackoverflow.com/questions/8766698/how-do-i-get-onactivityresult-to-run-in-an-adobe-air-native-extension

It's questionable whether they should or shouldn't... Maybe there's no better way to monitor the state of the app? Maybe there is? I don't know.

Logcat at the bottom

#### discussion

Should this kind of API be made public? Is it worth the effort to compatibility with those ANEs?

Personally, since everything is closed source (the ANEs and runtimeClasses.jar), I cannot fix stuff and upgrade to the latest AIR SDK.

---

```yaml
04-25 08:06:45.693 21423 21423 W System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/adobe/air/StateChangeCallback;
04-25 08:06:45.693 21423 21423 W System.err:    at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
04-25 08:06:45.693 21423 21423 W System.err:    at com.adobe.air.customHandler.handleMessage(customHandler.java:22)
04-25 08:06:45.693 21423 21423 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:105)
04-25 08:06:45.693 21423 21423 W System.err:    at android.os.Looper.loop(Looper.java:164)
04-25 08:06:45.693 21423 21423 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6944)
04-25 08:06:45.693 21423 21423 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
04-25 08:06:45.693 21423 21423 W System.err:    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
04-25 08:06:45.693 21423 21423 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
04-25 08:06:45.693 21423 21423 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.adobe.air.StateChangeCallback" on path: DexPathList[[zip file "/data/app/air.nl.goliathgames.triominos-6HthfSkCU0GI3iNz3mbOww=$
/base.apk"],nativeLibraryDirectories=[/data/app/air.nl.goliathgames.triominos-6HthfSkCU0GI3iNz3mbOww==/lib/arm64, /data/app/air.nl.goliathgames.triominos-6HthfSkCU0GI3iNz3mbOww==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64$
]
04-25 08:06:45.693 21423 21423 W System.err:    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
04-25 08:06:45.693 21423 21423 W System.err:    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
04-25 08:06:45.693 21423 21423 W System.err:    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-25 08:06:45.693 21423 21423 W System.err:    ... 8 more
```

**Comment by marchbold** [comment]
This was the process we were advised to use by Adobe even though it is a private API.

@ajwfrost Can you please let us know what has changed and how this will affect us!? Many of our ANEs need to monitor the state of the activity to correctly handle feedback.

**Comment by marchbold** [comment]
I don't see any changes in the AIR SDK here, the only way I can replicate this error is by using the wrong Core ANE (i,e, the noair version which has these private API exposing classes removed to avoid conflicts with other ANE developers).

**Comment by ajwfrost** [comment]
Hi

I'm wondering if this is a timing problem again - we haven't change any APIs here but the splash screen implementation may well have modified how the start-up timing works..

Alternatively if this is to do with multi-dex support, it might be because the new D8 tool pushes most things into a secondary classes dex file ..

@j3k0  are you able to open your APK file within Android Studio's APK Analyser (from Build menu) and see whether this has got multiple "dex" files? If you select "classes.dex" and look in the panel showing the class list, can you find com.adobe.air.StateChangeCallback in that? Or in one of the other classesN.dex files?

thanks

**Comment by marchbold** [comment]
@ajwfrost it was an implementation error, they were using the wrong Core ane. We have a version without the air integrations to avoid conflicts with other air developers and they were using that version, which resulted in the missing classes.

So no issue here.
