### ISSUE TITLE
Harman Adobe air 33.1.1.98  cannot update or install app on WIndows

### ISSUE THREAD

**Issue by Menard1965** [Gamua/Adobe-Runtime-Support#306]
I use SDK 33.1.98 from Harman. When i complie Air for Desktop. I cannnot install the Aopplication or Update it. Threre is the following error message from Adobe Air runtime:

You need a more recent Adobe Air runtime. Please install.

But  there  is no  Adobe Air runtime ?? to download. I have thousands of people outthere using my Apps. What is the solution.

Please help

PS: in Harman 33.0.2.281  it worked  since 33.1.1.98 it doesnt work

**Comment by ajwfrost** [comment]
Hi

Please package the application together with the runtime:

https://help.adobe.com/en_US/air/build/WSfffb011ac560372f709e16db131e43659b9-8000.html

Thanks

   Andrew
