### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted

### ISSUE THREAD

**Issue by dmitrydmsk** [Gamua/Adobe-Runtime-Support#319]
Submit new app to Apple, built with AIRSDK 33.1.1.98 with few ANE all from Distriqt and recieve email with:
'ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted'

Sorry, but i did not find answear here, on 'google' and different forums. I found in unpacked ipa file text 'UIWebView', but cant find out how its got there. References to UIWebView not found in ANEs, but they present in air sdk and facebook sdk

Is this still a problem for new apps even with AIRSDK 33.1.1.98 ?

Thanks in advance

**Comment by qq5000521** [comment]
I used the same version as you and didn't have any problems with you.
The upload was successful, but apple did not approve it

**Comment by markkelynack** [comment]
I have the same issue, what ANE's are you using?

**Comment by kxk-kry** [comment]
the issue is not because of the AIRSDK. It is because of ANEs. I use myflashlabs ANE(FirebaseCore and FirebaseMessaging). @qq5000521 is right. The upload was successful without these ANEs. I am waiting for myflashlabs.

**Comment by marchbold** [comment]
We have discovered some unexpected references in a few of our ANEs. Please let us know what ANEs you are using, we are going through them all now.

**Comment by markkelynack** [comment]
Using the following for this project:

Scanner
Location
Notifications
Vibration
Permissions
Network
Application

With, Core and androidX

**Comment by marchbold** [comment]
Scanner was updated last night, that should be the only one in your list that has UIWebView usage.

**Comment by BotikiGames** [comment]
Hi, I am using ANE ADMOB from myflashlabs and will get the same error. Are there any other ANE ADMOBs where the error has already been fixed?

**Comment by dmitrydmsk** [comment]
Thanks all for comments. The problem was indeed in ANE not AIRSDK 33.1.1.98 With the latest version of ANEs from Distriqt this problem is solved, app accepted by Apple.

**Comment by dgurney75** [comment]
Still waiting on MyFlashLabs to address UIWebView issue in Firebase ANE's.

**Comment by myflashlab** [comment]
@dgurney75 Actually about two months ago, on [May 19, 2020](https://github.com/myflashlab/Firebase-ANE/blob/master/ChangeLog.md) we upgraded to Firebase iOS 6.18.0 which the use of UIWebview has been removed. 

We also made a similar update to our Admob ANE to make sure the UIWebview problem won't be around our ANEs ^_^

**Comment by dgurney75** [comment]
After submitting multiple builds to the app store, I can confirm that firebase.dynamicLinks-V9.12.0.ane is causing the UIWebView issue. Can you please check this ANE for any references and update asap. I can’t use Firebase Auth without this ane.

Thanks.

**Comment by dgurney75** [comment]
I actually meant to say firebase.fcm-V9.12.0.ane is the one that’s causing the issue.

From: Dan Gurney <dgurney75@gmail.com>
Date: Thursday, July 16, 2020 at 2:01 PM
To: Gamua/Adobe-Runtime-Support <reply@reply.github.com>, Gamua/Adobe-Runtime-Support <Adobe-Runtime-Support@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [Gamua/Adobe-Runtime-Support] ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted (#319)

After submitting multiple builds to the app store, I can confirm that firebase.dynamicLinks-V9.12.0.ane is causing the UIWebView issue. Can you please check this ANE for any references and update asap. I can’t use Firebase Auth without this ane.

Thanks.

**Comment by myflashlab** [comment]
@dgurney75 you are right, that is happening due to a confusion in the `OneSignal` ANE. we'll fix that a.s.a.p and update you. thanks.

**Comment by myflashlab** [comment]
While we are still working on a newer version of both Firebase and OneSignal, here's a quick rollback-hot-fix to fix this on internal OneSignal libraries to avoid using UIWebview... Please grab V9.12.1 from ANELAB and it should be fine. ^_^
