### ISSUE TITLE
iPad splitview/multitasking support

### ISSUE THREAD

**Issue by myflashlab** [Gamua/Adobe-Runtime-Support#321]
## Problem Description

To support splitview/multitasking on iPad devices, besides using launchScreen storyboards, we might need to add the following key under the `<InfoAdditions>` tag:

```xml
<key>UIRequiresFullScreen</key>
<string>NO</string>
```

I remember a few years back Adobe had hardcoded this value to `YES` so AIR apps would opt-out of multitasking by default.

I'm not sure if this policy has ever changed or not but I tried to set the key hoping that it would overwrite the hardcoded value but no luck. And when I open up the .ipa file and read the .plist file, I still see it's value is set to `true`.

Is there a workaround for this so AIR can support splitview properly? it would be a nice fix for AIR I guess ^_^

**Comment by ajwfrost** [comment]
@myflashlab  this is a bit "use at your own risk" but can you try the following and perhaps see what happens - I'm afraid I don't know whether this is actually supported in the code or not, but you can change that UIRequiresFullScreen setting if you add an element in the application descriptor file:
```
<application>
  <iPhone>
    <multitasking>true</multitasking>
  </iPhone>
</application>
```
Whether AIR then works in split-screen view or not, we've not checked.. there might need to be a lot of changes for this sort of thing in both iOS and Android, I suspect the whole thing was coded with the expectation that we just take over the whole screen...

**Comment by myflashlab** [comment]
@ajwfrost Thanks for the suggestion. I tried adding that but the compiler keeps on throwing this error `Error:Launch screen storyboard file missing from package` although I am using the launchScreen story board.

**Comment by FliplineStudios** [comment]
@myflashlab When Adobe added multitasking support in AIR, they mentioned having to add a couple different tags to the application descriptor at the same time to get it to work:

<iPhone>

    <multitasking>true</multitasking>
    <launchScreen>LaunchScreen.storyboardc</launchScreen>
    <assetsCar>Assets.car</assetsCar>

</iPhone>

Did you try adding that launchScreen tag there, as well as the newer UILaunchStoryboardName key?


The release notes for AIR 22 seem to be the last time they mentioned it (as a Beta feature), so not sure if they made any changes since then, or how well it worked:
https://helpx.adobe.com/flash-player/release-note/fp_22_air_22_release_notes.html

**Comment by myflashlab** [comment]
Nice one @FliplineStudios that was exactly what was missing...
The app is now beautifully resizing on different splitviews :)

@ajwfrost I think a centralized documentation would be very much helpful as remembering old stuff from years back is not very easy. ^_^

**Comment by ajwfrost** [comment]
Thanks @FliplineStudios for that - I hadn't seen it in there! @myflashlab yes definitely - my slight concern here is that those options don't appear in the AIR Descriptor online specification from Adobe, so I wasn't sure if it was completely undocumented (and therefore just something that's not properly supported)...

**Comment by GeneralVimes** [comment]
Thank you so much! This solution worked for me: https://www.reddit.com/r/iosgaming/comments/1gn9p70/my_idle_games_idle_tower_builder_and_farm_and/
