### ISSUE TITLE
App is getting crashed while playing videos in iOS 13 devices

### ISSUE THREAD

**Issue by ukmunnithan** [Gamua/Adobe-Runtime-Support#324]
## Problem Description
When I try to play video in my app on iOS 13 devices the app is getting crashed.
The issue is happens for AIR SDK 33.1.1.98. For the AIR SDK version 32 it is working fine.
Also the video is playing well for iOS version less than 13.
I am using MPMoviePlayerController as ANE to play the video.
Could you please help me to resolve the issue?

**Comment by ajwfrost** [comment]
I believe MPMoviePlayerController was deprecated some time ago and has now been removed from iOS 13?

**Comment by ukmunnithan** [comment]
But it is working with AIR SDK 32 for iOS 13 devices

**Comment by marchbold** [comment]
AIR 32 would still be targeting the older SDK, which would allow usage of it. Now that you have to target iOS 13 you need to migrate to AVKit's AVPlayerViewController

**Comment by ukmunnithan** [comment]
@ajwfrost @marchbold 
Thank you for the update and Information. I tried with AVPlayer and its working fine.
Thanks!

**Comment by ukmunnithan** [comment]
@marchbold @ajwfrost what should be the minimum os version and target sdk version need to set in the app.xml file.

**Comment by marchbold** [comment]
We are currently suggesting versions as follows:
- iOS minimum 9 

```xml
<key>MinimumOSVersion</key>
<string>9.0</string>
```

- Android minimum 19 
- Android target 28

```xml
<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="28" />
```
