### ISSUE TITLE
Screen size - Xiaomi Mi 9T

### ISSUE THREAD

**Issue by caraiz** [Gamua/Adobe-Runtime-Support#326]
## Problem Description

Xiamoi Mi 9T has a resolution of 1080x2340, but the stage dimensions (not fullscreen) are of 1080x1913, which are wrong because appears a black border. 

- AIR 33.1.1.98
- Android 10

![photo_2020-05-17_21-02-04](https://user-images.githubusercontent.com/12096804/82157510-2c064400-9882-11ea-91e4-8d73d469afea.jpg)

**Comment by ajwfrost** [comment]
Hi
Can you please try adding the max_aspect value into your AIR application descriptor file?
`<meta-data android:name="android.max_aspect" android:value="2.50" />`
(within the Android section, inside the `<application>` tag)
thanks

**Comment by caraiz** [comment]
Hi, that solves the "problem".
Thanks!
