### ISSUE TITLE
Unable to enumerate devices

### ISSUE THREAD

**Issue by qq5000521** [Gamua/Adobe-Runtime-Support#327]
windows10 
FlashBuilder  debug 
IPhoneXR
Unable to enumerate devices

**Comment by ajwfrost** [comment]
Hi
Which version of the AIR SDK are you using? there were some updates in the most recent (33.1.1.98) which should have resolved most of the issues with this. But if not - can you use a command prompt and the ADT command to enumerate the devices and see what comes out?
e.g. `adt -devices -platform ios`
thanks

**Comment by qq5000521** [comment]
Thank you very much 
using version SDK 33.1.1.98


use**adt -devices -platform ios**
An error is as follows:
ERROR: Could not connect to lockdownd: Missing HostID (-20)
Could not read device info

**Comment by ajwfrost** [comment]
This appears to be a failure within the libimobiledevice tool related to the device's USB connection. There are a few suggestions online which suggest resetting things/rebooting etc, but the other one to check first perhaps is if you unplug your phone, then when you plug it in, unlock it and make sure you've got the computer set as "trusted"?

See e.g. https://github.com/libimobiledevice/libimobiledevice/issues/510

**Comment by qq5000521** [comment]
Iphone6 is normal, iphoneXR will give an error （Unable to enumerate devices）.

**Comment by ajwfrost** [comment]
Okay curious .. just to check, if you go into the `lib\aot\bin\iOSBin` folder of the SDK in a command prompt, and run `ideviceinfo.exe` (with just the XR plugged in), do you still get the same error report?

As a last-ditch option, if you check the below URL, can you try downloading the zip for the complete libimobiledevice tool and extract this somewhere and then again try the `ideviceinfo.exe` tool?
http://docs.quamotion.mobi/docs/imobiledevice/download

thanks

**Comment by qq5000521** [comment]
@ajwfrost thanks 
Your method Error display:

ERROR: Could not connect to lockdownd: Pairing dialog response pending (-19)

**Comment by qq5000521** [comment]
@ajwfrost thanks
Your method Error display:

ERROR: Could not connect to lockdownd: Missing HostID (-20)

**Comment by qq5000521** [comment]
ideviceinfo -s 
Device information can be displayed

**Comment by ajwfrost** [comment]
Hi @qq5000521  - thanks for that. So is this that, when using the binaries from Quamotion, you are able to see the device information, but if you use the binaries from our SDK, then you can't?

In which case it perhaps means we've missed one of the dependent binaries (they don't appear to have updated the files since we got them): can you copy all the files from the Quamotion package into that lib\aot\bin\iOSBin folder and try it again via ADT/Flash Builder?

thanks

**Comment by qq5000521** [comment]
@ajwfrost Thank you for your reply
Both SDK and Quamotion can be used to view the information, but flash builder debugging will report an error through enumerate devices

**Comment by qq5000521** [comment]
@ajwfrost Thank you very much. I solved this problem and the Windows enumeration device reported an error because my iTunes version was too low.I hope more people will pay attention to this little detail
