### ISSUE TITLE
air for iOS.An error occurs when Japanese is entered into the app name.

### ISSUE THREAD

**Issue by awaza001** [Gamua/Adobe-Runtime-Support#331]
I put Japanese in the appname of the general tab.
Publishing　done.

but... error report.
ITMS-90035: Invalid Signature appears in Transporter.

I can't use Japanese for the application name on iOS. It's supposed to affect all languages except English.

ITMS-90035 is a famous error.
It always comes up when the project file name in xcode has Japanese characters.
https://program-life.com/1428

But with xcode, you can add Japanese to the application name on iOS.

**Comment by ajwfrost** [comment]
Hi

Is it possible for you to provide an IPA file containing a basic test case with Japanese in the application name, and we can check what's happening?

If you're also able to provide an IPA file from an application generated using XCode using Japanese in the name, we can see why theirs works and the AIR one doesn't..

thanks

**Comment by awaza001** [comment]
I found it.
This is an image with the extension ipa rewritten to zip.
exec(unix executable file) 
If the exec is set to Japanese, an error occurs.
exec=app name.

**Comment by awaza001** [comment]
![jpnname](https://user-images.githubusercontent.com/55721791/82443860-2c4e4b80-9add-11ea-89a1-4b7ad46300c1.jpg)

**Comment by ajwfrost** [comment]
Hi

Can I just check, is the folder that you're displaying there also using Japanese characters? or is this folder name okay and it's just the filename that's okay on the left but not on the right?

I would expect we can change the filename of that executable file as this is separate from the application's name (or can be, we just happen to use the same for both..)
```
        <key>CFBundleExecutable</key>
        <string>[name of the AIR-generated binary file]</string>
        <key>CFBundleName</key>
        <string>[app name that can include Japanes]</string>
```

So we can update ADT to try to handle non-ascii characters appropriately via a different executable name.

**Comment by awaza001** [comment]
![foldername](https://user-images.githubusercontent.com/55721791/82454764-219bb280-9aed-11ea-91b3-4f3db517c8fd.jpg)
That's right.
The payload folder is also in Japanese.

I don't know what ADT is.
Where do I write this code? 
XML?

**Comment by ajwfrost** [comment]
Okay thanks.

No that's fine we should be able to sort it all out from here ... ADT is the AIR Developer Tool which is the application actually doing the packaging up of the IPA file! I'm assuming then, you're using Animate/FlashBuilder etc which hide the complexity of ADT and make it (a bit) easier to use!

**Comment by awaza001** [comment]
Yes I did. I'm using AnimateCC2020.adobe air31.1.63. only.
I would like you to tell me how to deal with it.

**Comment by ajwfrost** [comment]
Okay so this is interesting, Animate is setting the value you give in "App name" into the 'filename' and 'name' fields of the application descriptor file which we read, the initial SWF filename comes from the 'Output name' in the general publish settings, and the application ID is given under the 'Deployment' tab.

Then in ADT, we're looking at the 'filename' field to create the name of the .app folder and the executable file, but the 'name' field for the 'CFBundleName' value.

So this should be a relatively easy change... once we've done it, yes it would be something included in the next release of AIR SDK, but we can perhaps provide the updated adt.jar separately for you..

thanks

**Comment by awaza001** [comment]
I want a new adt.jar.
I tried to open the SDK in a text editor, but I couldn't.
If there are any changes I can make, please let me know here.
By the way, I'm on the basic plan for $199.

**Comment by ajwfrost** [comment]
Hi
So if you find where you had installed the AIR SDK, can you back up the existing `adt.jar` file from the lib folder, and then replace it with the new one from the below link?
https://transfer.harman.com/message/Ocgn0Ch6rnCHLjksAE80Ce
This is from AIR 33.1.1.98, I suspect it won't build Android apps for you unless the rest of the SDK is also from that version, but for iOS it should be okay.
If you're able to confirm that it then installs/uploads the IPA, we can get this into a formal release.
thanks

**Comment by awaza001** [comment]
Thanks!! Solved!!
I was able to upload it in the new adt.jar.
I was able to send it via mac transporter.
I can japanese app name!
