### ISSUE TITLE
Windows Air app stop and go again when finger is stationnary

### ISSUE THREAD

**Issue by pol2095** [Gamua/Adobe-Runtime-Support#340]
## Problem Description

on Windows in all Air apps, when I put a finger on the screen, if the finger is stationnary the animation stop and go again...

* AIR SDK 33.1.1.98, AIR SDK 32

* Windows only, AIR only, work correctly on Flash Player Standalone

* I can reproduce it on all Air apps

* link to the [Starling forum](https://forum.starling-framework.org/d/22520-windows-bug-when-finger-is-stationnary)

## Steps to Reproduce

on Windows in all Air apps, when I put a finger on the screen, if the finger is stationnary the animation stop and go again...
The cpu and memory doesn't increase
I tried on a XPS and a Lenovo
It's not neccessary to add a Touch event.

```
package
{
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.text.TextField;
	import flash.utils.getTimer;

	public class Main extends Sprite
	{
		private var textField:TextField = new TextField();
		private var sprite:Sprite = new Sprite();
		private var reverse:Boolean;
		private var start:Number = 0;

		public function Main()
		{
			this.addEventListener(Event.ADDED_TO_STAGE, addedToStageHandler);
		}

		private function addedToStageHandler(e:Event):void
		{
			this.removeEventListener(Event.ADDED_TO_STAGE, addedToStageHandler);
			
			textField.border = true;
			textField.wordWrap = true;
			textField.width = 400;
			textField.height = 200;
			textField.y = 40;
			this.addChild(textField);
			
			sprite.graphics.beginFill(0x0000FF);
			sprite.graphics.drawRect( 0, 0, 100, 100);
			sprite.graphics.endFill();
			sprite.y = textField.y + textField.height + 20;
			this.addChild( sprite );
			
			this.addEventListener(Event.ENTER_FRAME, onEnterFrame);
		}
		
		private function onEnterFrame(event:Event):void
		{
			if( sprite.x > 400 ) reverse = true;
			if( sprite.x < 0 ) reverse = false;
			if( ! reverse ) sprite.x += 2;
			if( reverse ) sprite.x -= 2;
			textField.text += ( getTimer() - start ).toString() + " ";
			start = getTimer();
		}
	}
}
```

* I added a [video](http://pol2095.free.fr/video/Finger_Touch.mp4)

## Known Workarounds

no workaround

**Comment by hardcoremore** [comment]
@pol2095 Are you saying that execution of entire application is stopped after small delay when you touch screen or click with mouse and hold it in place.

Or only ENTER_FRAME event is not being dispatched. Did you tried with interval, will the interval dispatch?

**Comment by pol2095** [comment]
With the mouse no problem, only when I put a finger (my index is stationnary) of all Air apps.
the animation stop and go again... stop and go again...
see the [video](http://pol2095.free.fr/video/Finger_Touch.mp4)

**Comment by ajwfrost** [comment]
Curious! So with your finger, it's pausing the animations, but with mouse-down it's not.. 
We can check on a touchscreen laptop, you may be able to work around it by setting the multitouch input mode to 'none' so that touches are just interpreted as mouse events.. default appears to be 'gesture' so perhaps it's waiting to see what you do with your finger. Shouldn't be blocking the animation process though!

https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/ui/MultitouchInputMode.html

**Comment by pol2095** [comment]
@ajwfrost
`Multitouch.inputMode = MultitouchInputMode.NONE;` doesn't solve the problem

**Comment by ajwfrost** [comment]
Interesting - thanks for those extra details. We'll investigate..

**Comment by pol2095** [comment]
I tried with my new XPS 13 and my old Lenovo Yoga Pro 2, same problem

**Comment by pol2095** [comment]
no bug using Air 31

**Comment by pol2095** [comment]
Any news on this problem ?

**Comment by pol2095** [comment]
> Interesting - thanks for those extra details. We'll investigate..

Any news on this problem ?

**Comment by pol2095** [comment]
Any news about this problem ?
the bug still occurs in Air 33.1.1.190

**Comment by ajwfrost** [comment]
This one's on our list but slightly tricky to debug .. will try to get some eyes on this shortly though.
thanks

**Comment by pol2095** [comment]
@ajwfrost 
Thanks for your prompt reply

**Comment by ajwfrost** [comment]
@pol2095  it's taken a while I'm afraid but we now have a fix for this which will go into our next release..

**Comment by pol2095** [comment]
Thanks, good job.
