### ISSUE TITLE
InfoPlist.strings support

### ISSUE THREAD

**Issue by jackwlee01** [Gamua/Adobe-Runtime-Support#345]
We need to localise the camera permissions message. We specify NSPhotoLibraryUsageDescription in the app.xml, but this by itself is not sufficient for our localisation requirements.

To achieve this natively I would create an InfoPlist.strings file (see link below), but I can't dig up any info on whether this is supported by Adobe Air. I attempted to create these localisation files through XCode, and copy the results of the built app into my Air project but I couldn't get it to work.

Are InfoPlist.strings files supported by Adobe Air, and if so are you able to offer any guidance on their usage?

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html

**Comment by ajwfrost** [comment]
Hi - we don't have a way of doing this currently I'm afraid, but I've added it to our backlog as it doesn't look like it would be particularly complex to do...

thanks

**Comment by jackwlee01** [comment]
Thank you. This is important for our app as we are supporting 14 languages, and the permission dialogues are the only component that we are not yet able to localise.

**Comment by marchbold** [comment]
@ajwfrost I haven't done this but just found one of our clients who went through this a while ago using `purposeStrings.xml`, is that still supported? 

https://helpx.adobe.com/au/flash-player/release-note/fp_28_air_28_release_notes.html


> Starting AIR 28, developers can provide localized purpose strings for the permissions required in the application. Developers are required to package an XML file called purposeStrings.xml in the application. The format of this XML file should adhere to the following. A sample xml file is available in AIR SDK at SDK/samples/purposeStrings-sample.xml. Use the below mentioned command to package a sample application using the purposeStrings.xml file.


Example from AIR 32:

```xml
<purposeString>  
    <iPhone>
     <text xml:lang="da">               
       <string key = "NSPhotoLibraryUsageDescription" > Formålstreng til fotobibliotek på dansk</string>
       <string key = "NSCameraUsageDescription" > Formålstreng til kamera på dansk </string>
    </text>
     <text xml:lang="de">               
       <string key = "NSPhotoLibraryUsageDescription" > Zweck String für Foto-Bibliothek in deutscher Sprache </string>
       <string key = "NSCameraUsageDescription" > Zweck String für Kamera in Deutsch  </string>
    </text>
    <text xml:lang="en">               
       <string key = "NSPhotoLibraryUsageDescription" > Purpose string for photo library in English </string>
       <string key = "NSCameraUsageDescription" > Purpose string for camera in English </string>
    </text>
    <text xml:lang="fr">               
       <string key = "NSPhotoLibraryUsageDescription" > Chaîne de but pour la photothèque en français </string>
       <string key = "NSCameraUsageDescription" > But chaîne pour caméra en français  </string>
    </text>
  </iPhone>
</purposeString>
```


Supposedly, just put that in a file `purposeStrings.xml` and package it at the root of your app.

**Comment by jackwlee01** [comment]
Thanks @marchbold! This works for us.

**Comment by ajwfrost** [comment]
@marchbold  thanks! I did see a reference to 'purpose' in the code but it didn't immediately seem obvious that this was for localisation.. yes it looks like this is all fine, there are some strings it won't accept such as DTPlatformName and other central things, but other than that yes this will get parsed and the details written into the existing localised string files..

@jackwlee01  are you okay to close this issue please?

thanks
