### ISSUE TITLE
Worker ByteArray memory leak

### ISSUE THREAD

**Issue by pol2095** [Gamua/Adobe-Runtime-Support#347]
## Problem Description

when I use
mainToBack.send( bytes );
I have a memory leak

* Air 33.1 Windows, Android (Mac, iOS not tested)
* Air, Flash, debug and release
* all users can reproduce
* link to the [Starling/Feathers discussion](https://forum.starling-framework.org/d/22557-worker-bytearray-memory-leak).

## Steps to Reproduce

when I use
mainToBack.send( bytes );
I have a memory leak, the memory increase in Scout

```
package
{
    import flash.display.BitmapData;
    import flash.display.Sprite;
    import flash.events.Event;
    import flash.system.MessageChannel;
    import flash.system.Worker;
    import flash.system.WorkerDomain;
    import flash.utils.ByteArray;
 
    public class Main extends Sprite
    {    
        protected var mainToBack:MessageChannel;
        
        /**
        * Start the app in main thread or worker thread mode
        */
        public function Main()
        {    
            var worker:Worker;
            if (Worker.current.isPrimordial)    
            {
                //Create worker from the main swf 
                worker = WorkerDomain.current.createWorker(this.loaderInfo.bytes);
                
                //Create message channel TO the worker
                mainToBack = Worker.current.createMessageChannel(worker);
                
                //Now that we have our two channels, inject them into the worker as shared properties.
                //This way, the worker can see them on the other side.
                worker.setSharedProperty("mainToBack", mainToBack);
                
                //Lastly, start the worker.
                worker.start();
                
                this.addEventListener( Event.ENTER_FRAME, enterFrameHandler );
            }
            else
            {
                worker = Worker.current;
            
                //Listen on mainToBack
                mainToBack = worker.getSharedProperty("mainToBack");
                mainToBack.addEventListener(Event.CHANNEL_MESSAGE, onMainToBack);
            }
        }
        
        protected function onMainToBack(event:Event):void
        {
            if(mainToBack.messageAvailable)
            {
                var bytes:ByteArray = mainToBack.receive();
                //var bytes:ByteArray = mainToBack.receive().bytes;
                bytes.clear();
            }
        }
        
        private function enterFrameHandler(event:Event):void
        {
            var bytes:ByteArray = new ByteArray();
            bytes.writeUTF( "update" );
            var bitmapData:BitmapData = new BitmapData( 100, 100 );
            bitmapData.copyPixelsToByteArray(bitmapData.rect, bytes);
            bitmapData.dispose();
            mainToBack.send( bytes );
            //mainToBack.send( { bytes : bytes } );
            bytes.clear();
        }
    }
}
```

## Known Workarounds

not use directly ByteArray in MessageChannel.send() but in an Object like this :
mainToBack.send( { bytes: bytes } );

**Comment by itlancer** [comment]
I have seen something like that. There are some issues with that in AIR when you use `ByteArray::shareable=true` or send `ByteArray` as you wrote without `ByteArray::clear()` after that.
Try to clear bytes after sending it to `Worker` it should fix your issue. But some other issues with `Worker` and `ByteArray` still exists I beleive but cannot figure out yet how it correctly reproduce.

**Comment by pol2095** [comment]
bytes.clear(); doesn't solve the problem.

**Comment by ajwfrost** [comment]
Can you try setting shareable to false again? We can take a look at some point but I would also advise not creating a new bytearray for each message..

See also https://stackoverflow.com/questions/18160165/bytearray-clear-not-working-for-shared-bytearrays

Setting the length, and clearing the data, are no longer simple operations once you've set the shareable property to true. We need to sync these calls across all of the threads - although I would expect that it's then synchronised i.e. we wait in that calling bit of ActionScript until the other ActionScript has finished using the bytearray. But, easy to hit deadlock in this sort of code, so much better to avoid setting length/clear within message handlers like this. My suggestion would be to have multiple local bytearrays in each worker if you need, and just have a single shared bytearray that you copy the data into/out of (maybe a bytearray for each direction?).


Feel free to chip in, anyone who's looking at https://github.com/adobe/avmplus/blob/master/core/ByteArrayGlue.cpp
:-)

**Comment by zwetan** [comment]
use a shared mutex to solve the problem

see [Mutex](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/concurrent/Mutex.html)

> The Mutex (short for "mutual exclusion") class provides a way to make sure that only one set of code operates on a particular block of memory or other shared resource at a time. The primary use for a Mutex is to manage code in different workers accessing a shareable byte array (a ByteArray object whose `shareable` property is `true`). However, a Mutex can be used to manage workers' access to any shareable resource, such as an AIR native extension or a filesystem file. No matter what the resource, the purpose of the mutex is to ensure that only one set of code accesses the resource at a time.

primordial
```
var mutex:Mutex =new Mutex();

//...
worker.setSharedProperty("mainToBack", mainToBack);
worker.setSharedProperty("mutex", mutex);

```

worker
```
mainToBack = worker.getSharedProperty("mainToBack");
var mutex:Mutex = worker.getSharedProperty("mutex");
```

now either primordial or worker, when you work on your ByteArray data
```
mutex.lock();
bytes.writeUTF( "update" ); // or whatever
mutex.unlock();
```

see also
https://github.com/adobe/avmplus/blob/master/test/acceptance/as3/Workers/ByteArrayWorkers.as

**Comment by pol2095** [comment]
@ajwfrost 
 setting shareable to false again doesn't solve the problem
I create new bytearray for each message because bytes.clear() doesn't work correctly

@zwetan
Mutex doesn't solve the problem

**Comment by zwetan** [comment]
@pol2095 what is the sample  code where you tried mutex, maybe you used it wrong

**Comment by zwetan** [comment]
also your sample is wrong in the way you are not sharing the ByteArray itself

you should do
```
var mutex:Mutex = new Mutex();
var bytes:ByteArray = new ByteArray();
      bytes.shareable = true

worker.setSharedProperty("mutex", mutex);
worker.setSharedProperty("bytes", bytes);
```

and then
```
var mutex:Mutex = worker.getSharedProperty("mutex");
var bytes:ByteArray = worker.getSharedProperty("bytes");
```

cf. [MessageChannel.send()](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/system/MessageChannel.html#send())

> There are five types of objects that are an exception to the rule that objects aren't shared between workers:
> 
>   - Worker
>   - MessageChannel
>   - shareable ByteArray (a ByteArray object with its shareable property set to true
>   - Mutex
>   - Condition

if you want to share the state of data do use a `ByteArray`
if you want to shared short message/events then use `MessageChannel`

anyway I see that as "Not a Bug"

**Comment by pol2095** [comment]
I understand the problem now, it's not a bug, thanks.
