### ISSUE TITLE
Can licensed users add their own splash image?

### ISSUE THREAD

**Issue by dmunsie** [Gamua/Adobe-Runtime-Support#351]
In the past we've used the technique(s) outline here:
https://airnativeextensions.github.io/tutorials/android-splash-screen

Are these method(s) still available for Air33+ and more importantly does Harman officially allow this? Thank you.

**Comment by ajwfrost** [comment]
Hi

Yes I can't see why this wouldn't still work. We certainly don't want to restrict licensed users from doing this if they want; for users who are on the 'free tier', we add our own splash screen which uses a slightly different mechanism and is likely to obscure this view.

On iOS, it's similar - commercially licensed users can add their own launch storyboard, but this is also the mechanism that we'll be using for the free tier with our own splash screen.

thanks

   Andrew
