### ISSUE TITLE
___isPlatformVersionAtLeast  Undefined symbols for architecture newest SDK

### ISSUE THREAD

**Issue by Devarai** [Gamua/Adobe-Runtime-Support#362]
Hi,

I am using Harman Air Version 33.1.1.98 on Windows.

I cannot compile my iOS IPA due to this error:

Undefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:
      -[BaseClassAdMob getAdSize] in C:\Users\Win10\AppData\Local\Temp\db1fa52f-056c-48c4-9be1-d2b26635fef6\libcom.myflashlab.air.extensions.admob.a(BaseClassAdMob.o)
  "_GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth", referenced from:
      -[BaseClassAdMob getAdSize] in C:\Users\Win10\AppData\Local\Temp\db1fa52f-056c-48c4-9be1-d2b26635fef6\libcom.myflashlab.air.extensions.admob.a(BaseClassAdMob.o)
ld: symbol(s) not found for architecture arm64
Compilation failed while executing : ld64

Replacing lclang_rt.ios did not help.

What can I do now?

Henning

## Steps to Reproduce

Tell us how this issue can be reproduced. Seriously: if you want this issue to be fixed, this is the part you **really** need to get nailed.
Give us a minimal example:

* As little code as possible. Get to the root of the problem!
* As few dependencies as possible. Did the problem pop up with Feathers? Try to reproduce it with Starling only.
* Remove any ANEs (except if they are vital for the problem).
* Include all necessary files (e.g. textures).

## Known Workarounds

Just in case others run into this – do you happen to know of a workaround? Otherwise, just remove this section altogether.

**Comment by marchbold** [comment]
Can you provide some more information? Normally to resolve this you need an ANE that links against `lclang_rt.ios` and add the latest version to your AIR SDK.

**Comment by marchbold** [comment]
Yes I would suggest something a lot more recent than iOS 12.

**Comment by Devarai** [comment]
I replaced it now with the newest iOS 13 version and there is now this error:

Undefined symbols for architecture arm64:
  "_GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth", referenced from:
      -[BaseClassAdMob getAdSize] in C:\Users\Win10\AppData\Local\Temp\1f3e0be5-da29-462e-a1b8-c56969f64eb7\libcom.myflashlab.air.extensions.admob.a(BaseClassAdMob.o)
ld: symbol(s) not found for architecture arm64
Compilation failed while executing : ld64

What now?

**Comment by marchbold** [comment]
That's an issue with your ANE, looks like you are missing the AdMob SDK. I'd suggest you contact the support for your extension.

**Comment by Devarai** [comment]
Thanks a lot for your help Michael . Got it working on my MacBook.
