### ISSUE TITLE
AIR 33.1.1.98 - Google Play Store reporting apps as non 64-bit compliant

### ISSUE THREAD

**Issue by FrogDigital** [Gamua/Adobe-Runtime-Support#367]
My client has just had an email from Google saying that two apps I created (for Android phone and tablet) have been detectetd as not offering 64-bit support.

However, both were created using Harman AIR 33.1.1.98 back in March, and I thought that this ensured they were 64-bit compliant?

Any help or insight you can give would be very useful as my client is now nervous that (A) their apps will be removed from PLay Store, and (B) they cannot be updated.

Thanks

**Comment by alanlanglois** [comment]
Same here, using AIR 33.0.2.338
I thought it was maybe due to ANEs, but one of the app has no ANE and is listed as well

**Comment by FrogDigital** [comment]
Im hoping its just a "catch all" type search by Google who simply detect the use of the Air SDK and flag it as non-compliant. 
Problem with this is that the email really is worded like the app is definitely not 64-bit compliant. :(

_snippet from Google's email..._

> As of June 30, 2020, we have detected the following app(s)* were not compliant:
> --
> •Aerogen Solo - phone version
> •Aerogen Solo - tablet version

**Comment by FrogDigital** [comment]
@alanlanglois  - just out of interest. Did you publish your app within **Adobe Animate**?
Im wondering if Animate doesnt create 64-bit apps, even with Harman's excellent SDK.

**Comment by ptysbilbo** [comment]
Are you sure you created a 64-bit version. By default Air SDK 33 is creating 32-bit version.
To switch to 64 bit you can for example uncomment this line:
DefaultArch=armv8
in the following file in the SDK folder: \AIR33.1\lib\adt.cfg

**Comment by alanlanglois** [comment]
Ok, I think i know why. 
From the last release not. 
![image](https://user-images.githubusercontent.com/712986/86134302-bc72ae00-bae9-11ea-99a9-9805aff899b6.png)
I don't remember changing that before packaging...
![image](https://user-images.githubusercontent.com/712986/86134327-c399bc00-bae9-11ea-9f9e-1056de90c8c7.png)

**Comment by alanlanglois** [comment]
> @alanlanglois - just out of interest. Did you publish your app within **Adobe Animate**?
> Im wondering if Animate doesnt create 64-bit apps, even with Harman's excellent SDK.

Nope I used VSCode on macOS (first time) before I was on Windows on Flashdevelop ;)

**Comment by ptysbilbo** [comment]
To be sure, that apk is 64 bit, check its content. In a "lib" folder, there should be a "arm64-v8a" folder.
If it's "armeabi-v7a" - apk is 32bit

**Comment by FrogDigital** [comment]
@ptysbilbo - thank you so much. you have at least confirmed that these are 32bit versions. I only have "armeabi-v7a" folder within the apk!
Argh!!! Harman!!! This is a nightmare. I am now going to have to work out how to compile 64-bit versions and then reopen a signed off, closed project with my client. ARgh.

**Comment by FrogDigital** [comment]
THanks for that info @alanlanglois 
Seems I can still use ANimate, but I just need to find a certain configuration flag and ensure its chagned correctly.

The hunt begins....

**Comment by ptysbilbo** [comment]
@FrogDigital - no problem.
Creating a 64-bit isn't really a big deal. Just uncomment this line:
"DefaultArch=armv8" in cfg file, as I mentioned earlier.

**Comment by FrogDigital** [comment]
Problem is, I dont even know where that line exists! I suspect you are referring ot the ADT? - a tool I have never used.
All my apps over the years have been created in Flash/Animate (successfully so!) and Im unfamiliar with anything else.

**Comment by ptysbilbo** [comment]
@FrogDigital no - it's in the SDK Folder
When you downloaded SDK form Harman site, you extracted it to a folder, eg. "AIR33.1"
In this folder look for the following file: 
AIR33.1/lib/adt.cfg
This "adt.cfg" is a text file - jest edit it and uncomment the line (remove #)

**Comment by FrogDigital** [comment]
Oh wow. That sounds remarkably easy :)
Going to try it right now...
_(buttocks clenched)_

**Comment by ajwfrost** [comment]
FYI the latest Animate versions also add the ARMv8 targets as a package option.

I would suggest switching both of the lines:
```
DefaultArch=armv8
OverrideArch=armv8
```
since if your toolchain is adding "-arch armv7" already, then you would need the 'override' version.

As mentioned above, you would need to check that you've got the arm64-v8a folder in your APK file - but please also ensure you've got the version number slightly higher for the ARMv8 one, so that this is chosen as the preferred option for devices that can run both ARMv7 and ARMv8 binaries..

See the release notes, section entitled: "Android Applications – Play Store Uploads"

**Comment by FrogDigital** [comment]
It worked!
I have now used ANimate to publish out the APK file jsut as before, except I "uncommented" both the DefaultArch and OverrideArch lines from the CFG file @ptysbilbo mentioned.
I now have an APK without a "armeabi-v7a" folder, and instead contains an "arm64-v8a" folder.

Thank you so so much guys. I definitely owe you one.

P.S. @ajwfrost - I rolled back to Animate 2019 after updating to the latest and hating the new interface which had removed all the AS shortcuts which made my productivity so high. So unfortunately, Im stuck with whatever I can get done in Animate 2019.
However, the mobile market changes so much and all my clients seem to want "one app fits all" for Apple, Android and everything in between that it has become too difficult for me to continue within this sector and still make good profits. THerefore, this was the last "store front" app that I will be making I think.
If any great freelancer wants to sub-contract to me for any future work, please do! :D.... but personally, Im happier to exist outside the public facing mobile sector I think. Sad times as its been very good to me for 14 years of trading. :(

**Comment by FrogDigital** [comment]
PPS - a quick thank you to Andrew Frost @ajwfrost and everyone on the Harman team. Since you guys took over its been a different AIR, and a much more pleasant, developer focussed place to be. The way you handle problems and questions, how you keep your developers informed and part of the conversation, all has been so refreshing from the "Adobe way". Much love 👍  :)

**Comment by ajwfrost** [comment]
Thanks @FrogDigital! appreciate the comments and will pass them on. Sad that you're having to move on, best wishes with it all!

**Comment by leossmith** [comment]
I think this is a false positive. I also get a couple emails from clients, but when checking the console, it is clear this is a false positive.

![image](https://user-images.githubusercontent.com/4300876/86234620-e7b7d480-bb9f-11ea-88a2-e1e0c0fe8a08.png)

**Comment by FrogDigital** [comment]
@leossmith - you might very well be correct, however, in my case it was definitely that my apps were _not_ 64-bit.

To know for sure, follow the excellent tip from @ptysbilbo ...

> To be sure, that apk is 64 bit, check its content. In a "lib" folder, there should be a "arm64-v8a" folder.
> If it's "armeabi-v7a" - apk is 32bit
