### ISSUE TITLE
AIR 33.1.1.176 can't build in 32 bits android 

### ISSUE THREAD

**Issue by marcanw** [Gamua/Adobe-Runtime-Support#379]
I'm building using Animate and the adt.cfg scheme.
I noticed that I can't build in 32 bits android anymore. receiving an INSTALLED_FAILED_NO_MATCHING_ABIS.
Same project and adt.cfg builds fine in 32 bits on 33.1.1.98.
So it's not a big deal because I can use 33.1.1.9 for the 32 bits release and  33.1.1.176 for the 64 but it might be a problem in the future.
Cheers

**Comment by ajwfrost** [comment]
This should still work in .176 - can you confirm what's in your adt.cfg in the .176 folder? and then looking in your generated APK file in a zip manager, what's the subfolder name under the 'lib' folder?

As far as I know, in Animate you set the ABI (ARMv7 or ARMv8 etc) and they pass this through to ADT, which can then be adjusted if there's an entry for overriding this.

Also if you change that adt.cfg and add:
`DebugOut=true`
then you should get an adt.log file generated in your user home folder, which will show more what's going on..

thanks

**Comment by marcanw** [comment]
Damn my bad.
I wasn't  editing the right adt.cfg.
It's working now.
Thank you and sorry for disturbing :-|
