### ISSUE TITLE
iOS App Launch time is long

### ISSUE THREAD

**Issue by Devkjk** [Gamua/Adobe-Runtime-Support#386]
MacOS10.14.6
Animate2020
AIRSDK33.1.1.98
Debug at iphone7 iOS13

I set device install and pulished by Animate.
The launch time is too long,about 20-30 seconds until show harman splashScreen.(before vis asking debug network dialog )
I tested the app a few years ago,the launch time is short.
Is it something bug? Or it is correct behavior?

**Comment by marchbold** [comment]
This sounds like normal behaviour, your app is just waiting to connect to a debugging IDE and timing out eventually. 

The issue is probably with the debugging configuration / setup you have rather than AIR.

**Comment by Devkjk** [comment]
Thanks.
I will try testflight.
