### ISSUE TITLE
Error when upload iOS app by Transporter.

### ISSUE THREAD

**Issue by Devkjk** [Gamua/Adobe-Runtime-Support#389]
MacOS10.14.6
Animate2020
AIRSDK33.1.1.98
Transporter1.1.1.1

When deliver,below error occurs.
How can I do for this?
```
ERROR ITMS-90164: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. According to the provisioning profile, the bundle contains a key value that is not allowed: 'true' for the key 'get-task-allow' in 'Payload/xxxVer2.2.app/xxxVer2.2'."
```

```
ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/xxxVer2.2.app/xxxVer2.2' must be signed with the certificate that is contained in the provisioning profile."
```

**Comment by FliplineStudios** [comment]
Strange, we haven't had any problems ourselves with AIR 33.1 and iOS, though in the past others have had similar issues in AIR 32 and older:

https://community.adobe.com/t5/air/error-itms-90164-quot-invalid-code-signing-entitlements/td-p/10566262?page=1

I would double-check to make sure you're definitely using a distribution provisioning profile and app store distribution certificate, as that get-task-allow key should only be found in development builds, not in distribution builds.  If you're already using distribution profile/certificate and generating an ipa-app-store build, you may want to add Entitlements to your application XML and explicitly set <key>get-task-allow</key><false/> if it's still giving you this error.

**Comment by Devkjk** [comment]
Hi.Tank you your advice.Yeah,very strange.
I see [https://stackoverflow.com/questions/28359988/itms-90179-invalid-code-signing-itms-90209-invalid-segment-alignment](url)
I can deliver by the first answer.
