### ISSUE TITLE
[macOS] Cannot launch and test application with AIR 33.1.1.190 and Adobe Animate

### ISSUE THREAD

**Issue by itlancer** [Gamua/Adobe-Runtime-Support#393]
## Problem Description
Cannot launch and test any application with AIR 33.1.1.190 and Adobe Animate for macOS.
After application compilation IDE throws window with error: "Test Movie launch failed."

Tested with Adobe Animate 20.0.2 (22168) and Adobe Animate 20.5 for macOS Catalina 10.15.4.
The same problem in all cases with any AIR project (even "empty").
It works fine with AIR 33.1.1.176 and earlier for macOS.
Also It works fine with Windows.

But application packaging works fine. So seems it only `adl` related issue.
If you try to launch `adl` via Terminal you will see different output.
For 33.1.1.190 you will see:
```
Last login: Thu Jul 16 17:35:36 on ttys000
username@MacBook-Pro-USER ~ % /Users/username/Documents/SDK/AIRSDK_MacOS_33_1_1_190/bin/adl ; exit;
zsh: killed     /Users/username/Documents/SDK/AIRSDK_MacOS_33_1_1_190/bin/adl

[Process completed]
```

For 33.1.1.176 you will see:
```
Last login: Thu Jul 16 17:35:58 on ttys000
username@MacBook-Pro-USER ~ % /Users/username/Documents/SDK/AIRSDK_MacOS_33_1_1_176/bin/adl ; exit;
Adobe (R) AIR (R) Debug Launcher (ADL)
Version 33.1.1.98
Copyright (c) 2008-2019 Adobe. All Rights Reserved.

application descriptor file not specified
usage:
  adl ( -runtime <runtime-dir> )? ( -pubid <pubid> )? -nodebug? ( -profile PROFILE )? ( -extdir <extensions-dir> )? ( -screensize SCREEN_SIZE )? <app-desc> <root-dir>? ( -- ... )?
  adl -help

PROFILE                : mobileDevice|extendedMobileDevice|desktop|extendedDesktop|tv|extendedTV
SCREEN_SIZE            : ( <width>x<height>:<fullscreen width>x<fullscreen height> )|PREDEFINED_SCREEN_SIZE
PREDEFINED_SCREEN_SIZE : iPhone|iPhoneRetina|iPhone5Retina|iPhone6|iPhone6Plus|iPod|iPodRetina|iPod5Retina|iPad|iPadRetina|Droid|NexusOne|SamsungGalaxyS|SamsungGalaxyTab|QVGA|WQVGA|FWQVGA|HVGA|WVGA|FWVGA|1080|720|480

[Process completed]
```

## Steps to Reproduce
1) Open Adobe Animate for macOS, create new one AIR project (or open existing one), choose AIR 33.1.1.190.
2) Try to test it (or simply press Ctrl+Enter).

**Actual Result:**
After test application compilation IDE throws window with error: "Test Movie launch failed."

**Expected Result:**
Application will be compiled and launched.

## Known Workarounds
Remove the code signing from `adl` binary:
`codesign --remove-signature adl`

**Comment by ajwfrost** [comment]
Yet another code-signing issue .. this one you should be able to work around by removing the `Contents` subfolder (or renaming it) from the SDK's `bin` folder..

**Comment by itlancer** [comment]
@ajwfrost,
Nope, removing bin/Contents directory didn't help.
After that you willl get error:
```
Adobe AIR could not be found.
Use "-runtime <dir>" to specify the location of the runtime.
You can download the latest version of the runtime
from http://www.adobe.com/go/getair.
```

**Comment by ajwfrost** [comment]
Okay thanks - this will need to wait until Monday when the team is back in, but just out of interest, if you remove the code signing from this binary, will it work then? (Worth backing up the file first..!)
`codesign --remove-signature adl`

**Comment by itlancer** [comment]
After removing code signature all works fine.
Waiting for complete fix at the next release.

**Comment by stoff99** [comment]
Hello @ajwfrost and @itlancer ,
thx for your answer.
I tested to remove the codesign from /bin/adl and now the emulator is working again.
Thx for that!
@ajwfrost will be there a correct codesign in the next release?

**Comment by itlancer** [comment]
It works fine with latest AIR 33.1.1.217. Thank you!
