### ISSUE TITLE
iOS binaries not being processed since 33.1.x

### ISSUE THREAD

**Issue by ventr1x** [Gamua/Adobe-Runtime-Support#394]
There currently seems to be an issue around that prevents AIR binaries from being processed for iOS.
It is unsure if this is AIR specific or something else, but our tests suggest AIR being the reason in the end.

We are currently unable to release new apps/versions because every binary gets stuck in "processing". We receive confirmation mails of "successful" processing without any warning, but the binary keeps being stuck.
This only concerns AIR apps as far as we can tell. We have other frameworks in production and tested them all out, they all work but AIR (e.g. RN, Flutter, Ionic).

Apple support seems to have no idea what is going on. I'm in contact with their dev team for three weeks now. They confirm more and more tickets with this issue but have no solution yet.

I'm currently unable to try out <=33.0 (can't upload them to the app store anymore anyhow), but that issue started after using 33.1.x.
For our tests we used the same sdk/xcode on all frameworks: 17B102
The only difference is AIR apps not including any symbols.

Just to put this possible major issue out there. We're currently losing money daily and can't release a new very important app (likely killing 30% of our revenue this year) because of this issue. I really hope that this is not AIR related, but no one as any other explanation.

<img width="1137" alt="Screenshot 2020-07-17 at 14 30 39" src="https://user-images.githubusercontent.com/7974355/87786405-2c976880-c83a-11ea-99a5-7e51e6f30648.png">

**Comment by ventr1x** [comment]
I've tested this with different accounts right now. This seems to be in fact an account wide issue and not related to AIR.

**Comment by ajwfrost** [comment]
Phew! But please keep us updated, this sounds pretty major!
FYI 33.0 releases were all using Adobe's binaries from the AIR 32 SDK, our first build of AIR for iOS was the beta of 33.1..

thanks

**Comment by FliplineStudios** [comment]
This happens to us frequently with the App Store, and has been happening for the past year or two actually even with earlier AIR builds.  I don't believe it's related to AIR itself, but occasionally builds will get "stuck" in processing.  In the past, if something remains stuck in processing for more than 30-60 minutes, what we've done is re-compile a new identical version with exactly the same assets (just incrementing the build number), and after uploading that, just having a second build processing for the same app will usually kick-start it into suddenly finishing processing for one or both of the uploads within a couple minutes.  Once in a while, if that didn't clear it up within 15 minutes, I would upload a third identical version and that would force them all to finish processing.

Apple has never acknowledged the problem, but at least in the past this has worked for us (I believe it last happened for us in February with an AIR32 build).

**Comment by ventr1x** [comment]
Of course we tried reuploading the same version.
We also created a new app in the mean time that is stuck the same way on first upload.

I tried a Flutter app today in another account, changed one of our non working air apps to its id and uploaded it there: works without issues.
This issue consists now for weeks on all apps, which is a bit outside of "happens sometimes". I never had this happen like this in my nearly 6 years as an app dev.

**Comment by itlancer** [comment]
Last time my app has been released to AppStore with AIR 33.1.1.98 without any issues at the end of May. Right now new version of my app also "stuck" in processing already for a day.
New version of my app also build with AIR 33.1.1.98.

**Comment by itlancer** [comment]
New version of my application finally accepted and released to AppStore. It took 4 days instead of usual few hours.

**Comment by ventr1x** [comment]
It works fine for me now too. I saw a change in their ui - binaries were suddenly marked with (processing) besides their names - tried uploading again and it works since then (old ones still stuck at processing though).
Apple answered a day later confirming that the issue has be solved on their end.
