### ISSUE TITLE
[IOS]AIRSDK 33.1.1.190 "Xcode version is too low"

### ISSUE THREAD

**Issue by samwang1996** [Gamua/Adobe-Runtime-Support#398]
Hi, I just have a question on AIRSDK which version is 33.1.1.190. I try to build it and verify this package on the Apple Store, but it told me that Xcode version is too low, apple need the minimum Xcode version is 1121, but Apple Store said that my ipa package Xcode build version is 1120. I read the Release Notes, and I found that the latest sdk's Xcode version is 11.2.1. I don't know what happened, but finally the Apple Store said my package Xcode version is too low. 

Can you upgrade the new Xcode version in next version? 
If you need a long time, can I fix it by myself? I have already buy the product, please help me.

**Comment by ajwfrost** [comment]
Thanks for this - we can get this updated for the next release, it shouldn't take too long (but we can provide a patch of ADT if you need it quickly?)

**Comment by ajwfrost** [comment]
FYI - are you able to check what happens if you use the below adt.jar file (you can copy this into the "lib" folder in your SDK, worth backing up the adt.jar that is there already though!)
https://transfer.harman.com/message/Bu00u9yZUoYTyHCOc5fekm

thanks

**Comment by samwang1996** [comment]
Very appreciate! Now I will try to replace the jar file and test it!

**Comment by samwang1996** [comment]
It works! Thanks a lot!

**Comment by ukmunnithan** [comment]
@samwang1996 could you please share the message that got from testflight while uploading the build?
Is it similar to this message "ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/xxxxxx.app/Assets.car' can't be processed. Rebuild your app, and all included extensions and frameworks, with the latest GM version of Xcode and resubmit."

**Comment by samwang1996** [comment]
> @samwang1996 could you please share the message that got from testflight while uploading the build?
> Is it similar to this message "ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/xxxxxx.app/Assets.car' can't be processed. Rebuild your app, and all included extensions and frameworks, with the latest GM version of Xcode and resubmit."

I‘m afraid I can't help you, because we use our company's tool to scan the app, it only told me that Xcode version is low. Now it works. If you have some error message, you can share for me and I will try to look for that😊

**Comment by samwang1996** [comment]
> @samwang1996 could you please share the message that got from testflight while uploading the build?
> Is it similar to this message "ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/xxxxxx.app/Assets.car' can't be processed. Rebuild your app, and all included extensions and frameworks, with the latest GM version of Xcode and resubmit."

If you guess that your error is similar to me, you can try to replace the official jar file and rebuild it. Follow our message, you can find that.
