### ISSUE TITLE
Player 23 in chrome. Gradients messed up with quality higher than "best".

### ISSUE THREAD

**Issue by PippoApps** [Gamua/Adobe-Runtime-Support#4]
## Problem Description

Upgrading Chrome to ver. 58, same SWF, shows a lot of graphic artefacts (misplaced colors, removed transparency, etc.) on assets with gradients when quality is higher than "best". (you can see in the attached screenshots).

Adobe tracker (please vote): https://tracker.adobe.com/#/view/FP-4198401

## Steps to Reproduce

some assets with gradients (mysteriously, some other assets are unchanged, but I can't narrow down where it comes from), if shown with render quality higher than best (8x8, 8x8linear, 16x16, 16x16linear), have all gradients messed up.

Steps to Reproduce:
Go on this url using latest chrome: http://www.pippoapps.com/_demo/bugSwfQuality/ 
SWF will load an external SWF. 
Click on "increase quality" until 8x8 is reached, you will see all gradients mess up.
You can download swf with gradient here: http://www.pippoapps.com/_demo/bugSwfQuality/bugSwfQuality.zip

Actual Result:
Colors are all messed up, gradients replaced by flat green color.

## Known Workarounds

1 - Keeping quality high, convert gradients to bitmap (cacheAsBitmap doesn't work, it caches also glitches, must be exported as bitmap from within animate). 
2 - Lower quality, anything from "best" downwards will do.

![image](https://user-images.githubusercontent.com/29799572/27740015-db904a8e-5db0-11e7-84e3-3a60928154be.png)
![image](https://user-images.githubusercontent.com/29799572/27740033-e6060f44-5db0-11e7-8ea7-ddfdbb72f5d9.png)

**Comment by viveknegi1** [comment]
Hi,
This bug is fixed and will be released in this week's beta.

-Vivek

**Comment by PrimaryFeather** [comment]
That's great to hear! Thanks a lot for working on it, Vivek, and for notifying us here!

**Comment by PippoApps** [comment]
Thank you Vivek, great news.
