### ISSUE TITLE
min sdk version error  when packaging apk by java version 7

### ISSUE THREAD

**Issue by Devkjk** [Gamua/Adobe-Runtime-Support#409]
MacOS10.14.6
Animate2020
AIRSDK33.1.1.98
java version "1.7.0_80"

When I tried to package to apk by command line ,the error occured.
`Using min SDK version >= 26 with Java runtime < 1.8 will not work due to the Android build tools`
I use 1024 p12 file, so I must use java < 1.8.
I use some ANEs of distriqt,and some anes for android require min SDK version 26.
How can I solve this ?

**Comment by ajwfrost** [comment]
Can you try with Java version 1.8.0_74 which should still support 1024-bit certificates...

**Comment by Devkjk** [comment]
Thanks I will try.
