### ISSUE TITLE
 signing error: Bundle identifier not specified

### ISSUE THREAD

**Issue by Xgamefactory** [Gamua/Adobe-Runtime-Support#41]
We are getting `Signing error: Bundle identifier not specified"` when packaging ipa with **NMAKit.framework** (Heremaps premium ios framework) tried packaging with original framework file and codesigned on mac but getting same error.
 Xcode build app file without errors so this is specific for adobe ipackager also we did not any issues for Signing error: Bundle identifier not specified" air sdk 28.122 os: mac high sierra

here is the adobe bugtrack please vote.
https://tracker.adobe.com/#/view/AIR-4198638

**Comment by marchbold** [comment]
Did you ever resolve this issue, we occasionally see it occur but haven't been able to isolate a direct cause as yet.

**Comment by ajwfrost** [comment]
In terms of a reason for this, it's where we're about to sign a framework that's being included in an IPA file, but can't find the framework identifier. There should be an "Info.plist" file in the framework, from which we take this...
I can't see any way in which this should be sporadic: if you see it happening and then call ADT again with the same command, it should happen again..? at which point, I would suggest taking out frameworks until we find out which one is the problem one, and if you can send us the Info.plist file we'll see what might be going wrong with the parsing...
thanks

**Comment by marchbold** [comment]
Ah, that would make some sense, generally we have attributed it to a Framework being downloaded incorrectly. 

Might close this issue as it seems logical it's related to the framework.
