### ISSUE TITLE
Your app currently targets API level 28 and must target at least API level 29

### ISSUE THREAD

**Issue by mohamedxxx** [Gamua/Adobe-Runtime-Support#415]
Hi
Today I want to upload my new app apk to Google Play
This new problem appears to me
The text of the message was as

" Upload failed
Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance. Change your app's target API level to at least 29."

**Comment by ajwfrost** [comment]
FYI see below comment on another issue; we're trying to get a release together currently so that this happens automatically, but facing some challenges!
https://github.com/Gamua/Adobe-Runtime-Support/issues/372#issuecomment-662760963

**Comment by marchbold** [comment]
Duplicate
