### ISSUE TITLE
Cannot install app on ios14 beta

### ISSUE THREAD

**Issue by kalashot** [Gamua/Adobe-Runtime-Support#419]
Hi,

I can't install app on ios14 beta 4. Neither via Diawii.com nor via Flashdevelop:

WARNING: could not locate iTunesMetadata.plist in archive!
WARNING: could not locate Payload/Flogger.app/SC_Info/Flogger.sinf in archive!
ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe80
08029: Failed to verify code signature of /var/installd/Library/Caches/com.apple
.mobile.installd.staging/temp.S4oCHg/extracted/Payload/Flogger.app : 0xe8008029
(The code signature version is no longer supported.)

There was no such issue on ios 13.x

Air sdk v 33.1.1.190

**Comment by Dima107** [comment]
We have same issue with 33.1.1.217
Have we any news about this issue?

**Comment by ajwfrost** [comment]
We're investigating this one - a test app that we built here has worked okay so we're wondering if this is related to the certificate used. Is it possible to get your IPA file so that we can analyse it?

thanks

**Comment by marchbold** [comment]
@ajwfrost Which beta version are you using? We did encounter this with the beta 4 as referenced here, but half expected it to be an issue with the beta (as there were a range of issues with it) . I haven't tried the more recent updates as have been tied up on other projects.

**Comment by kalashot** [comment]
Hi @ajwfrost,

Here is the ipa (33.1.1.217) with enterprise provisioning profile: https://app-center.toyota.ru/trade-in-app/ToyotaTradeIn.ipa
You can try to install it from here: https://app-center.toyota.ru/trade-in-app/

Thanks

**Comment by ajwfrost** [comment]
Hi - we've tried with beta 7 and can install our test apps. With your IPA, it installs for us .. but then it crashes. Our apps work fine though.. so this may just be some flakiness with beta 4..?

thanks

**Comment by kalashot** [comment]
Hi.
I've just updated iOS to beta 8. All apps install and run fine. I hope it will be so in the final version.
Thank you very much
