### ISSUE TITLE
Release notes from AIR 33.1.1.217 -  Target SDK Version 28 instead of 29

### ISSUE THREAD

**Issue by luc4smoreira** [Gamua/Adobe-Runtime-Support#426]
This issue is just a documentation inconsistency in release notes

> Section 2.2.3 - Build Environment
> Platform Android, 
> Build Details: Target SDK Version: 28 

It should be 29 as described here:

> Gamua-372:Changing default Android target SDK to 29: this will update generated APK files so that the default targetSdkVersion value is 29

**Comment by rewb0rn** [comment]
After building and uploading an apk to Google Play with Air 33.1.1.217, Google says this is a TargetSDK 28 build. Am I missing something?

**Comment by luc4smoreira** [comment]
To be clear:

![issue-air](https://user-images.githubusercontent.com/9322152/90335382-156ba800-dfab-11ea-968e-0318c1727789.png)


![issue-air2](https://user-images.githubusercontent.com/9322152/90335423-5bc10700-dfab-11ea-8617-d83bf67f3462.png)



![issue-air3](https://user-images.githubusercontent.com/9322152/90335425-5f548e00-dfab-11ea-9261-ac175b36ba55.png)

**Comment by ajwfrost** [comment]
To clarify this: when you build an app using the SDK, the default 'targetSdkVersion' value will be set to 29. However, we've not yet updated the internal build of the AIR SDK to the newest Android SDK, this is currently ongoing..

**Comment by rewb0rn** [comment]
I am confused, does that mean we would target SDK 29 while building with SDK 28? Does the Android SDK support future target versions? It sounds to me like this should break in some way...

**Comment by TobiasHeidingsfeld** [comment]
@ajwfrost Please let us know when the internal build of the AIR SDK to the newest Android SDK is ready and a new AIR SDK can be downloaded including this feature.

**Comment by luc4smoreira** [comment]
The new version AIR 33.1.1.259 fixed it.

![issue-fixed](https://user-images.githubusercontent.com/9322152/94210207-80f73e00-fea4-11ea-9fd4-b9f9846414c3.png)
