### ISSUE TITLE
google play submission main mechanism no longer supported

### ISSUE THREAD

**Issue by ageekhere** [Gamua/Adobe-Runtime-Support#428]
google play submission main mechanism no longer supported

steps followed
1) Create a first APK file for 32-bit ARM (armv7)
2) Update the version number by as small as increment as possible
3) Create a second APK file for 64-bit ARM (armv8)
4) Upload both APK files to the Play Store.

Error
This release is not compliant with the Google Play 64-bit requirement.
The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code: [1001021]
Include 64-bit and 32-bit native code in your app. Use the Android App Bundle publishing format to automatically ensure that each device architecture receives only the native code it needs. This avoids increasing the overall size of your app. Learn More

The Android App Bundle format needs to become the new main mechanism.

**Comment by rewb0rn** [comment]
Hi, we were able to update our apps on Google Play after the deadline. Are you trying to upload an x86? We have removed the x86 build now because they would require x86_64 versions as well, but that is not supported by all ANEs we are using. Meaning we decided to go only with ARM 32 and 64 for now.

**Comment by ageekhere** [comment]
yes i had an x86 build, will try removing it

**Comment by ajwfrost** [comment]
@ageekhere  you can always add in an x64 version as well if you wanted to cover those x86 devices.. not sure how many of these there are, Intel had a big push into Android tablets for the educational market a while ago...
