### ISSUE TITLE
ViewNavigatorApplication missing in Harmon AIR SDK 33.1.1.190 and 33.1.1.217

### ISSUE THREAD

**Issue by PhilCase** [Gamua/Adobe-Runtime-Support#437]
## Problem Description
I've got an app in AIR33.0 that compiles fine.
If I upgrade the AIR SDK to any of the 33.1.1 ones (190 or 217 for instance)

1. I lose access to s|ViewNavigatorApplication.

2. A number of components need their skin defining explicitly (s|ToggleSwitch for instance.
    In addition I'm trying to explicitly set the skin for  s|ViewNavigatorApplication.   (My app runs in a full screen without respecting the iOS "useable window area").

If I look at the libraries that are included by AIR33.0 to AIR 33.1 I can see that the mobilecomponents.swc is missing.   

* Which AIR SDK did you use? Hint: always try the latest version from [Adobe Labs]
   AIR 32.0 - fine.
   AIR 33.0 - fine
   AIR 33.1.1.190 - broken
   AIR 33.1.1.217 - broken

To reproduce.
   Open flashbuilder.
   Set the libraries to 33.1.1.217
   Create a new app for flex mobile.
   Hit "compile"

## Known Workarounds

- missing skins can be included by defining the Skin in the cascading style sheet or the skin class of the element.

I haven't got a fix for the missing ViewNavigatorApplication at this time.   What worked in a simple app doesn't work for the one I need, and creates more errors.

**Comment by ajwfrost** [comment]
Hi
I'm curious - mobilecomponents.swc isn't part of any AIR SDK afaik, that should come from the Flex SDK. I've just checked in AIR 32 (both the normal and Flex versions) from get.adobe.com and these don't contain that library.
It's part of Flex 4.6 SDK though. I'm wondering whether there's been an issue in doing the merge between the Flex SDK and the AIR SDK which means some of the files are missing..?
thanks
  Andrew

**Comment by PhilCase** [comment]
Thanks Andrew.    I think that's it.   I can't get the Flex SDK from Adobe as links to it appear to be dead.   I have recovered a copy of it from the download cache of my AIR update program.    Copying the frameworks folder from over Harmon's update seems to fix that problem.

**Comment by leossmith** [comment]
I am running on Java 1.8.251 and it works without issues. I have a lot of issues with flash builder in the last 2 years so I jumped to intellij which works as should.

**Comment by PhilCase** [comment]
I've fixed it.   I've rebuilt the AIR library, and I've moved to IntelliJ IDEA which handles the build chain for me.
