### ISSUE TITLE
WISH: Desktop extra large (256x256)  icon support

### ISSUE THREAD

**Issue by Oldes** [Gamua/Adobe-Runtime-Support#462]
## Problem Description

It should be possible to include icon of size 256x256 on Windows.
Using `<image256x256>icon_256.png</image256x256>` does not work. It leads to error:
```
application-windows.xml(29): error 103: application.icon.image256x256 is an unexpected element/attribute
```

## Known Workarounds

Use Resource Hacker or similar additional tool to replace icon in the exe file.

**Comment by ajwfrost** [comment]
That seems a no-brainer to add! Am surprised that wasn't already supported...

The above error is easy to get rid of but I'm not sure whether it will then actually work, so we'll need to check on this one...

thanks

**Comment by zwetan** [comment]
2 things
  - [Application icons](https://help.adobe.com/en_US/air/build/WS2d929364fa0b81374fa5df4f129dca62884-8000.html#WS2d929364fa0b81374fa5df4f129dca62884-7ff9) for desktop
  - [Application icons](https://help.adobe.com/en_US/air/build/WSfffb011ac560372f-5d0f4f25128cc9cd0cb-7ffe.html#WS901d38e593cd1bac1e63e3d129907d2886-8000) for mobile

in both case, the doc mention
> If you do not supply an icon of a given size, the next largest size is used and scaled to fit.

side note, you have the same thing for macOS
see [Steps to Post an AIR Application to the Mac App Store](https://helpx.adobe.com/flash-player/kb/posting-air-app-mac-app.html)
> Also add a 512x512 icon to your Icon.icns file. (Currently the adt tool does not support icons of this size on Mac.) You can use Icon Composer (available with the xcode tools) to resize.

technically you could go as far as `1024x1024` from [Apple's Human Interface Guideline](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/)

----

the Icon Handbook has a great [Icon Reference Chart](http://iconhandbook.co.uk/reference/chart/)
for [Mac OS X](http://iconhandbook.co.uk/reference/chart/osx/), [Windows](http://iconhandbook.co.uk/reference/chart/windows/), etc.

**Comment by Adolio** [comment]
@marchbold I think this one is done according to `AIR 33.1.1.300` release notes.

**Comment by marchbold** [comment]
Cheers, will close
