### ISSUE TITLE
IOS 14, Can't visible video at StageVideo.

### ISSUE THREAD

**Issue by zosime** [Gamua/Adobe-Runtime-Support#466]
Hi

Video can't visible often available after iOS 14 updates.
You can reproduce the issue by playing the intro video.

Movie : HLS streaming with Wowza 3.x
RenderMode : gpu
SDK : 33.1.1.98 / 33.1.1.217
Device : iPhone, iPad (IOS 14)
app link : [spekingmax](https://apps.apple.com/kr/app/%EC%8A%A4%ED%94%BC%ED%82%B9%EB%A7%A5%EC%8A%A4-for-iphone/id642372941)

**normal operation NetStatusEvent code :** 
onNetStatus > NetConnection.Connect.Success
onNetStatus > NetStream.Pause.Notify
onNetStatus > NetStream.Play.Start
onNetStatus > NetStream.Unpause.Notify
onNetStatus > NetStream.Buffer.Full

**video is not visible NetStatusEvent code :**
onNetStatus > NetConnection.Connect.Success
onNetStatus > NetStream.Pause.Notify

**Comment by ged-mc** [comment]
We're also seeing a problem with Stage Video on IOS 14  +  AIR 33-11-190  ( Which has worked great since IOS 7 )
It appears the NetStatusEvent - NetStream.Play.Start  event is not firing consistently. We use this event to remove a mask covering the stage video when it starts playing to reveal the video underneath. 

Sometimes stage video displays and sounds as normal ( mask is removed )
Most often we can hear the video but the mask is covering it. I assume it is playing okay under the mask. 
Will update when we confirm.

**Comment by ged-mc** [comment]
On further investigation . . 

STAGEVIDEO is BROKEN on IOS 14  for all AIR 33, AIR 32 and ( I believe ) all previous AIR versions - so this is critical!

It seem that the standard method of Setting up stage video on IOS is not working and the StageVideoAvailabilityEvent.STAGE_VIDEO_AVAILABILITY  events are not firing.  Furthermore the problem is inconsistent so occasionally the events will fire. 

While we wait for this critical issue to be addressed this crude work around should work ( tested for IOS only ):

1) Rather than re-using the StageVideo object. Scrap it and recreate it each time you play a video.
2) Don't rely on Stage video events to fire as expected - rather, set a timer to wait 1s then continue the set up, play video etc

workaround code: 

`protected function resetStageVideo():void{
				nc = null; 
				ns = null;
				sv = null;
				_trace("resetStageVideo")
			}
			
			protected function setUpStageVideo():void
			{
				_trace("setUpStageVideo start")
// scrap any existing Stagevideo object and start fresh every video
				resetStageVideo();
					
				stage.align = StageAlign.TOP_LEFT;
				stage.scaleMode = StageScaleMode.NO_SCALE;
				
				nc = new NetConnection();
				nc.connect(null);
				
				ns = new NetStream(nc);
				
				ns.client = this;
				
				// don't bother with these events - broken in IOS 14 
				//ns.addEventListener(NetStatusEvent.NET_STATUS, onNetStreamStatus);
				//stage.addEventListener(StageVideoAvailabilityEvent.STAGE_VIDEO_AVAILABILITY, onStageVideoAvailable);
				
				_trace("setUpStageVideo done start hope timer")
				
				hopeTimer = new Timer(100, 10)
				hopeTimer.addEventListener(TimerEvent.TIMER_COMPLETE, hopeStageVideoIsAvailable);
				hopeTimer.start();
			}
			
			private var hopeTimer:Timer
			
			
			private function hopeStageVideoIsAvailable(e:TimerEvent):void{
				_trace("hope !!! StageVideoIsAvailable  after a wait "  );
				var point:Point = new Point(  kvidFrame.dummyVideo.x,  kvidFrame.dummyVideo.y);
				//stage.removeEventListener(StageVideoAvailabilityEvent.STAGE_VIDEO_AVAILABILITY, onStageVideoAvailable);
				sv = stage.stageVideos[0];
				sv.attachNetStream(ns);
				sv.addEventListener(StageVideoEvent.RENDER_STATE, onRenderState);
				sv.viewPort = new Rectangle(point.x, point.y, videoWidth, videoHeight);
				//stageVideoSetup = true;
				
				if(ns){
				ns.play(getSourceDef(videoToPlayVid));
				rootApplication.switchAppBgAlphaTransparent(true);
				_trace("Hope play and BG transparent")
				}
				
				kvidFrame.setDummyVideoVisibility(false);
				loadingInProgressSwitch(false)
				
				hopeTimer.stop();
				hopeTimer = null;
			}`

**Comment by ajwfrost** [comment]
Thanks for the workaround which gives us a bit of a hint.. we're investigating!

**Comment by ged-mc** [comment]
Unfortunately the "workaround" in not reliable either however it improves the success rate. 
When successful we always see the onRenderState (= accelerated) event.
When not successful we can still hear the audio.

**Comment by ajwfrost** [comment]
Hi
Can I just query one part of this:
StageVideoAvailability events are not firing

As we're seeing the events being dispatched like normal, consistently, 100% of time (10+ tests)
Using both 33.1.1.259 (forthcoming) and 33.1.1.98, iOS 14.0 on an iPhone 6s, tried renderMode = direct and gpu

This is just in a simple test case:
```
		public function Main() 
		{
			stage.scaleMode = StageScaleMode.NO_SCALE;
			stage.align = StageAlign.TOP_LEFT;
			stage.addEventListener(Event.DEACTIVATE, deactivate);
			
			// touch or gesture?
			Multitouch.inputMode = MultitouchInputMode.TOUCH_POINT;
			
			stage.addEventListener(StageVideoAvailabilityEvent.STAGE_VIDEO_AVAILABILITY, onStageVideoAvailable);
		}
		
		private function onStageVideoAvailable(e : StageVideoAvailabilityEvent) : void
		{
			trace("Stage Video availability -> " + e.availability);
		}

```

If you are trying the same sort of test, do you (a) get no event dispatched, or (b) get no availability?

thanks

**Comment by ged-mc** [comment]
We're using Flex mobile with AIR 33.1.1.190

We're seeing the following events fire ( in reverse order ) :

**Video fails - audio only **

(trace end)

rootApplication.switchAppBgAlpha
ns.play
sv.viewPort
sv.addEventListener StageVideoEvent.RENDER_STATE
sv.attachNetStream(ns)
sv = stage.stageVideos[0]
removeEventListener StageVideoAvailabilityEvent
stage video is available
StageVideoAvailabilityEvent = available
setUpStageVideo started 
trace start


**And Video successful**

**NetStatusEvent = NetStream.Buffer.Full
NetStatusEvent = NetStream.Play.Start
StageVideoEvent Render Status = accelerated**
rootApplication.switchAppBgAlpha
ns.play
sv.viewPort
sv.addEventListener StageVideoEvent.RENDER_STATE
sv.attachNetStream(ns)
sv = stage.stageVideos[0]
removeEventListener StageVideoAvailabilityEvent
stage video is available
StageVideoAvailabilityEvent = available
setUpStageVideo started 

trace start 

So the difference between success and fail is **not StageVideoAvailability** but getting events back from the netStream and the StageVideoEvent Render Status = accelerated:

NetStatusEvent = NetStream.Buffer.Full
NetStatusEvent = NetStream.Play.Start
StageVideoEvent Render Status = accelerated

Here's the code:


`	protected function setUpStageVideo():void
			{
				_trace("setUpStageVideo started ")
				
				stage.align = StageAlign.TOP_LEFT;
				stage.scaleMode = StageScaleMode.NO_SCALE;
				
				nc = new NetConnection();
				nc.connect(null);
				
				ns = new NetStream(nc);
				
				ns.client = this;
				ns.addEventListener(NetStatusEvent.NET_STATUS, onNetStreamStatus);
				stage.addEventListener(StageVideoAvailabilityEvent.STAGE_VIDEO_AVAILABILITY, onStageVideoAvailable);
				
			}
			
			protected function onStageVideoAvailable(event:StageVideoAvailabilityEvent):void
			{
				_trace( "StageVideoAvailabilityEvent = " + event.availability );
				var point:Point = new Point(  kvidFrame.dummyVideo.x,  kvidFrame.dummyVideo.y);

				if (event.availability == "available")
				{
					_trace("stage video is available"  );
					
					stage.removeEventListener(StageVideoAvailabilityEvent.STAGE_VIDEO_AVAILABILITY, onStageVideoAvailable);
					_trace("removeEventListener StageVideoAvailabilityEvent")
					sv = stage.stageVideos[0];
					_trace("sv = stage.stageVideos[0]")
					sv.attachNetStream(ns);
					_trace("sv.attachNetStream(ns)")
					sv.addEventListener(StageVideoEvent.RENDER_STATE, onRenderState);
					_trace("sv.addEventListener StageVideoEvent.RENDER_STATE")
					sv.viewPort = new Rectangle(point.x, point.y, videoWidth, videoHeight);
					_trace("sv.viewPort")
					stageVideoSetup = true;
					if(ns){
						ns.play(getSourceDef(videoToPlayVid));
						_trace("ns.play")
						rootApplication.switchAppBgAlphaTransparent(true);
						_trace("rootApplication.switchAppBgAlpha")
					}else{
						_trace("NetStream is null")
					}
				}   
				else{
					_trace("stage video is not available"  ) 
					
				}
			}
			
			private function onNetStreamStatus(event:NetStatusEvent):void
			{
				var info:Object = event.info;
				_trace( "NetStatusEvent = "+ info.code)
				
				switch (info.code)
				{
					case "NetStream.Play.Start":
						
						//ns.seek(0);
						kvidFrame.setDummyVideoVisibility(false);
						//loadingInProgress = false;
						loadingInProgressSwitch(false)
						break;
					case "NetStream.Play.Stop":
						//ns.seek(0);
						kvidFrame.setDummyVideoVisibility(true);
						if(!loadingInProgress){
							// video is complete go back
							goVideoBack()
						}
						break;
					
					case "NetStream.Buffer.Full":
						kvidFrame.setDummyVideoVisibility(false);
						break;
				}
				
			}
			
			public function onMetaData(obj:Object):void
			{
				//var info:Object = obj
				
			}
			
			public function onPlayStatus(obj:Object):void
			{
				_trace( "onPlayStatus = "+ obj.code)
				
				if(obj.code == 'NetStream.Play.Complete'){
					kvidFrame.setDummyVideoVisibility(true);
				}
			}
			
			public function onXMPData(obj:Object):void
			{
				
			} 
			
			private function getSourceDef(v:VideoVO):String{
				
				var src:String = v.sourceHLS;
				
				return src;
				
			}
			
			
			protected function onRenderState(event:StageVideoEvent):void
			{
				_trace("StageVideoEvent Render Status = " + event.status );
			}
`

**Comment by ged-mc** [comment]
There's also a possibility Apple have messed up HLS:
[New low latency HLS in IOS 14 ](https://developer.apple.com/videos/play/wwdc2020/10228/)
[HLS Streaming issues only on iOS 14](https://developer.apple.com/forums/thread/660999)

**Comment by ajwfrost** [comment]
Interesting! thanks - so that explains perhaps why our local file playback case was working...
Will take a look at how AIR does the HLS stuff, in case we can find a workaround..

**Comment by ajwfrost** [comment]
FYI we have a patch available for this, then hopefully we will have a release out in the next week or two with a lot of other fixes that will put this into a formal build...
https://transfer.harman.com/message/LPi44JEls6fcgxH9N1NJ2U

thanks

**Comment by ged-mc** [comment]
Patch did the trick. Thank you very much for the quick fix!

**Comment by ged-mc** [comment]
With further testing . . .

Using the patched AIR SDK on IOS14 were getting a crash as follows:

AIR 33-11-259 ( patched ) on IOS14 = Stagevideo okay.  App crashes at different points - even without Stagevideo played during the test session. No actionscript errors or useful debug info seen before sudden & complete crash.

AIR 33-11-259 ( without patch) on IOS14 = No crashes (but stagevideo problem)

We're using Air sdk overlaid onto Flex mobile. App crashes are rare.
