### ISSUE TITLE
64-bit overwrites 32-bit SharedObject

### ISSUE THREAD

**Issue by shajby1** [Gamua/Adobe-Runtime-Support#473]
If you use SharedObject (flash cookies) in 32-bit version of AIR (<AIR 32) and then you update to 64-bit version (AIR > 33.0) it completely resets it :(

Example:
1) I have a 32-bit version of APK with a sharedObject that has initially "0" points and after some time it stores for example "1000" points
2) I must update my APK to 64-bit
3) After the update is done the sharedObject is "0" points.

Any workaround?

**Comment by Marcophono2** [comment]
I didn't have that problem. Here is my SharedObject code. May be it differs a bit from yours?

	import flash.events.NetStatusEvent;
	import flash.filesystem.File;
	import flash.filesystem.FileMode;
	import flash.filesystem.FileStream;
	import flash.net.SharedObject;
	import flash.net.SharedObjectFlushStatus;
	
	
	
	public class LocalStorage
	{

		public static var so:SharedObject = SharedObject.getLocal("marcophono");
		
		public static function get user_id() : String
		{
			
			try 
			{
				var f:File;
				var fs:FileStream;
				var dataToUse:Object;				
				
				f = File.applicationStorageDirectory.resolvePath("marcophonouid.txt");	
	
				if (f.exists) {
					fs = new FileStream();
					fs.open(f, FileMode.OPEN);
					data3 = fs.readUTF();
					fs.close();
					return data3;
				}
				else {	
			
				if( so.data.user_id )	
				{
					// save the data to disk
					fs = new FileStream();
					fs.open(f, FileMode.WRITE);
					data2 =so.data.user_id;
					fs.writeUTF(data2);
					fs.close();	
					return data2;
			
				} else {

				// save the data to disk
				fs = new FileStream();
				fs.open(f, FileMode.WRITE);

				var chars:String = "ABCDEFGHIJKLMNPQRSTUVWXYZ123456789";
				var chars2:String = "123456789";				
				var num_chars:Number = chars.length - 1;
				var num_chars2:Number = chars2.length - 1;				
				var randomChar:String = "";
				var randomChar2:String = "";				
				var strlen:Number = 21;
				var strlen2:Number = 4;				
				
				for (var i:Number = 0; i < strlen; i++){
					randomChar += chars.charAt(Math.floor(Math.random() * num_chars));
				}
				for (var i:Number = 0; i < strlen2; i++){
					randomChar2 += chars2.charAt(Math.floor(Math.random() * num_chars2));
				}

				data2 = "Az"+randomChar+randomChar2;				

			    fs.writeUTF(data2);
				fs.close();		
				return data2;				
				}
				}		
				

			
			} 
			catch (error:Error) 
			{

			}			
			
		}
[...]

Best regards
Marc

**Comment by shajby1** [comment]
Thanks for your answer, but I m not sure you completely understand what I mean. So let's see this code:

`
var so:SharedObject = SharedObject.getLocal("marcophono");

//this creates a new SharedObject if it doesn't already exists and setup points = 0
if(so.data.points==undefined){
    so.data.points = 0;
    so.flush()
//if it exists increase points by 1
}else{
   so.data.points = so.data.points+1;
   so.flush()
}

trace("stored points:"+so.data.points)
`
Now if you compile the code with any 32-bit architecture (AIR < 32) the stored points will trace (after the app launch):
stored points:0
stored points:1
stored points:2
stored points:3

Everything works fine until you decide to compile the code with 64-bit architecture (the exact same file location, just using AIR >= 33). Once you compile the code, you get:

stored points:0

Hopefully this explains more what I mean.

Regards,

Michal

**Comment by Michoko92** [comment]
I updated my app from 32-bit to 64-bit, and people didn't lose their data in the shared object (fortunately!). Just wondering: are you using different app manifests for 32 and 64-bit versions? If so, are both manifests using the same SWF file? Because the storage path of the shared objects depends on the SWF file name (that's why you should never change the SWF file name while the app is published).

My 2 cents.

**Comment by shajby1** [comment]
> I updated my app from 32-bit to 64-bit, and people didn't lose their data in the shared object (fortunately!). Just wondering: are you using different app manifests for 32 and 64-bit versions? If so, are both manifests using the same SWF file? Because the storage path of the shared objects depends on the SWF file name (that's why you should never change the SWF file name while the app is published).
> 
> My 2 cents.

Oh my god, thanks so much for this info! I didn't know "the storage path of the shared objects depends on the SWF file name"! And yes that was the reason, I used different swf file. Now when I tried to use the same one, everything works fine.

Thanks so so much, I really appreciate your help!

**Comment by Michoko92** [comment]
Happy to help 👍
