### ISSUE TITLE
[feature request] Supporting bigger icon sizes for desktop apps

### ISSUE THREAD

**Issue by myflashlab** [Gamua/Adobe-Runtime-Support#475]
This is a very old issue which does not seem to be addressed before https://tracker.adobe.com/#/view/AIR-3844899
That would be nice to support bigger icons for desktop apps. currently, the app icons does not look very nice as 128x128 is the biggest one supported right now.

```
            <icon>
                <image16x16>icons/16.png</image16x16>
                <image32x32>icons/32.png</image32x32>
                <image48x48>icons/48.png</image48x48>
                <image128x128>icons/128.png</image128x128>
            </icon>
```

Would it be easy to support higher resolutions?

**Comment by Oldes** [comment]
Related to: https://github.com/Gamua/Adobe-Runtime-Support/issues/462
