### ISSUE TITLE
Windows: Add way to ignore DPI scaling

### ISSUE THREAD

**Issue by Adolio** [Gamua/Adobe-Runtime-Support#483]
## Problem Description

Windows DPI Scaling badly affects the rendering resolution even in fullscreen mode (through `StageDisplayState.FULL_SCREEN_INTERACTIVE`).

If possible it would be really nice to have a way to disable it directly from the application itself.

Here are few solutions ideas:

## 1. Add new content for `requestedDisplayResolution` in `application.xml`

Maybe something like:

```
<initialWindow>
    <requestedDisplayResolution>full</requestedDisplayResolution>
</initialWindow>
```

## 2. Add new entry for `initialWindow` in `application.xml`

Maybe something like:

```
<initialWindow>
    <dpiScaling>ignore</dpiScaling>
</initialWindow>
```

## 3. Add Exclusive Fullscreen Mode with actual screen resolution

See https://github.com/Gamua/Adobe-Runtime-Support/issues/441

## Steps to Reproduce

I have made this tiny project to illustrate the issue with my configuration: https://github.com/Adolio/Adobe-AIR-DPI-Scaling

Here are my scenarios:

### DPI of 100%: Everything is alright

DPI Scaling: 100%
Screen Resolution: 2560x1440
Application Fullscreen Resolution: 2560x1440

![2560x1440](https://user-images.githubusercontent.com/1126990/94705367-40cf0a00-0341-11eb-944f-8a8729559777.png)

### DPI of 225%: Fullscreen resolution is affected

DPI Scaling: 225%
Screen Resolution: 2560x1440
Application Fullscreen Resolution: **1138x640**

![1138x640](https://user-images.githubusercontent.com/1126990/94705519-707e1200-0341-11eb-93f8-be64bb78cc5d.png)

The `Content Scale Factor` is however correct but useless since I cannot render more pixels than the fullscreen resolution.

## Known Workarounds

I tried several things to overcome this issue and I didn't found a acceptable way to solve it.

### 1. Ask user to set DPI scaling to 100%

Display Settings > Scale and layout > 100%

![ScalingAndLayout](https://user-images.githubusercontent.com/1126990/94706404-70cadd00-0342-11eb-88f9-0c86e5fc95a7.PNG)

👉 This solution is not acceptable because it requires user to modify his / her computer configuration.

### 2. Override DPI scaling for the distributed executable

Application Properties > Compatibility Tab > Change high DPI settings > High DPI scaling override > Application

![adl](https://user-images.githubusercontent.com/1126990/94706368-6577b180-0342-11eb-8fe4-39fb5e4883b5.png)
(example with adl64.exe but the package app should be used)

👉 This solution is not acceptable because the information is not stored in the executable itself. As soon as the file is copied or moved the configuration is lost.

**Comment by Adolio** [comment]
This is actually not an issue in Adobe AIR.

To solve this, two things are required:
  
1. Add `<requestedDisplayResolution>high</requestedDisplayResolution>` in the `application.xml`
2. Enable support of high resolutions in `Starling` through `Starling::supportHighResolutions`

**Comment by Fancy2209** [comment]
I am facing this issue and the framework I am using is Away3D and not Starling, any suggestions?
