### ISSUE TITLE
Air 33.1.1.259: antiAlias crashes Windows application

### ISSUE THREAD

**Issue by spielepalast** [Gamua/Adobe-Runtime-Support#484]
## Problem Description

We have a simple Away3D scene in our games (cards, table, Skybox). Using Air SDK 33.1.1.259 or Air SDK 33.1.1.217 will cause the application to crash the first time `_view.render()` is called with any antiAlias value other than 0.

Target platform is Windows 32, the crash happens both in ADL and the generated .exe file.

Using Air 32.0.0.116, the application runs without crash.

## Steps to Reproduce

Here is a simplified example code:

```
var profile:Context3DProfile = highQuality ? Context3DProfile.BASELINE_EXTENDED : Context3DProfile.BASELINE;
_view = new View3D(null, null, null, false, profile);
_view.antiAlias = 4;

// .... Set up scene 

_view.render();
```

Here is the output from Windows Event Viewer for a crash with ADL:

```
Faulting application name: adl.exe, version: 33.1.1.259, time stamp: 0x5f6206a9
Faulting module name: d3d11.dll, version: 10.0.19041.1, time stamp: 0x9edbf96b
Exception code: 0xc0000005
Fault offset: 0x00171fc5
Faulting process id: 0x40d0
Faulting application start time: 0x01d697d817d51ac3
Faulting application path: D:\Air\33.1.1.259\bin\adl.exe
Faulting module path: C:\WINDOWS\system32\d3d11.dll
Report Id: 2776311d-82cc-4b66-9418-929775b2a77e
Faulting package full name: 
Faulting package-relative application ID: 
```

## Known Workarounds

Use Air SDK 32.0.0.116 or set `_view.antiAlias = 0;`

Let me know if you need more info!

**Comment by ajwfrost** [comment]
I suspect this is the same problem as in #436 - we had a bugfix around GPU memory usage which caused a regression due to a double-release... if you can grab the updated AIR DLL from the below comment, it may fix the problem?
https://github.com/Gamua/Adobe-Runtime-Support/issues/436#issuecomment-700433056

thanks

**Comment by spielepalast** [comment]
This fixes the problem, very nice, thanks :)
