### ISSUE TITLE
Unable to build Android 64 bit (-arch armv8) apk with Air 33.1.1.xx in Flashbuilder 4.7

### ISSUE THREAD

**Issue by dmitrydmsk** [Gamua/Adobe-Runtime-Support#496]
Project build completed sucssesfully and working fine with for 32 bit mode with AIR 32, 33.1.1.98, 33.1.1.259. It also build and working fine for IOS with AIR33.1.1.98 But when trying to build 64 bit, i add parameter '-arch' 'armv8' after '-target' options (before '-storetype') in Customize Launch exactly as noted in AIRSDK release notes, android version i have an error:

Error occured while packaging the application:
Cannot run program "java.exe" (in directory "D:\Projects\Flash\LiteM64\bin-release-temp"): 

CreateProcess error=206, The filename or extension is too long

I read notes about issue in release notes (https://forums.adobe.com/thread/1505072) where discussed this error, and tried workaround - make shorter path names, but this didnt help. As i understand this error have something with limitation of command arguments for java.exe. So I tried to remove recources - images and other files to check if it help - in this case there is no error message, but process never completed. Flash Builder looks like doing nothing with message: 

Exporting release build: Packaging for Google Android platform

Flash Builder itself didnt hangup - click on stop button (red cquare) just cancel process.

I tried to use windows command shell with the script, which i get from "Customize Launch\Show Command". First error was about missing some file, there was no file name in message. Inspecting script i decided to use quotas for path to adt.jar, since path have space symbols, but this path was not quoted, so i make start of command like:

java.exe -jar "D:\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\lib\adt.jar"...

After this i got another error about missing files, but in this case the name of the file was displayed and it was clear what name is clamped (missing several last symbols). Reducing number of files in command help me to generate apk file and inside i saw a directory arm64-v8a, which i think verified succsesfull build for 64bit, but this apk is incomplete. 

Also there was many errors with command line build until i completely switch off all extension, but for now more important to have solution and just to build full application.

I read about command line arguments limit on Win7 and, if there is no workaround, look like its pointless to move in this direction since i have 44461 symbols just in names of files. Also i see what java add a path to each file when making error message, so it is possible what arguments length can be bigger than that number.

I cannot understand - if problem is in command line buffer legnth, why 32bit application builded just fine (with all AIR SDK version and for IOS also)?

Is there a way to fix this problem and build 64 bit apk either with flash builder or somehow else? Please help.

AIRSDK: 33.1.1.98, 33.1.1.259
WIN7 64 Pro
FlashBuilder 4.7 Prem or Command line
Link to simular problem on adobe tracker https://forums.adobe.com/thread/1505072 
Reproduced always - with all ANE removed

**Comment by ajwfrost** [comment]
Hi

We've got a way to output the command lines that are used internally by ADT, so are you able to try this please:
1) Edit the file 'adt.cfg' which should be in the SDK's "lib" folder alongside adt.jar
2) Add a line to this: "DebugOut=true"
3) Run this again...
4) Now look at a file that is created: c:\users\[username]\adt.log, and send us the contents.

thanks

**Comment by dmitrydmsk** [comment]
Hello, and thank for you reply!
After enabling adt log i somehow managed to build 64bit apk without resources and ane - armv8-64 directory now present in apk. Probably i didnt clear up all ane and lost in different attempts. Log show 'Setting architecture to: armv8' (i used -arch param) and apk generated. But i cannot build apk with resources - looks like in this case (with resources) build not even started because there is no log file in this case (if log deleted before build) or no new record in log (if log exist) and i got same error message:

Error occured while packaging the application:
Cannot run program "java.exe" (in directory "D:\a\bin-release-temp"):

**Comment by dmitrydmsk** [comment]
Since building full project do not work for 64bit case i make a 64 bit build with small amount of resources and then build 32 bit with full resources. I attach adt.log file for these two builds (i formatted text a little, just few CR to see the difference). Visible difference is:
after "Called by: D:\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\lib\adt.jar"

64 bit have a two text outputs, which not present in 32 bit log:

"ADT called with: -package -target apk-captive-runtime -arch armv8 -storetype pkcs12 -keystore D:\c\c.p12 -storepass xxxx d:\a\a64.apk b-app.xml b.swf icons\icon_aquantika_144.png icons\icon_aquantika_192.png icons\icon_aquantika_32.png 
icons\icon_aquantika_48.png icons\icon_aquantika_512.png icons\icon_aquantika_72.png icons\icon_aquantika_96.png icons\icon_aquantika_v2.png icons\icon_aquantika_v2_512.png icons\icon_aquantika_v2_96.png"

AND

"Setting architecture to: armv8"

(I masked password by xxxx)

 32 bit have one text output instead these two in 64 bit:

"APK Packager entry point"

Then goes last text which look simular for both builds:

"AAPT command line: D:\Adobe\Adobe Flash Builder 4.7...."

Looks like 64bit version called adt with full list of project files as parameter, but 32 bit version somehow go without that call.
Maybe this be the problem?
[adtlog_comented.txt](https://github.com/Gamua/Adobe-Runtime-Support/files/5390282/adtlog_comented.txt)

**Comment by ajwfrost** [comment]
So this is interesting: the fact you've got a difference in the two log files where the ARMv8 one says:
`ADT called with: ...`
makes it clear that whilst Flash Builder is "cheating" with the 32-bit builds, it's just calling via the command line for a 64-bit build. Not entirely sure why it's doing this differently, but for 32-bit it's not calling ADT as a normal Java application, instead it's loading in the jar file directly to run it.  (In case you want the details, that 'ADT called with' trace is in the static `main` function, so the fact we don't see it means that we're not being called from the 'java.exe' launcher...)

The `Called by` line that comes out first happens in the initialisation of the log file. So if it's using Java to kick off the 64-bit build, then we should see `Called by...` followed by `ADT called with...` and then `Setting architecture...` which is in the command-line parsing (the 32-bit variant doesn't use the command line..).

The fact it's not getting anything out means that the Java command that's got too long a line is actually the call to ADT: so Flash Builder will be doing (in your 64-bit successful case):
```
java.exe -jar "D:\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\lib\adt.jar" -package -target apk-captive-runtime -arch armv8 -storetype pkcs12 -keystore D:\c\c.p12 -storepass xxxx d:\a\a64.apk b-app.xml b.swf icons\icon_aquantika_144.png icons\icon_aquantika_192.png icons\icon_aquantika_32.png icons\icon_aquantika_48.png icons\icon_aquantika_512.png icons\icon_aquantika_72.png icons\icon_aquantika_96.png icons\icon_aquantika_v2.png icons\icon_aquantika_v2_512.png icons\icon_aquantika_v2_96.png
```

and it's this line that then gets too long...! If you have any way you can shorten it, it would be good. For example with those icons, you could do `"-C icons ."` perhaps?

**Comment by dmitrydmsk** [comment]
Hello
i tried several combinations to supply directory name, but without luck.
In case of [-C icons .] build processed succesfully and apk generated, but it doesnt contain folder with files. Here the adtlog param string:

"*** ADT Logging at 2020/10/16 15:53:18 ***
Called by: D:\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\lib\adt.jar
ADT called with: -package -target apk-captive-runtime -arch armv8 -storetype pkcs12 -keystore D:\c\c.p12 -storepass xxxx D:\Aquantika64.apk LiteM64-app.xml LiteM64.swf -C icons . -extdir D:\Projects\Flash\.metadata\.plugins\com.adobe.flexbuilder.project.ui\ANEFiles\LiteM64\com.adobe.flexide.multiplatform.android.platform
Setting architecture to: armv8
AAPT command line: D:\Adobe\..."

In other attemps there was errors, which identify what if i for example, choose to add just "icons" - this is how FB did for IOS in CustomizeLaunch - in case of Android build "icons" expanded to full path and then goes error:

Parameters preview in Customize Launch looks:
"java.exe -jar D:\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\lib\adt.jar -package -target apk-captive-runtime -arch armv8 -storetype pkcs12 -keystore D:\c\c.p12 -storepass <Value cannot be displayed> D:\Aquantika64.apk LiteM64-app.xml LiteM64.swf D:\Projects\Flash\LiteM64\src\icons -extdir D:\Projects\Flash\.metadata\.plugins\com.adobe.flexbuilder.project.ui\ANEFiles\LiteM64\com.adobe.flexide.multiplatform.android.platform"

Error:
"Error occurred while packaging the application:
File D:\Projects\Flash\LiteM64\src\icons\icon_aquantika_144.png is not relative to directory D:\Projects\Flash\LiteM64\bin-release-temp"

Same error in adtlog:
"UsageError: File D:\Projects\Flash\LiteM64\src\icons\icon_aquantika_144.png is not relative to directory D:\Projects\Flash\LiteM64\bin-release-temp"

If i try to 'trick' FlashBuilder and add " icons" with space to swf file parameter:
Preview:
"java.exe -jar D:\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\lib\adt.jar -package -target apk-captive-runtime -arch armv8 -storetype pkcs12 -keystore D:\c\c.p12 -storepass <Value cannot be displayed> D:\Aquantika64.apk LiteM64-app.xml LiteM64.swf icons -extdir D:\Projects\Flash\.metadata\.plugins\com.adobe.flexbuilder.project.ui\ANEFiles\LiteM64\com.adobe.flexide.multiplatform.android.platform"

got error:

"Error occurred while packaging the application:
no such file D:\Projects\Flash\LiteM64\bin-release-temp\LiteM64.swf icons"
same in adtlog:
"*** ADT Logging at 2020/10/16 16:17:42 ***
Called by: D:\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\lib\adt.jar
ADT called with: -package -target apk-captive-runtime -arch armv8 -storetype pkcs12 -keystore D:\c\c.p12 -storepass xxxx D:\Aquantika64.apk LiteM64-app.xml LiteM64.swf icons -extdir D:\Projects\Flash\.metadata\.plugins\com.adobe.flexbuilder.project.ui\ANEFiles\LiteM64\com.adobe.flexide.multiplatform.android.platform
Setting architecture to: armv8
UsageError: no such file D:\Projects\Flash\LiteM64\bin-release-temp\LiteM64.swf icons"

And this is very strange - somehow parameters divided by space character still counted as a file path.

Renaming about 1200 files, where names have a meaning and also recorded manually in xml file (kind of database)  to something like numbers looks like a very hard solution.

Is text in adt log adter "ADT called with:..." really shows real arguments line?
Is there any ideas what else i can try?
