### ISSUE TITLE
compc using Java 1.8.0_261 Embed font compilation error

### ISSUE THREAD

**Issue by pol2095** [Gamua/Adobe-Runtime-Support#499]
## Problem Description

Hello,

compc return an error message when I embed a font using the last Java 1.8.0_261

```
package
{
	public class MainSwc
	{
		[Embed(source="SourceSansPro-Regular.ttf",fontFamily="SourceSansPro",fontWeight="normal",mimeType="application/x-font",embedAsCFF="true")]
		protected static const SOURCE_SANS_PRO_REGULAR:Class;
	}
}
```

I have this message error : 

> Internal error : java.lang.NullPointerException
>         at com.adobe.flash.swf.SWF.addFrame(SWF.java:91)
>         at com.adobe.flash.compiler.internal.targets.SWFTarget$FramesInformation.createFrames(SWFTarget.java:876)
>         at com.adobe.flash.compiler.internal.targets.SWFTarget.build(SWFTarget.java:243)
>         at com.adobe.flash.compiler.internal.targets.SWCTarget.buildLibrarySWF(SWCTarget.java:348)
>         at com.adobe.flash.compiler.internal.targets.SWCTarget.build(SWCTarget.java:128)
>         at com.adobe.flash.compiler.clients.COMPC.buildArtifact(COMPC.java:144)
>         at com.adobe.flash.compiler.clients.MXMLC.compile(MXMLC.java:553)
>         at com.adobe.flash.compiler.clients.MXMLC.mainNoExit(MXMLC.java:242)
>         at com.adobe.flash.compiler.clients.MXMLC.mainNoExit(MXMLC.java:196)
>         at com.adobe.flash.compiler.clients.COMPC.staticMainNoExit(COMPC.java:75)
>         at com.adobe.flash.compiler.clients.COMPC.main(COMPC.java:62)

* AIR SDK 33.1.1.259
* Windows 10

## Steps to Reproduce

> compc -include-sources source -source-path source -output MainSwc.swc

same issue using mxmlc

## Known Workarounds

it work when I use an older version of Java 1.8.0_66

Thanks

**Comment by pol2095** [comment]
It's impossible to compile Feathers [theme](https://github.com/BowlerHatLLC/feathersui-starling/tree/master/themes/MetalWorksDesktopTheme) using Java 1.8.0_261 on Windows, thanks.

**Comment by joshtynjala** [comment]
I can reproduce with Java 8.0.282. It worked again after I upgraded to Java 11, in case that helps anyone with the same issue.
