### ISSUE TITLE
if i use air33 release chinses name app to ios , the name will be garbled , who can help me

### ISSUE THREAD

**Issue by ifczt** [Gamua/Adobe-Runtime-Support#500]
air sdk is air 33.1.1.259

**Comment by ajwfrost** [comment]
Can you please confirm what values you're using in your application descriptor XML file please? or what process/IDE you're using for building the application?

We had an update a while ago that should have helped with this: #331 
so if you're able to provide more details on what you're using and what is then being generated, we can investigate further.

thanks

**Comment by ifczt** [comment]
> 您能否确定在应用程序描述符XML文件中使用的值是什么？或用于构建应用程序的过程/ IDE？
> 
> 一段时间之前，我们进行了一次更新，应该对此有所帮助：[＃331，](https://github.com/Gamua/Adobe-Runtime-Support/issues/331)
> 因此，如果您能够提供有关正在使用的内容以及生成的内容的更多详细信息，我们可以进行进一步调查。
> 
> 谢谢

<?xml version="1.0" encoding="utf-8"?>
<application xmlns="http://ns.adobe.com/air/application/33.1">
  <id>com.damou.mznxt</id>
  <versionNumber>0.7.2</versionNumber>
  <supportedProfiles>mobileDevice</supportedProfiles>
  <filename>智能学堂初中版</filename>
  <name>
    智能学堂初中版
  </name>
  <android>
    <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
	<uses-sdk android:minSdkVersion="8" />
	<uses-permission android:name="android.permission.RECORD_AUDIO" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.VIBRATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.READ_PHONE_STATE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<application>
		<activity android:name="air.com.damou.mznxt.wxapi.WXEntryActivity" android:exported="true"></activity>
		<activity android:name="air.com.damou.mznxt.wxapi.WXPayEntryActivity" android:exported="true"></activity>
	</application>
	<application android:enabled="true">
		<activity android:name="com.alipay.sdk.app.H5PayActivity" android:configChanges="orientation|keyboardHidden|navigation" android:exported="false" android:screenOrientation="behind"></activity>
		<activity android:name="com.alipay.sdk.auth.AuthActivity" android:configChanges="orientation|keyboardHidden|navigation" android:exported="false" android:screenOrientation="behind"></activity>
	</application>
	
	
	<uses-permission android:name="android.permission.INTERNET" />
	
	
	<uses-permission android:name="android.permission.DISABLE_KEYGUARD" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
</manifest>]]></manifestAdditions>
    <colorDepth>32bit</colorDepth>
  </android>
  <iPhone>
    <InfoAdditions><![CDATA[<key>LSApplicationQueriesSchemes</key>
<array>
	<string>wechat</string>
	<string>weixin</string>
</array>
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true />
</dict>
<key>NSMicrophoneUsageDescription</key>
<string>Microphone required</string>
<key>UIStatusBarStyle</key>
<string>UIStatusBarStyleBlackOpaque</string>
<key>UIRequiresPersistentWiFi</key>
<string>NO</string>

<key>CFBundleIconName</key>
<string>AppIcon</string>
<key>UIDeviceFamily</key>
<array>
	<string>1</string>
	<string>2</string>
</array>
<key>MinimumOSVersion</key>
<string>8.0</string>
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>mznxt</string>
		</array>
		<key>CFBundleURLName</key>
		<string>com.damou.mznxt</string>
	</dict>
	<dict>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>wx96c46d2a21078f13</string>
		</array>
		<key>CFBundleURLName</key>
		<string>weixin</string>
	</dict>
</array>
]]></InfoAdditions>
    <requestedDisplayResolution>high</requestedDisplayResolution>
  </iPhone>
  <initialWindow>
    <title>智能学堂初中版</title>
    <content>zn.swf</content>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    
    
    <renderMode>direct</renderMode>
    
    
    <aspectRatio>landscape</aspectRatio>
    <systemChrome>standard</systemChrome>
    <autoOrients>true</autoOrients>
    <softKeyboardBehavior>pan</softKeyboardBehavior>
    <requestedDisplayResolution>high</requestedDisplayResolution>
    <depthAndStencil>true</depthAndStencil>
  </initialWindow>
  <icon>
    <image48x48>icons/icon_48.png</image48x48>
    <image57x57>icons/icon_57.png</image57x57>
    
    <image72x72>icons/icon_72.png</image72x72>
    <image76x76>icons/icon_76.png</image76x76>
    <image96x96>icons/icon_96.png</image96x96>
    <image114x114>icons/icon_114.png</image114x114>
    <image120x120>icons/icon_120.png</image120x120>
    <image144x144>icons/icon_144.png</image144x144>
    <image152x152>icons/icon_152.png</image152x152>
    <image36x36>icons/icon_36.png</image36x36>
    <image16x16>icons/icon_16.png</image16x16>
    <image512x512>icons/icon_512.png</image512x512>
    
    <image29x29>icons/icon_29.png</image29x29>
    <image32x32>icons/icon_32.png</image32x32>
    <image40x40>icons/icon_40.png</image40x40>
    <image50x50>icons/icon_50.png</image50x50>
    <image58x58>icons/icon_58.png</image58x58>
    <image80x80>icons/icon_80.png</image80x80>
    <image87x87>icons/icon_87.png</image87x87>
	<image167x167>icons/icon_167.png</image167x167>
    <image100x100>icons/icon_100.png</image100x100>
    <image128x128>icons/icon_128.png</image128x128>
    <image180x180>icons/icon_180.png</image180x180>
    
  </icon>
  
  <description>
    <text xml:lang="zh">
    </text>
  </description>
  <supportedLanguages>zh</supportedLanguages>
  <copyright>2017 Damou Technology Co., Ltd.</copyright>
 
</application>
Thank you very much for your answer

**Comment by ifczt** [comment]
> Can you please confirm what values you're using in your application descriptor XML file please? or what process/IDE you're using for building the application?
> 
> We had an update a while ago that should have helped with this: #331
> so if you're able to provide more details on what you're using and what is then being generated, we can investigate further.
> 
> thanks

Thank you very much for your answer
`
<?xml version="1.0" encoding="utf-8"?>
<application xmlns="http://ns.adobe.com/air/application/33.1">
  <id>com.damou.mznxt</id>
  <versionNumber>0.7.2</versionNumber>
  <supportedProfiles>mobileDevice</supportedProfiles>
  <filename>智能学堂初中版</filename>
  <name>
    智能学堂初中版
  </name>
  <android>
    <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
	<uses-sdk android:minSdkVersion="8" />
	<uses-permission android:name="android.permission.RECORD_AUDIO" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.VIBRATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.READ_PHONE_STATE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<application>
		<activity android:name="air.com.damou.mznxt.wxapi.WXEntryActivity" android:exported="true"></activity>
		<activity android:name="air.com.damou.mznxt.wxapi.WXPayEntryActivity" android:exported="true"></activity>
	</application>
	<application android:enabled="true">
		<activity android:name="com.alipay.sdk.app.H5PayActivity" android:configChanges="orientation|keyboardHidden|navigation" android:exported="false" android:screenOrientation="behind"></activity>
		<activity android:name="com.alipay.sdk.auth.AuthActivity" android:configChanges="orientation|keyboardHidden|navigation" android:exported="false" android:screenOrientation="behind"></activity>
	</application>
	
	
	<uses-permission android:name="android.permission.INTERNET" />
	
	
	<uses-permission android:name="android.permission.DISABLE_KEYGUARD" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
</manifest>]]></manifestAdditions>
    <colorDepth>32bit</colorDepth>
  </android>
  <iPhone>
    <InfoAdditions><![CDATA[<key>LSApplicationQueriesSchemes</key>
<array>
	<string>wechat</string>
	<string>weixin</string>
</array>
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true />
</dict>
<key>NSMicrophoneUsageDescription</key>
<string>Microphone required</string>
<key>UIStatusBarStyle</key>
<string>UIStatusBarStyleBlackOpaque</string>
<key>UIRequiresPersistentWiFi</key>
<string>NO</string>

<key>CFBundleIconName</key>
<string>AppIcon</string>
<key>UIDeviceFamily</key>
<array>
	<string>1</string>
	<string>2</string>
</array>
<key>MinimumOSVersion</key>
<string>8.0</string>
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>mznxt</string>
		</array>
		<key>CFBundleURLName</key>
		<string>com.damou.mznxt</string>
	</dict>
	<dict>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>wx96c46d2a21078f13</string>
		</array>
		<key>CFBundleURLName</key>
		<string>weixin</string>
	</dict>
</array>
]]></InfoAdditions>
    <requestedDisplayResolution>high</requestedDisplayResolution>
  </iPhone>
  <initialWindow>
    <title>智能学堂初中版</title>
    <content>zn.swf</content>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    
    
    <renderMode>direct</renderMode>
    
    
    <aspectRatio>landscape</aspectRatio>
    <systemChrome>standard</systemChrome>
    <autoOrients>true</autoOrients>
    <softKeyboardBehavior>pan</softKeyboardBehavior>
    <requestedDisplayResolution>high</requestedDisplayResolution>
    <depthAndStencil>true</depthAndStencil>
  </initialWindow>
  <icon>
    <image48x48>icons/icon_48.png</image48x48>
    <image57x57>icons/icon_57.png</image57x57>
    
    <image72x72>icons/icon_72.png</image72x72>
    <image76x76>icons/icon_76.png</image76x76>
    <image96x96>icons/icon_96.png</image96x96>
    <image114x114>icons/icon_114.png</image114x114>
    <image120x120>icons/icon_120.png</image120x120>
    <image144x144>icons/icon_144.png</image144x144>
    <image152x152>icons/icon_152.png</image152x152>
    <image36x36>icons/icon_36.png</image36x36>
    <image16x16>icons/icon_16.png</image16x16>
    <image512x512>icons/icon_512.png</image512x512>
    
    <image29x29>icons/icon_29.png</image29x29>
    <image32x32>icons/icon_32.png</image32x32>
    <image40x40>icons/icon_40.png</image40x40>
    <image50x50>icons/icon_50.png</image50x50>
    <image58x58>icons/icon_58.png</image58x58>
    <image80x80>icons/icon_80.png</image80x80>
    <image87x87>icons/icon_87.png</image87x87>
	<image167x167>icons/icon_167.png</image167x167>
    <image100x100>icons/icon_100.png</image100x100>
    <image128x128>icons/icon_128.png</image128x128>
    <image180x180>icons/icon_180.png</image180x180>
    
  </icon>
  
  <description>
    <text xml:lang="zh">
    </text>
  </description>
  <supportedLanguages>zh</supportedLanguages>
  <copyright>2017 Damou Technology Co., Ltd.</copyright>
 
</application>
`

**Comment by ifczt** [comment]
@ajwfrost 
Thank you very much for your answer
im use utf-8

**Comment by ifczt** [comment]
<filename>智能学堂初中版</filename>
  <name>
    智能学堂初中版
  </name>
i set this app name but i get it '667a80fd5b665802521d4e2d7248' maybe is unicode cant use utf-8

**Comment by ajwfrost** [comment]
Where are you setting this name?
Do you edit the application descriptor XML file directly? or do you use Animate or similar?

thanks

**Comment by ifczt** [comment]
![QQ截图20201019173556](https://user-images.githubusercontent.com/4133892/96427803-92c4ca80-1231-11eb-8f38-7d3443420bc5.png)

yes im  edit the application descriptor XML file directly

**Comment by ifczt** [comment]
and im use flashdevelop

**Comment by ajwfrost** [comment]
Okay thanks. So, the issue is that the "filename" is set with Chinese characters. The filename is used for the "CFBundleExecutable" value and for the name of the generated executable file and .app folder: this causes problems for the signature process if it's got non-latin characters it seems.

So, if you can change the "filename" value to something more similar to your application ID or something else in Latin text, but leave the "name" value in Chinese, you should end up with a .ipa file that can be installed but then displays to the user with the Chinese name properly.

thanks

**Comment by ifczt** [comment]
sry if i change "filename" ios will report the ERROR ITMS-90694:" Invalid bundle display name."智能学堂初中版" starts with a whitespacecharacter cant change "filename" Is there any other solution

**Comment by ifczt** [comment]
@ajwfrost hi~ can u help me please i need u help ~~

**Comment by nyaaao** [comment]
@ifczt looking at your screenshot there's a space in the <name> in the beginning and that's why it fails. after you fix that it should work, I believe

**Comment by ifczt** [comment]
@nyaaao tanks but I tried, but it didn't work

**Comment by ifczt** [comment]
@ajwfrost Do you have any other solutions
