### ISSUE TITLE
Failed to package AIR application .ipa (Compilation failed while executing : compile-abc)

### ISSUE THREAD

**Issue by Mintonist** [Gamua/Adobe-Runtime-Support#501]
Hi all!

AIR 33.1.1.217 and 33.1.1.259

Failed to package AIR application ***.ipa:
0x000F2471 (0x041C71E8 0x00000000 0x041C71C8 0x041C7230)<br>0x000000013F57CFC4 (0x000000000030E240 0x0000000000000000 0x000000000030E240 0x000000013F57D15E)<br>0x000000013F57D8BA (0x000002C6907B7438 0x000002C691238930 0x000002C6907B7378 0x000002C691238A38)<br>0x000000013F6484ED (0x000000000030E3C0 0x000000000030E3C0 0x000002C690AD8050 0x000000000030E200)<br>0x000000013F648663 (0x000002C691238930 0x000002256AFA3400 0x000000000000034B 0x000000000030E530)<br>0x000000013F648180 (0x000002C691238930 0x000000000030E530 0x000000000030E450 0x0000000000000000)<br>0x000000013F613027 (0x000002C691238830 0x0000000000000000 0x0000000000000000 0x0000000000000000)<br>0x000000013F60CC28 (0x000002C691238830 0x000002C69139F1D8 0x000002C69139F060 0x000002C69139F1D8)<br>0x000000013F56D488 (0x00000000026F98E0 0x000003E112EA866E 0x000003E112EA8655 0x0000000000000001)<br>0x000000013F566D95 (0x000000000030ECC0 0x000003E112EA8655 0x0000000000000047 0x0000000000000000)<br>0x000000013F554639 (0x00000001404E78A0 0x00000000026F98E0 0x000000000030ECE0 0x000002256AFA3400)<br>0x000000013F4FDB53 (0x0000000000000000 0x000002250000226F 0x0000000002B40F70 0x00000000000034B0)<br>0x000000013F4FB349 (0x000002256A991000 0x0000000000000014 0x000002250000010C 0x000002256A9A3200)<br>0x000000013F50132F (0x0000000000442340 0x0000000000000000 0x000000000000001D 0x0000000000000000)<br>0x000000013F5025E0 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)<br>0x000000014043BEE8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)<br>0x000000007706556D (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0xD bytes(s)<br>0x00000000771C372D (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x1D bytes(s)<br>Compilation failed while executing : compile-abc

**Comment by ajwfrost** [comment]
Can you please confirm (a) the OS version, and (b) what target option you're using (ipa-debug etc) when packaging?

thanks

**Comment by Mintonist** [comment]
Sorry.

I use Windows 7 х64, IDEA 2020.3, jdk 1.8.112. And all worked fine few days ago.  Simple (hello word) project build without errors. 
So problem is into my project. I don't understand what I need to do?) I can revert all changes for last week but may be you show me the right way.

Thx!

**Comment by Mintonist** [comment]
C:\Program Files\JetBrains\IntelliJ IDEA 203.4818.26\jbr\bin\java.exe -Dapplication.home=F:\SDK\AIR33.1 -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Duser.language=en -Duser.region=en -Xmx1024m -jar F:\SDK\AIR33.1\lib\adt.jar -package -target ipa-app-store -storetype PKCS12 -keystore D:\Projects\ForestBounty_AIR\cert\****.p12 -storepass **** -provisioning-profile D:\Projects\ForestBounty_AIR\cert\2020_ForestBounty_AppStore.mobileprovision D:\Projects\ForestBounty_AIR\bin-debug\Forest_Bounty_IOS.ipa D:\Projects\ForestBounty_AIR\bin-debug\MobileIOSAppStore.xml -extdir D:\Projects\ForestBounty_AIR\ane -C D:\Projects\ForestBounty_AIR\bin-debug Forest_Bounty_IOS.swf -C D:\Projects\ForestBounty_AIR\bin-debug ForestBounty_music.swf -C D:\Projects\ForestBounty_AIR GoogleService-Info.plist -C D:\Projects\ForestBounty_AIR\system\icons_ios Assets.car -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-375w-667h@2x~iphone.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-414w-736h@3x~iphone.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-414w-896h@3x~iphone.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-568h@2x.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-568h@2x~iphone.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-667h@2x.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-812h@3x~iphone.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-896h@2x~iphone.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-Landscape-1112h@2x.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-Landscape-414w-736h@3x~iphone.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-Landscape-414w-896h@3x~iphone.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-Landscape-812h@3x~iphone.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-Landscape-896h@2x~iphone.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-Landscape.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-Landscape@2x.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-Landscape@2x~ipad.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-Landscape~ipad.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-Portrait-1112h@2x.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-Portrait.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-Portrait@2x.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-Portrait@2x~ipad.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default-Portrait~ipad.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default@2x.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default@2x~iphone.png -C D:\Projects\ForestBounty_AIR\system\icons_ios Default~iphone.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon120.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon152.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon167.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon180.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon29.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon40.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon58.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon76.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon80.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon87.png

**Comment by ajwfrost** [comment]
Hi - I'm not sure we will be able to see why compile-abc is failing based on that initial error output. No clues in that I'm afraid. 
To narrow it down, are you able to eliminate any other SWF files? So you have your initial 'IOS' SWF, and a 'music' SWF, and then some ANEs each of which will have a SWF. If you can take those out and see when the problem goes away, you can see which of the SWFs is causing the problem.
We're just preparing our next release at the moment but I may be able to sneak in a quick low-risk change to ADT so that we could output the command-line to the compile-abc executables when in debug mode, which would make the above a little easier to work out..  So if you can wait a week, try with our next release, in the config file (lib\adt.cfg) add `DebugOut=true` and then check your `c:\users\[username]\adt.log` file for the details.

thanks

**Comment by Mintonist** [comment]
I try last release and have the same problem:

0x00122471 (0x045B2EF0 0x00000000 0x045B2ED0 0x045B2F38)<br>0x000000013F14CFC4 (0x00000000001EE070 0x0000000000000000 0x00000000001EE070 0x000000013F14D15E)<br>0x000000013F14D8BA (0x000003AE218255B0 0x00000499953CF920 0x000003AE218254F0 0x00000499953CFA28)<br>0x000000013F2184ED (0x00000000001EE1F0 0x00000000001EE1F0 0x000003AE21818830 0x00000000001EE030)<br>0x000000013F218663 (0x00000499953CF920 0x00000499952D3B00 0x000000000000034C 0x00000000001EE360)<br>0x000000013F218180 (0x00000499953CF920 0x00000000001EE360 0x00000000001EE280 0x0000000000000000)<br>0x000000013F1E3027 (0x00000499953CF830 0x0000000000000000 0x0000000000000000 0x0000000000000000)<br>0x000000013F1DCC28 (0x00000499953CF830 0x00000499953061D8 0x0000049995306060 0x00000499953061D8)<br>0x000000013F13D488 (0x00000000027C5FB0 0x000002DE1CFF8E78 0x000002DE1CFF8E5F 0x0000000000000001)<br>0x000000013F136D95 (0x00000000001EEAF0 0x000002DE1CFF8E5F 0x0000000000000047 0x0000000000000000)<br>0x000000013F124639 (0x00000001400B78A0 0x00000000027C5FB0 0x00000000001EEB10 0x00000499952D3B00)<br>0x000000013F0CDB53 (0x0000000000000000 0x0000049900002279 0x00000000026322A0 0x00000000000034C0)<br>0x000000013F0CB349 (0x0000049994C61000 0x0000000000000014 0x00000499000000E5 0x0000049994C73200)<br>0x000000013F0D132F (0x000000000029D9B0 0x0000000000000000 0x000000000000001F 0x0000000000000000)<br>0x000000013F0D25E0 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)<br>0x000000014000BEE8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)<br>0x00000000771759CD (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0xD bytes(s)<br>0x00000000773AA561 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)<br>Compilation failed while executing : compile-abc

adt.log:
*** ADT Logging at 2020/11/05 22:38:00 ***
Called by: F:\SDK\AIR33.1\lib\adt.jar
ADT called with: -package -target ipa-app-store -storetype PKCS12 -keystore D:\Projects\ForestBounty_AIR\cert\VIGR_2020.p12 -storepass *** -provisioning-profile D:\Projects\ForestBounty_AIR\cert\2020_ForestBounty_AppStore.mobileprovision D:\Projects\ForestBounty_AIR\bin-debug\Forest_Bounty_IOS.ipa D:\Projects\ForestBounty_AIR\bin-debug\MobileIOSAppStore.xml -extdir D:\Projects\ForestBounty_AIR\ane -C D:\Projects\ForestBounty_AIR\bin-debug Forest_Bounty_IOS.swf -C D:\Projects\ForestBounty_AIR\system\icons_ios icon29.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon40.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon58.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon76.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon80.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon87.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon120.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon152.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon167.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon180.png -C D:\Projects\ForestBounty_AIR\system Assets.car
*** ADT Logging at 2020/11/05 22:38:01 ***
Called by: F:\SDK\AIR33.1\lib\adt.jar
ADT called with: -package -target ipa-app-store -storetype PKCS12 -keystore D:\Projects\ForestBounty_AIR\cert\VIGR_2020.p12 -storepass *** -provisioning-profile D:\Projects\ForestBounty_AIR\cert\2020_ForestBounty_AppStore.mobileprovision D:\Projects\ForestBounty_AIR\bin-debug\Forest_Bounty_IOS.ipa D:\Projects\ForestBounty_AIR\bin-debug\MobileIOSAppStore.xml -extdir D:\Projects\ForestBounty_AIR\ane -C D:\Projects\ForestBounty_AIR\bin-debug Forest_Bounty_IOS.swf -C D:\Projects\ForestBounty_AIR\system\icons_ios icon29.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon40.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon58.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon76.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon80.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon87.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon120.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon152.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon167.png -C D:\Projects\ForestBounty_AIR\system\icons_ios icon180.png -C D:\Projects\ForestBounty_AIR\system Assets.car
Invalid input: Compilation failed while executing : compile-abc


Is it normal to calling adt.jar twice within 1 second? Seems it is logging duplication.

**Comment by Mintonist** [comment]
I have done many tests on this. The problem is not in additional .swf or .ane files or other package files (icons, .car, etc) - I try to compile many cases.

I find two commits in my project - without and with this error (it was a month ago). But I can't understand reason. This commit has only as3 code changes and all. I can't rollout to that old commit. Of course I try to checkout to that commit and done fixes line to line but no effects(   I can't find necessary code.

Current code compiles and works fine in Android and Windows targets. 

What I need to do?) Please, help!
Thx!

**Comment by Mintonist** [comment]
I have really done it!)

This code breaks .ipa packaging... At any place

if(someOject != null)
{
	switch(someOject.someField)
	{
		case SomeOjectClass.SOME_INT_CONSTANT:
			// todo. some commented code
			break;
	}
}

Android and Windows targets compile and work fine!

**Comment by ipnet-me** [comment]
> Hi all!
> 
> AIR 33.1.1.217 and 33.1.1.259
> 
> Failed to package AIR application ***.ipa:
> 0x000F2471 (0x041C71E8 0x00000000 0x041C71C8 0x041C7230)
> 0x000000013F57CFC4 (0x000000000030E240 0x0000000000000000 0x000000000030E240 0x000000013F57D15E)
> 0x000000013F57D8BA (0x000002C6907B7438 0x000002C691238930 0x000002C6907B7378 0x000002C691238A38)
> 0x000000013F6484ED (0x000000000030E3C0 0x000000000030E3C0 0x000002C690AD8050 0x000000000030E200)
> 0x000000013F648663 (0x000002C691238930 0x000002256AFA3400 0x000000000000034B 0x000000000030E530)
> 0x000000013F648180 (0x000002C691238930 0x000000000030E530 0x000000000030E450 0x0000000000000000)
> 0x000000013F613027 (0x000002C691238830 0x0000000000000000 0x0000000000000000 0x0000000000000000)
> 0x000000013F60CC28 (0x000002C691238830 0x000002C69139F1D8 0x000002C69139F060 0x000002C69139F1D8)
> 0x000000013F56D488 (0x00000000026F98E0 0x000003E112EA866E 0x000003E112EA8655 0x0000000000000001)
> 0x000000013F566D95 (0x000000000030ECC0 0x000003E112EA8655 0x0000000000000047 0x0000000000000000)
> 0x000000013F554639 (0x00000001404E78A0 0x00000000026F98E0 0x000000000030ECE0 0x000002256AFA3400)
> 0x000000013F4FDB53 (0x0000000000000000 0x000002250000226F 0x0000000002B40F70 0x00000000000034B0)
> 0x000000013F4FB349 (0x000002256A991000 0x0000000000000014 0x000002250000010C 0x000002256A9A3200)
> 0x000000013F50132F (0x0000000000442340 0x0000000000000000 0x000000000000001D 0x0000000000000000)
> 0x000000013F5025E0 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
> 0x000000014043BEE8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
> 0x000000007706556D (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0xD bytes(s)
> 0x00000000771C372D (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x1D bytes(s)
> Compilation failed while executing : compile-abc
