### ISSUE TITLE
Flash Builder 4.7 Premium - how long it will be available in Creative Cloud?

### ISSUE THREAD

**Issue by dmitrydmsk** [Gamua/Adobe-Runtime-Support#506]
Hello, sorry if its not right place to ask.
Flash Builder 4.7 Premium is agreat IDE, one of the reason i still working on AIR projects. I have paid subscription to HARMAN AIR 33 SDK, paid ANEs from Disqrete and pay montly for full version of Creative Cloud subscriptions. There are a difficulties and bugs, but so far it is still convinient  to build apps for mobile.
 What worries me - Flash Builder 4.7 is not official part of creative cloud and can disappear anytime. Today i tried to buy perpetual TLP license from authorised reseller - their assuried me what it is in Adobe price list, what they emailed them in 12.00 and they akchowledge purchasement - and i made bank money transfer. But in 14.00 got a call with exuses from reseller - they said what Adobe stopped to sell this licenses "right now" so they will return money. After some talks, manager tried to convience Adobe to release "just one key", buy got answear what "its technically impossible", "product dropped" and so on.
  Is it possible for Harman as Adobe partner to obtain license for FB 4.7 Prem, so anyone who like to use Flash Builder can buy it and have a litte assurance it is not just disapperied overnight, bringing more trouble to air developers, forcing us to look for other tools, command lines paths or else?
 And honestly, what is the state of air development? Is there any future and hope? Should me continue hanging on air and invest money to all these subscriptions (ide,ane,sdk)? Or we shold run away from this technology (as many said long time ago) because its dead - and there are just few teams, which for different reasons still using air and buy susbscription, so there is no money for Harman to sustain support and Adobe just dont care anymore about anything related to AIR - they even dont want to sell very old tool, for a fulll price ~$800.

**Comment by leossmith** [comment]
FB is old and full of bugs. Causes so many troubles during development. If you are not using AMF, Coldfusion or BlazeDS any more, why not migrate to Intellij?

**Comment by marchbold** [comment]
While AIR development is definitely still a really great solution I believe Flash Builder is something that everyone should all move on from. 

You will not regret a move to a modern IDE, IntelliJ is our choice but there are several other options that are much more reliable than Flash Builder.

**Comment by ajwfrost** [comment]
I don't think Flash Builder has the scale now to be a viable tool, with the alternatives that are around I suspect people will need to migrate away. Mostly I think it's just used by big businesses who have the copies they need; I have to confess to never being a fan of Eclipse or the tools that were based on it.. 

For AIR itself, we're happy with the scale and the numbers of people downloading and using it. It might be nicer for us if the balance between 'free tier' and the commercially licensed folk was more in our favour, but we are still seeing new people signing up and now that renewals have also started, our management are happy with the long term viability of this.

Anyway - we don't have any specific deal with Adobe relating to Flash Builder so can't support this directly I'm afraid.. I was told you could still get Flash Builder from Adobe currently but I would expect this to change when their official Flash Player EOL hits..

**Comment by JanFW** [comment]
Our team is using IntellJ IDEA for a very big AIR/Flex project since the beginning of 2018.
We have (also) moved from FlashBuilder to IntelliJ and it was one of the best decisions we have made!
IntelliJ is by far superior in nearly every aspect.

**Comment by hardcoremore** [comment]
I am still using Flash Builder 4.7 and have very little issues with it. Its fast and supports library projects that I use a lot. I would like to keep using it as long as Adobe allows it.

**Comment by rdefalco** [comment]
I jump into this thread to ask someone who has already transitioned from FB to IntelliJ.

I use flashbuilderc.exe with a custom script to build ARM apk, ARM64 apk, IPA and AIR (reverting temporarily my descriptor to v32.0 for .AIR and reducing programmatically version number between architectures according to the apk requirements).

Do someone know if IntelliJ has command line packaging features?

**Comment by dmitrydmsk** [comment]
Thanks to all for advices and respond. After some toughts i decided do not worry that much about FB. I will use FB for now as a part of Adobe CC and will move on to something else if it will removed from CC or became unusable for some reasons.

**Comment by thywfs18** [comment]
Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/



Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/





Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/




Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/




Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/






Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/





Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/











Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/







Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/



Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/



Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/





Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/




Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/




Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/






Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/





Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/











Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/







Download Link  >>>>  https://pcsoftsfull.org/after-verification-click-go-to-download/
