### ISSUE TITLE
Remove Splash Screen on ADL

### ISSUE THREAD

**Issue by llorenzo** [Gamua/Adobe-Runtime-Support#509]
When running on ADL on Mac there is a new splash screen from Harman.

We have paid to not see this unpleasant screen during startup of the app.
What is the point of that screen in ADL when you have paid?

The pespective of having to look at that screen hundreds of times in the future gives me shivers...

Could you please remove that screen!

**Comment by ajwfrost** [comment]
Hi
Can you please check your license file is in the 'lib' folder of the SDK, and let us know what happens when you run "adt -license" from a command line?
ADL should check this file and ensure that it hides the splash screen if you have a commercially-licensed version of the SDK.
thanks
  Andrew

**Comment by llorenzo** [comment]
MacBook-Pro-2:bin lorenzo$ ./adt -license
License file is present and valid

**Comment by ajwfrost** [comment]
Okay thanks - so this is working for us as expected, are you able to confirm what version of MacOS you're running? and is this a normal Mac-target application i.e. AIR for desktop?

**Comment by llorenzo** [comment]
Yes i'm on Mojave. AIR-Target is iOS.

**Comment by ajwfrost** [comment]
Ah - thanks - yes I think there was an issue with this sometimes happening in an earlier SDK, we had been trying to get ADL to call the ADT process to check the license condition, but this sometimes had problems so we now have ADL check it directly...

thanks
