### ISSUE TITLE
Android `res` folder not packaged with 33.1.1.300

### ISSUE THREAD

**Issue by marchbold** [Gamua/Adobe-Runtime-Support#518]
## Problem Description

Appears the `res` folder that can be used to package Android resources is not working in the latest release of the AIR SDK 33.1.1.300. 

## Steps to Reproduce

- include a simple resource, such as an icon in `res/drawable-xxxx/`
- reference it in your manifest additions;
- attempt to package your application and you will receive a missing resource error

## Known Workarounds

Exact same setup will work with AIR SDK v33.1.1.259

**Comment by ajwfrost** [comment]
We'd updated this feature to use the "-resdir" option per the conversation on #163 .. we did have a brief look at trying to auto-detect but are just too concerned with ambiguities that would cause people problems.

This way it's a bit more clear what's intended, hopefully then a one-off update to build scripts etc..

thanks

**Comment by marchbold** [comment]
Hmmm okay, would have preferred it to be the default and used the resdir switch to change it, but okay, I'll get all our build scripts updated. I honestly believe there isn't an app that won't use this function. 

Also, when are you planning on getting some documentation together, you are adding features like this, but there's little documentation available on it.

**Comment by ajwfrost** [comment]
It would perhaps have been better if we'd gone with one approach and stuck with it, but with that initial version we were getting complaints that it was affecting existing set-ups. So we are now planning to stick with the general principle that we don't change anything such that it changes the current behaviour: if you want a new feature, you have to explicitly request it (in terms of the tools, arguments, etc).

Documentation, yes this was just mentioned in a side-note in the release notes but I've found from a lot of feedback that no one really reads those! When we get into next year and have a bit more time, we will be reviewing all the documentation and website again (it's somewhat busy right now as we're also supporting the Flash Player and there are a lot of big companies needing support with that!)

thanks

**Comment by marchbold** [comment]
Just checking but this approach means this feature cannot be used in any IDE's without them updating and including the option eg intellij, animate?  We'll need to create a build script for an app and add the adt option. Is `resdir` relative or absolute?

Think I may stick with the custom resources ANE

**Comment by marchbold** [comment]
Also, release notes are not documentation, we shouldn't have to scour the release notes to figure out how to use the sdk.

**Comment by leossmith** [comment]
@ajwfrost  Can this be used in intellij as an additional parameter in compiler? Also can you provide an example of usage?

**Comment by marchbold** [comment]
@leossmith Can you add adt packaging commands in intellij? I've only ever been able to add compiler arguments. Pretty sure they have just broken this feature for intellij users.

**Comment by leossmith** [comment]
@marchbold indeed, i wasn't able to use this in intellij. I had to compile with Flash Builder to use the -resdir. Maybe this can be added in the AIR configuration file as an argument?

**Comment by ajwfrost** [comment]
Config file might be an option for these IDEs then. Seems like whatever we do, we end up breaking it for one group or another!

**Comment by marchbold** [comment]
Maybe a tag in the app descriptor, something that is app based rather than global? whatever the method they need to start being consistent with this stuff... Driving me crazy... Just changed all our builds to use this and wrote new tutorials for our extensions and now I'm going to have to change it all back..

**Comment by marchbold** [comment]
@ajwfrost you need to make sure whatever approach you take is app specific and accessible to all ides... As far as I can tell this means the app descriptor... New tag under the android settings <resdir>res</resdir>?

I believe you need to define the direction though, we already have specific directory names on iOS that are treated differently so I feel your original approach was valid and inline with other options.

And you need to start documenting things.

**Comment by leossmith** [comment]
I didnt think of that, but yeah, app descriptor makes much more sense and it will be easier to use.

**Comment by sjabberwocky** [comment]
I agree with the application descriptor that this is the easiest way to work with custom resources.
Personally, I renamed folder with our assets from `res` to `resources`. It's not so beautiful, but it's okay.

**Comment by Dimensionscape** [comment]
Documentation is a must. Anyone who says otherwise isn't a serious developer.

**Comment by leossmith** [comment]
@ajwfrost any update on this?

**Comment by ajwfrost** [comment]
@leossmith - we're looking to incorporate a tag per the suggestion above into the XML descriptor file so that this can be set up on a per-project basis. And the -resdir command line would kept too and would then overwrite the XML descriptor setting in case of any conflict. One of the guys is working on this currently..

**Comment by leossmith** [comment]
I hope we will have this soon :)

**Comment by denisgl7** [comment]
I understand you didn't include this tag in the new release? when to wait for the next release?

**Comment by marchbold** [comment]
Any updates here?

**Comment by Mintonist** [comment]
Seems it's done in AIR 33.1.1.406!

**Comment by leossmith** [comment]
How does this work? can someone give an example?

**Comment by marchbold** [comment]
This is now available in 33.1.1.406. So excited for this one, going to make android builds so much easier!

I've put together the following guide on its usage. Let me know if anything isn't clear:

https://docs.airnativeextensions.com/docs/tutorials/android-resources
