### ISSUE TITLE
Amazon Fire TV Stick Lite/Gen 3 Hangs On Start Up

### ISSUE THREAD

**Issue by dmunsie** [Gamua/Adobe-Runtime-Support#530]
Older Amazon Fire TV/Stick devices not affected. This just happens on the recently released 2020 versions of their Gen 3 Fire Stick/Fire Stick Lite devices. Control never makes it to the swf. The runtime seems to be initialized by looking at the logcat, but the swf itself never launches. The start up logo appears and then just hangs from there. 

I've tested older apps as well (mine and others) and they show the same behavior on these devices. So it's not just related to the newer SDKs. 

Link to device specs:
https://developer.amazon.com/docs/fire-tv/device-specifications-fire-tv-stick.html?v=ftvsticklite

I'm using 33.300 but older SDKs show the same issue. If there's anything I can do to further test on my end, I would appreciate any comments, but I fear it's in the runtime. Fingers crossed it's something obvious. ;)

Here is a logcat dump. (myapp.tvtest)
[logcat2.txt](https://github.com/Gamua/Adobe-Runtime-Support/files/5567634/logcat2.txt)

Thank you.

**Comment by dmunsie** [comment]
Would really love someone to take a look at the above logcat and see if there's any evidence of the runtime not passing execution to the swf or something else happening. Thanks.

**Comment by dmunsie** [comment]
Going crazy here, can't tell if it's the swf or the runtime causing the problem. Can someone download the logcat in the op and have a look? Thanks.

**Comment by dmunsie** [comment]
Does this logcat info tell us anything?!?!?!

`
11-18 16:46:59.888   508   527 I ActivityManager: Start proc 31494:com.myapp.tvtest/u0a186 for activity com.myapp.tvtest/.AppEntry
11-18 16:46:59.905 31494 31494 E tvtest: Not starting debugger since process cannot load the jdwp agent.
11-18 16:46:59.983 31494 31494 I tvtest: The ClassLoaderContext is a special shared library.
11-18 16:47:00.046 31494 31494 W tvtest: resources.arsc in APK '/data/app/com.myapp.tvtest-patxxTO14BHsqebu0bXTxA==/base.apk' is compressed.
11-18 16:47:00.086 31494 31494 I StartupTime1: :1605739620086
11-18 16:47:00.086 31494 31494 I AIR VERSION: :33.1.1.300
11-18 16:47:00.086 31494 31494 I DEVICE ARCH: :armeabi-v7a
11-18 16:47:00.227 31494 31494 E SELinux : avc:  could not determine enforcing mode: Permission denied
11-18 16:47:00.227 31494 31494 E SELinux : Unknown class directtexture
11-18 16:47:00.227 31494 31494 D OpenGLRenderer: Skia GL Pipeline
11-18 16:47:00.267 31494 31494 W OrientationEventListener: Cannot detect sensors. Not enabled
11-18 16:47:00.355 31494 31494 I AIR RUNTIME: Version 33,1,1,300 - platform Android-ARM
11-18 16:47:05.400 31494 31494 W ServiceManager: Service media.camera didn't start. Returning NULL
11-18 16:47:05.400 31494 31494 W CameraBase: CameraService not published, waiting...
11-18 16:47:10.902 31494 31494 W ServiceManager: Service media.camera didn't start. Returning NULL
11-18 16:47:10.902 31494 31494 W CameraBase: CameraService not published, waiting...
11-18 16:47:16.404 31494 31494 W ServiceManager: Service media.camera didn't start. Returning NULL
11-18 16:47:16.404 31494 31494 W CameraBase: CameraService not published, waiting...
11-18 16:47:21.905 31494 31494 W ServiceManager: Service media.camera didn't start. Returning NULL
11-18 16:47:21.906 31494 31494 W CameraBase: CameraService not published, waiting...
11-18 16:47:27.407 31494 31494 W ServiceManager: Service media.camera didn't start. Returning NULL
11-18 16:47:27.407 31494 31494 W CameraBase: CameraService not published, waiting...
11-18 16:47:32.909 31494 31494 W ServiceManager: Service media.camera didn't start. Returning NULL
11-18 16:47:32.909 31494 31494 W CameraBase: CameraService not published, waiting...
11-18 16:47:37.996   508   525 I system_server: libdebuggerd_client: started dumping process 31494
11-18 16:47:37.998   389   389 I /system/bin/tombstoned: registered intercept for pid 31494 and type kDebuggerdJavaBacktrace
11-18 16:47:37.998 31494 31500 I tvtest: Thread[3,tid=31500,WaitingInMainSignalCatcherLoop,Thread*=0xaddb1200,peer=0x14e02760,"Signal Catcher"]: reacting to signal 3
11-18 16:47:37.998 31494 31500 I tvtest: 
11-18 16:47:38.108   389   389 I /system/bin/tombstoned: received crash request for pid 31494
11-18 16:47:38.108   389   389 I /system/bin/tombstoned: found intercept fd 512 for pid 31494 and type kDebuggerdJavaBacktrace
11-18 16:47:38.108 31494 31500 I tvtest: Wrote stack traces to '[tombstoned]'
11-18 16:47:38.109   508   525 I system_server: libdebuggerd_client: done dumping process 31494
11-18 16:47:39.055 31494 31494 W ServiceManager: Service media.camera didn't start. Returning NULL
11-18 16:47:39.055 31494 31494 W CameraBase: CameraService not published, waiting...
11-18 16:47:43.860   508   525 E ActivityManager: ANR in com.myapp.tvtest (com.myapp.tvtest/.AppEntry)
11-18 16:47:43.860   508   525 E ActivityManager: PID: 31494
11-18 16:47:43.860   508   525 E ActivityManager: Reason: Input dispatching timed out (Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it.  Outbound queue length: 0.  Wait queue length: 1.)
11-18 16:47:43.860   508   525 E ActivityManager: Load: 4.62 / 4.64 / 4.44
11-18 16:47:43.860   508   525 E ActivityManager: CPU usage from 0ms to 6300ms later (2020-11-18 16:47:37.538 to 2020-11-18 16:47:43.838):
11-18 16:47:43.860   508   525 E ActivityManager:   45% 2052/com.amazon.whad: 31% user + 13% kernel / faults: 3211 minor 501 major
11-18 16:47:43.860   508   525 E ActivityManager:   17% 508/system_server: 12% user + 4.7% kernel / faults: 4702 minor 386 major
11-18 16:47:43.860   508   525 E ActivityManager:   10% 57/kswapd0: 0% user + 10% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   6% 29366/com.amazon.tv.settings.v2: 4.6% user + 1.4% kernel / faults: 4160 minor 54 major
11-18 16:47:43.860   508   525 E ActivityManager:   5.2% 2021/com.amazon.vizzini: 4.4% user + 0.7% kernel / faults: 3499 minor 163 major
11-18 16:47:43.860   508   525 E ActivityManager:   4.7% 1681/com.amazon.device.services: 4.1% user + 0.6% kernel / faults: 3851 minor 53 major
11-18 16:47:43.860   508   525 E ActivityManager:   2.2% 376/media.codec: 1.1% user + 1.1% kernel / faults: 1987 minor 48 major
11-18 16:47:43.860   508   525 E ActivityManager:   1.9% 2032/com.amazon.tcomm: 1.2% user + 0.6% kernel / faults: 2525 minor 94 major
11-18 16:47:43.860   508   525 E ActivityManager:   1.7% 367/media.extractor: 1.2% user + 0.4% kernel / faults: 1856 minor 38 major
11-18 16:47:43.860   508   525 E ActivityManager:   1.7% 2042/com.amazon.tv.devicecontrol: 1.1% user + 0.6% kernel / faults: 1966 minor 138 major
11-18 16:47:43.860   508   525 E ActivityManager:   1.5% 1901/com.amazon.imp: 1.4% user + 0.1% kernel / faults: 2061 minor 202 major
11-18 16:47:43.860   508   525 E ActivityManager:   1.4% 325/surfaceflinger: 0.1% user + 1.2% kernel / faults: 207 minor 6 major
11-18 16:47:43.860   508   525 E ActivityManager:   1.4% 31494/com.myapp.tvtest: 0.4% user + 0.9% kernel / faults: 1030 minor 39 major
11-18 16:47:43.860   508   525 E ActivityManager:   1.2% 9233/adbd: 0.1% user + 1.1% kernel / faults: 13779 minor
11-18 16:47:43.860   508   525 E ActivityManager:   0.7% 3658/com.android.bluetooth: 0.3% user + 0.4% kernel / faults: 1688 minor 26 major
11-18 16:47:43.860   508   525 E ActivityManager:   0.6% 214/logd: 0% user + 0.6% kernel / faults: 116 minor
11-18 16:47:43.860   508   525 E ActivityManager:   0.4% 26/ksmd: 0% user + 0.4% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.4% 163/mmcqd/0: 0% user + 0.4% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.4% 257/hif_thread: 0% user + 0.4% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.3% 102/hdmi_timer_kthr: 0% user + 0.3% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.3% 243/ksdioirqd/mmc1: 0% user + 0.3% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.3% 298/android.hardware.graphics.composer@2.1-service: 0% user + 0.3% kernel / faults: 36 minor
11-18 16:47:43.860   508   525 E ActivityManager:   0% 389/tombstoned: 0% user + 0% kernel / faults: 172 minor 69 major
11-18 16:47:43.860   508   525 E ActivityManager:   0.3% 2948/com.amazon.tv.launcher: 0.3% user + 0% kernel / faults: 199 minor
11-18 16:47:43.860   508   525 E ActivityManager:   0.3% 30932/kworker/u8:2: 0% user + 0.3% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.1% 3/ksoftirqd/0: 0% user + 0.1% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.1% 7/rcu_preempt: 0% user + 0.1% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.1% 34/cfinteractive: 0% user + 0.1% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.1% 146/disp_osd1_irq_k: 0% user + 0.1% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.1% 147/disp_osd2_irq_k: 0% user + 0.1% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.1% 256/main_thread: 0% user + 0.1% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.1% 258/rx_thread: 0% user + 0.1% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.1% 307/fireos.hardware.audio@2.0-service: 0% user + 0.1% kernel / faults: 8 minor
11-18 16:47:43.860   508   525 E ActivityManager:   0% 366/mediadrmserver: 0% user + 0% kernel / faults: 121 minor 105 major
11-18 16:47:43.860   508   525 E ActivityManager:   0% 368/media.metrics: 0% user + 0% kernel / faults: 312 minor 34 major
11-18 16:47:43.860   508   525 E ActivityManager:   0% 369/mediaserver: 0% user + 0% kernel / faults: 235 minor 57 major
11-18 16:47:43.860   508   525 E ActivityManager:   0% 507/kworker/3:1H: 0% user + 0% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.1% 3000/com.amazon.kso.blackbird: 0.1% user + 0% kernel / faults: 86 minor
11-18 16:47:43.860   508   525 E ActivityManager:   0.1% 16493/kworker/u8:4: 0% user + 0.1% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.1% 23806/kworker/u8:5: 0% user + 0.1% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.1% 30015/kworker/0:1: 0% user + 0.1% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.1% 30038/kworker/u8:3: 0% user + 0.1% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   0.1% 31467/logcat: 0.1% user + 0% kernel / faults: 136 minor
11-18 16:47:43.860   508   525 E ActivityManager: 31% TOTAL: 18% user + 12% kernel + 0.4% iowait + 0% softirq
11-18 16:47:43.860   508   525 E ActivityManager: CPU usage from 44ms to 430ms later (2020-11-18 16:47:37.583 to 2020-11-18 16:47:37.969):
11-18 16:47:43.860   508   525 E ActivityManager:   106% 508/system_server: 79% user + 26% kernel / faults: 1806 minor 2 major
11-18 16:47:43.860   508   525 E ActivityManager:     65% 517/HeapTaskDaemon: 65% user + 0% kernel
11-18 16:47:43.860   508   525 E ActivityManager:     38% 525/ActivityManager: 14% user + 23% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   2.6% 34/cfinteractive: 0% user + 2.6% kernel
11-18 16:47:43.860   508   525 E ActivityManager:   4.1% 29366/com.amazon.tv.settings.v2: 4.1% user + 0% kernel
11-18 16:47:43.860   508   525 E ActivityManager: 26% TOTAL: 19% user + 7.3% kernel
11-18 16:47:43.867   508   525 W ActivityManager: Activity pause timeout for ActivityRecord{bf64897 u0 com.myapp.tvtest/.AppEntry t92}
11-18 16:47:43.912   508   526 I ActivityManager: Killing 31494:com.myapp.tvtest/u0a186 (adj 900): user request after error
11-18 16:47:43.914   508   528 W libprocessgroup: kill(-31494, 9) failed: No such process
11-18 16:47:43.953   508   528 W libprocessgroup: kill(-31494, 9) failed: No such process
11-18 16:47:43.996   508   528 W libprocessgroup: kill(-31494, 9) failed: No such process
11-18 16:47:44.005   281   281 I Zygote  : Process 31494 exited due to signal (9)
11-18 16:47:44.033   508   528 W libprocessgroup: kill(-31494, 9) failed: No such process
11-18 16:47:44.033   508   528 I libprocessgroup: Successfully killed process cgroup uid 10186 pid 31494 in 120ms
11-18 16:47:44.065   508   533 W ActivityManager: setHasOverlayUi called on unknown pid: 31494
`

**Comment by dmunsie** [comment]
The test app that generated this logcat has nothing in the code accessing the camera, it's just a generic hello world test. Why is the runtime trying to access the camerabase? I think this is the issue. Thanks.

**Comment by dmunsie** [comment]
25 days now. No reply.

**Comment by ajwfrost** [comment]
Hi - sorry, not sure how I've managed to miss all the notifications from the above! But, that does seem weird, looks like a SELinux issue:
11-18 16:47:00.227 31494 31494 E SELinux : avc: could not determine enforcing mode: Permission denied
but can't see why the runtime would try to open up the camera for a hello-world test.

We'll look into what's happening during start-up to see if we can work past this....

**Comment by dmunsie** [comment]
Thank you so much for responding. Fingers crossed there's something we can do to simply bypass the issue, resulting in a quick fix.

**Comment by dmunsie** [comment]
"We'll look into what's happening during start-up to see if we can work past this...."
Or perhaps maybe...I know a long shot... just a custom version that "skips" over all of this? We're desperate at this point. Thx.

**Comment by dmunsie** [comment]
I realize there's a lot of issues pending, but this one basically puts me out of business. Thanks for anything you can do.

**Comment by ajwfrost** [comment]
Hi @dmunsie  - can you check whether this fails with any basic/test AIR application? or is this specific to your own app?
There's one clue we could work with so I'd like to send you a test version of the SDK, can you please contact me at andrew.frost at harman.com
thanks

**Comment by dmunsie** [comment]
@ajwfrost  emailed. Thank you!

**Comment by dmunsie** [comment]
FYI: I use FlashDevelop to develop my apps.

**Comment by dmunsie** [comment]
Wow...what a crazy coincidence, Amazon has just contacted me as well today.
You should probably hold on before doing anything until I get done
communicating with them. Thanks!

**Comment by dmunsie** [comment]
ok.. a recent update to their Fire OS has corrected the issue. I do wish I knew what the problem was because it only appeared to affect a very small number of developers. But we can go ahead and close the issue. Thank you for your time and offer to help.
