### ISSUE TITLE
AIR 33.1.1.300 - 'DYLD, missing lazy symbol called' crash when attempting purchase on iOS

### ISSUE THREAD

**Issue by Kelsonk** [Gamua/Adobe-Runtime-Support#537]
I'm going to link this directly since I thought it was an ANE problem but it's a problem with the SDK.

https://github.com/distriqt/ANE-InAppBilling/issues/375

Trying to use this SDK version has really thrown a wrench into my apps.

**Comment by Bilbosax** [comment]
I was interested in this post because I am having trouble with 33.1.1.300 as well, but your link does not point anywhere, or maybe I don't have permission to access it???

**Comment by Kelsonk** [comment]
> I was interested in this post because I am having trouble with 33.1.1.300 as well, but your link does not point anywhere, or maybe I don't have permission to access it???

Oh, I didn't think about that. Yeah, you probably have to have the ANE license. I'll just try and copy-paste.

--------------
I'm on the latest SDK and ANE version. Whenever a purchase is attempted on iOS, specifically after this line.

var success:Boolean = InAppBilling.service.makePurchase( request );
The app will crash a couple seconds later. The purchase dialog will still show up, and remain on the screen even after the app crashes, so purchases might even work, but I haven't tested it yet. I can't really pin it down to something in my game, so I think it must be another issue. The crappy thing is I swear this was working fine a week or two ago.

The crash log has the error 'DYLD, missing lazy symbol called', but I can't say more than that, I've attached one of the many crash logs here.
--------------------------------------
[Castle Clicker-2020-11-23-094010.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/5591741/Castle.Clicker-2020-11-23-094010.zip)

------------------------------------------------------

Here's a console log, the crash is toward the bottom (my app id is com.autotelic.castleclicker)
log3.txt

Search for gem_apprentice_bag_new2 when the purchase was initialized.

I've made a minimum application that still crashes. I'm on Air SDK 33.1.300 and the latest Core and InAppBilling ANE. I have a user that's reporting the app won't open at all, even after reinstall (I think that it must be crashing trying to give them an unconsumed purchase or something) I think that's all the info I have.

EDIT: Slightly more info. The purchases_updatedHandler does get called right before the crash (the debugger will hit the first line for a split second before crashing). When trying to trace out more info in this function:

```private function purchases_updatedHandler( event:PurchaseEvent ):void
		{
			trace("Purchases Updated: " + event.message + event.errorCode);
			
			for each (var purchase:Purchase in event.data)
			{
				switchPurchaseeState(purchase);
			}
		}
```
The only thing that gets traced is
"Purchases Updated: "

EDIT: I've tried older version of the ANE to the same effect, I've tried not listening to the purchases update event to the same effect. I swear when I was testing purchases a few weeks ago when I was releasing the iOS version of my app this was working fine. I'm running out of ideas. But these issues are live so I really need to figure it out.
[log3.txt](https://github.com/Gamua/Adobe-Runtime-Support/files/5591746/log3.txt)

**Comment by Kelsonk** [comment]
Is there an update on this? Having micro transactions broken on iOS seems like an important issue.

**Comment by Kelsonk** [comment]
This is still an issue with the new SDK 33.1.1.345

**Comment by Kelsonk** [comment]
Non issue

**Comment by Elintondm** [comment]
We have the same issue here. How to solve it? Any workaround?

**Comment by Kelsonk** [comment]
> We have the same issue here. How to solve it? Any workaround?

For me this was an issue of not having update the distriqt Facebook ANE. Using the older one would cause a crash any time the app deactivated.
