### ISSUE TITLE
[not issue] ANE compatibility matrix / success stories

### ISSUE THREAD

**Issue by rdefalco** [Gamua/Adobe-Runtime-Support#548]
Hello, I don't know if it could be useful or, on the other end, if it's against any rule from Harman, Distriqt or MyFlashLabs to report some valid configurations where it's inevitable to mix together ANEs of different providers.

Let me know in both cases.

In my configuration I had to mix:
MyFlashLabs' Barcode
MyFlashLabs' LocalNotifications
MyFlashLabs' Firebase Messaging
MyFlashLabs' PackageManager
Distriqt's Share
Distriqt's NativeMaps
Distriqt's CameraRoll and CameraUI

To make everything work I had to use:
MyFlashLabs' Firebase dependencies (all added via ANE Lab)
MyFlashLabs' Google Play dependencies (all added via ANE Lab)
MyFlashLabs' androidx.browser (though I don't know if it's needed)
Distriqt's androidx.core.ane
All the main ANEs

So, comparing to each provider's official requirements, I had to remove:
Distriqt's playservices.Base and playservices.Maps, as I had to use Myflashlabs' ones
Myflashlabs' androidx.arch, androidx.core, androidx.design, androidx.lifecycle

Any other combination of the dependencies led to duplicate classes or missing classes/requirements.

**Comment by marchbold** [comment]
Definitely not against any rules, but probably better to list these in a forum ([starling](https://forum.starling-framework.org/) or [as3lang](https://discuss.as3lang.org/))

We are trying to keep this repository as issues with AIR.
