### ISSUE TITLE
AIR33: Including Support-v4 28.0.0 ANE (aka legacy-support-v4 1.0.0) results in compile error

### ISSUE THREAD

**Issue by tuarua** [Gamua/Adobe-Runtime-Support#55]
## Problem Description

Describe your problem in detail. Include the following information:

* Which AIR SDK did you use? 
33.0.0.175
* Describe the affected environment: 
AIR Android

* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?
Yes All

## Steps to Reproduce

1. Add the attached ANE ([androidx.legacy.legacy-support-v4-1.0.0.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/3332112/androidx.legacy.legacy-support-v4-1.0.0.zip) **Rename zip file to .ane to use**) to a blank AIR mobile Android project
```
<extensions>
        <extensionID>androidx.legacy.legacy-support-v4</extensionID>
    </extensions>
```
2. Compile for AIR 33
3. Observe Error: aapt tool failed:ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
			ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex

## Known Workarounds

Use older Google support libraries(this however causes Gradle warnings in Android Studio)

## Other Notes
AIR33 beta, although targeting SDK and Platform Tools 28, may still be built against older Android support libraries. These should be updated to 28 to align.

Same Issue was also observed in previous versions of Cordova
https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/205

**Comment by tuarua** [comment]
[androidx.legacy.legacy-support-v4-1.0.0.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/3332112/androidx.legacy.legacy-support-v4-1.0.0.zip)

**Comment by ajwfrost** [comment]
Hi

Thanks for this: yes we can reproduce it and as you suggest, it's to do with a misalignment in the various libraries/jar files that we're taking from the Android Platform SDK. It looks like we should have a resolution for this shortly, we need to update some build paths in our system to point to the appropriate platform folder...

  Andrew

**Comment by tuarua** [comment]
Andrew, 
Many Thanks for confirming.

Eoin

**Comment by tuarua** [comment]
Not seeing error now with 33.0.0.182
