### ISSUE TITLE
Apple M1 Chips & Adobe AIR

### ISSUE THREAD

**Issue by yozef** [Gamua/Adobe-Runtime-Support#551]
## Problem Description

Are there any work / planning occuring on having Adobe AIR compiled Apps for Mac to run natively or through Rosetta 2 on the new M1 chip Macs?

* Describe the affected environment: Flash vs. AIR, Android vs. iOS, all devices vs. just specific models.
Adobe AIR Runtime on Macs with M1+ chips.

**Comment by ajwfrost** [comment]
Hi - yes, work is ongoing for this. Closing as a duplicate of #359 
thanks
