### ISSUE TITLE
Windows platform requirements (vc++, .NET, etc)

### ISSUE THREAD

**Issue by Mintonist** [Gamua/Adobe-Runtime-Support#562]
Hi!

Does anybody know AIR requirements for Windows from your practice. I receive feedbacks from players with app startup crashes. I noticed that app don't start (autoclose after starting without showing window) if there is no any .NET Framework. So what minimum .NET Framework version is needed? What else (vc++ redistributable pack)?

With flash EOL - windows target will become more important and wide used to my mind.

There is no information on Harman site or docs. Please, add this information to every release notes.

Thx!

**Comment by ajwfrost** [comment]
There shouldn't be any dependency upon .NET! I have just checked on this via the Windows Dependency Walker and can't see anything that would imply a dependency here, are you able to confirm you're not using any ANEs at all?

**Comment by Mintonist** [comment]
Ok. Thx! Useful information.
Yes, I use some distiqt ANEs. Ask them about it.
