### ISSUE TITLE
CameraRoll.addBitmapData fails on Android 10+ after 32 images are saved from AIR apps

### ISSUE THREAD

**Issue by FliplineStudios** [Gamua/Adobe-Runtime-Support#564]
## Problem Description

When using cameraRoll.addBitmapData on Android 10 or newer, AIR is now saving images to Android's "Pictures" directory with the filename "Image.jpg", instead of generating a unique filename.  Subsequent images saved from AIR apps are continuing to use the same filename, resulting in "Image (1).jpg", "Image (2).jpg", "Image (3).jpg".  Once a total of 32 images are saved up to "Image (31).jpg", no further images will be saved when using addBitmapData on a CameraRoll object, and no errors are thrown.

On Android 9 and earlier, unique timestamp-based filenames were generated by CameraRoll.addBitmapData ("1567113735264.jpg"), allowing for unlimited photos to be saved.  Once Android 10 or newer is installed on the device, any new or existing AIR apps will change to the new "Image.jpg" format, and will not allow more than 32 images to be saved with that same filename before it silently fails.

Same results on the older Adobe AIR 32 (targeting API 26/27/28), and also on all versions of AIR 33 (targeting either API 28 or 29), including the latest 33.1.1.345 targeting 29.

## Steps to Reproduce

1.  Create a new CameraRoll object
2.  Be sure to check for CameraRoll.permissionStatus == PermissionStatus.GRANTED
3.  Create a BitmapData object, and use addBitmapData on the CameraRoll object
4.  In an Android photo viewer (eg. Google Photos), located the saved image in the Pictures directory with the filename "Image.jpg"
5.  Continue to save additional images using addBitmapData, and notice the filename for each image change to "Image (1).jpg", "Image (2).jpg"
6.  Once 32 images are saved, notice that no additional images are able to be saved from any AIR app on that device

## Known Workarounds

None

**Comment by FliplineStudios** [comment]
Looking into this more, it seems that in the Android API, MediaStore.Images.Media.insertImage must now explicitly supply a title String on Android 10 and above -- I'm assuming this is what AIR is using under the hood for addBitmapData, and wasn't originally supplying a title to be used as the filename.  Otherwise Android 10/11 just saves it as "Image", "Image (2)", etc. until the 33rd attempt, resulting in a `java.lang.IllegalStateException: Failed to build unique file` error message.  

It sounds like previous versions of Android would generate a unique timestamp for the filename if a title wasn't supplied, but recent Android versions require something to be explicitly set - perhaps AIR could generate a unique timestamp String itself to use as the image title when attempting to use CameraRoll.addBitmapData on Android, to allow for this to still work correctly?

**Comment by oltecam** [comment]
I have camera apps on Google Play. I have received feedback from customers about this problem.
It is not recommended that the camera stop saving images after 33 images have been taken.
There was no restriction on previous devices but the problem has come to Android 10 devices.
Unwanted update from Android. As a developer, can I do anything about it?

**Comment by FliplineStudios** [comment]
I had just finished adapting our app to use Distriqt's CameraRollExtended ANE and the addFile function to get around this problem (saving an image locally with a unique filename, then passing a reference to that file for addFile, then deleting the local image afterwards).  I just noticed Harman released an AIR update within the last couple days (33.1.1.444) that lists this issue in the bug fixes though, so perhaps this is now solved?  I'll download the latest SDK and check it out...

**Comment by oltecam** [comment]
79 / 5000
I just tested my camera app. The bug has been fixed in the version 33.1.1.444. Thanks to them!
