### ISSUE TITLE
Firebase Core / Analytics no data with Android and SDK 33.1.1.345 

### ISSUE THREAD

**Issue by apofis1969** [Gamua/Adobe-Runtime-Support#566]
We are using the distriqt Firebase ANE and we do not receive any events with Android devices with the new AIR SDK 33.1.1.345 at the Firebase Console.
How to resolve this?

**Comment by yooni126** [comment]
I have the same issue for firebase cloud messaging, but when I used 64 bit of customResource.ane, my problem solved

**Comment by apofis1969** [comment]
It is working with the newest ANE of distriqt.
