### ISSUE TITLE
Splash Screen shows for licensed SDK - 33.1.1.345 

### ISSUE THREAD

**Issue by teotigraphix** [Gamua/Adobe-Runtime-Support#568]
The .lic file is in the libs, I have turned off virus software, I cannot get this to go away.

Was putting time into developing but now trying to create an apk I get;

![image](https://user-images.githubusercontent.com/226417/102912970-18404300-444c-11eb-8d3b-78dc26e22ffc.png)

BTW I was looking at this popup from the debugger as well on Windows desktop testing.

I need to update these apps.

**Comment by ajwfrost** [comment]
Hi - can you please send your developer ID (from the adt.lic file) to adobe.support at harman.com and we can look into this..
thanks

**Comment by teotigraphix** [comment]
Sent, thanks.

**Comment by teotigraphix** [comment]
Sent, thanks.

**Comment by ajwfrost** [comment]
Solved by running "adt -license" within a normal command line. Might be that when VS Code runs, it doesn't run the ADT process with enough OS capabilities for it to be able to update the adt.lic file..
