### ISSUE TITLE
Adobe Air Runtime Download Gone

### ISSUE THREAD

**Issue by G-Powder** [Gamua/Adobe-Runtime-Support#574]
Hi all.

Now that Adobe has officially handed AIR over to Harmon, I was wondering if there was still a link available to download the runtime only.  It seems to have been removed from Adobe's website and archives location.

We have a desktop application that has been around for several years and was it built using an older version of the SDK.
On occasion we need to re-install the runtime only for our existing users.

Any help would be appreciated.

Thanks.

**Comment by ajwfrost** [comment]
Our recommendation for folk would be to use a bundled runtime in their apps, but we are looking to provide a shared runtime still, for end users to download. Currently just trying to sort out the legal pieces needed for this, we have installers pretty much ready although facing a few issues still on Big Sur..

We should have things resolved and uploaded within the next two weeks I believe. If you still have that older SDK, you can rebuild your app with that AIR runtime bundled into it perhaps for any more urgent needs?

thanks

**Comment by QAthulhu** [comment]
why not make the old runtime installers available in the meantime? I can't wait 2 weeks

**Comment by spamshaker** [comment]
@ajwfrost 
> Our recommendation for folk would be to use a bundled runtime in their apps

Won't it require to sing the code with Apple developer ID by developers who recently delivered and signed code by adt
https://help.adobe.com/en_US/air/build/WS5b3ccc516d4fbf351e63e3d118666ade46-7f74.html
so, will be working on Mac OS when the code will be signed by adt with existing global code sign certificate without Apple ID?

**Comment by mrchnk** [comment]
I found AIR 32 beta available at [adobe labs](https://labs.adobe.com/downloads/air.html)
