### ISSUE TITLE
[CLARIFICATION] 32bit apk installed in 64bit supported device from playstore. WHY ?

### ISSUE THREAD

**Issue by Gokulv617** [Gamua/Adobe-Runtime-Support#582]
I have uploaded 2 apk’s(32 bit and 64 bit). I’m getting more ANR’s from 32bit apk even with AIR 33.1.1.345. While checking on it, I can see 32bit apk is getting installed in 64bit supported devices also. Why is that ?

- v50.0  - 32 bit apk – minSdkVersion 14 and targetSdkVersion 29
- v50.1  - 64 bit apk – minSdkVersion 21 and targetSdkVersion 29
 
I have attached the screenshot for your reference.
![targetSDK](https://user-images.githubusercontent.com/43432782/104410868-3999d800-558f-11eb-832b-98156cf6d810.png)
//--------------------------------------------------------------------------------------------------------------------------------
![32bit in 64bit device](https://user-images.githubusercontent.com/43432782/104410904-4d453e80-558f-11eb-80c2-1a654bf71405.png)
//--------------------------------------------------------------------------------------------------------------------------------
![device](https://user-images.githubusercontent.com/43432782/104411338-33582b80-5590-11eb-9aa3-a4afdedde596.png)

**Comment by Gokulv617** [comment]
@ajwfrost 
Please share your feedback on this

**Comment by ajwfrost** [comment]
Hi @Gokulv617  - this is probably something you would need to check with Google for. The decision as to which APK to serve up for a particular customer is something that I believe is built into the Play Store, my understanding was just that if multiple options worked for a particular handset, they would be given the higher available version number. So you appear to have everything set up, with the 64-bit binary having the later version number.

I can't see anything that's wrong in the set-up, so can't really see why the Play Store has taken the decision to install a 32-bit APK  for them...

thanks

**Comment by Gokulv617** [comment]
Thank you for your feedback. I'll contact the google playstore team also
