### ISSUE TITLE
StageWebView dont show Facebook OAuth dialog on Android

### ISSUE THREAD

**Issue by Mintonist** [Gamua/Adobe-Runtime-Support#585]
## Problem Description
I implement OAuth for social networks (Facebook, VK.com, OK.com, mail.ru) with StageWebView.
All dialogues work fine on Android/IOS/Windows targets except Facebook on Android. StageWebView appears and disappears few moment later. IOS and Windows have not this problem.

I don't found any errors at logcat.

## Steps to Reproduce
Show StageWebView with url 
https://www.facebook.com/v9.0/dialog/oauth?client_id=xxxxx&display=popup&response_type=token&redirect_uri=https://www.facebook.com/connect/login_success.html

## Environment
AIR SDK version: 33.1.1.345
Development IDE: IDEA 2020.3
Development OS: Windows 7 х64

Pls help me or give me advice. I don't want to use WebView ANE for Android.

@ajwfrost  Are there any plans to update StageWebView to display modern sites (html5/js/css)?

**Comment by Mintonist** [comment]
@marchbold I think it is bug (not Feature). I really don't understand why only Facebook OAuth dialog for only Android has error.

**Comment by marchbold** [comment]
There are a myriad of issues with StageWebView so I've just been marking them all as a feature request, i.e. to update StageWebView to a modern implementation.

Why don't you want to use an ANE for this BTW? ANE's a perfectly suited for these sorts of tasks

**Comment by Mintonist** [comment]
> Why don't you want to use an ANE for this BTW? ANE's a perfectly suited for these sorts of tasks
I prefer same code and ANEs for Android/IOS. StageWebView works well in some my game logic exept only Facebook OAuth dialog on Android. If it sshown on IOS and Windows seems it can be not big issue for Harman.
If Harman ignore me, I will use your ANE.

Of course I agree with you about modern StageWebView but I prefer to create new issue for it (with a 'feature' label).

**Comment by Mintonist** [comment]
I have found problem on my side. On Android Facebook make redirect with "error=access_denied" but it is not real error redirect as expected my client.
So Facebook OAuth dialog works fine with StageWebView.
