### ISSUE TITLE
AIR SDK 33.1.1.345 iOS 14.3 signature issue

### ISSUE THREAD

**Issue by pavelzmolik** [Gamua/Adobe-Runtime-Support#590]
## Problem Description
Hello, when I compile IPA applications and install it into device with iOS 14.3, I got this message:
**This app will not work with future versions of iOS**

When I have digged a little I found this website:
https://developer.apple.com/documentation/xcode/using_the_latest_code_signature_format

I tried check the *CodeDirectory* output from the method Apple described, and I realized the Code returning from IPA from AIR SDK 33.1.1.345 is **20200** and the Apple wants **20500**.

No matter if I compile IPA at Windows(WIN 10 with latest Java Runtime Enviroment) or at the MacOS(Mac Mini M1, MacOS 11.1 Big Sur). I thought compiler on MacOS uses the xCode features(I have 12.3) so assumed the code signature should be OK, but it isn't.

I am not alone with this issue as you can see here:
https://developer.apple.com/forums/thread/671164

Please can you make sure us that new SDK version will fix this? Or is there some workaround to cheat Apple application checker?

Thank you for advance
Pavel Zmolik

**Comment by AlexLisic** [comment]
Hello, I have the same issue.

**Comment by FliplineStudios** [comment]
Same issue here for any adhoc apps installed on our 14.3 devices.  Apple's documentation mentions that anything previously submitted to the App Store or TestFlight are re-signed with the newer format, but not sure if their upload processes will start requiring this new code signing for submissions (or if they already do?)

**Comment by zizusoft** [comment]
Same issue here

**Comment by zizusoft** [comment]
If I deploy the app ad-hoc to a iOS14.3 device - it deploys, but I get the same error as those above when I run it.

If I debug the app to the same iOS device, I get this error:
![image](https://user-images.githubusercontent.com/54889301/104924782-d399c000-5995-11eb-9a33-4b704157d2c0.png)

And it won't deploy.

I'm assuming the two are related (as they are both to do with certificate signatures)?.

Using 33.1.1.345

**Comment by zizusoft** [comment]
If I deploy the app ad-hoc to a iOS14.3 device - it deploys, but I get the same error as those above when I run it.

If I debug the app to the same iOS device, I get this error:
![image](https://user-images.githubusercontent.com/54889301/104925177-64709b80-5996-11eb-8e84-e8807f38b143.png)


And it won't deploy.

I'm assuming the two are related (as they are both to do with certificate signatures)?.

Using 33.1.1.345

**Comment by MarEGMco** [comment]
Hello,
the only solution I could find was to run the codesign as indicated on: https://developer.apple.com/documentation/xcode/using_the_latest_code_signature_format
I imported the .p12 certificate on a MacOS BigSur VM in the Keychain.
Then I ran:
codesign -s "iPhone Distribution ......." -f --preserve-metadata /path/to/MyApp.app
Beware of using the --preserve-metadata otherwise it won't work, even if it says it's deprecated.
Then I checked with:
codesign -dv /path/to/MyApp.app 
and CodeDirectory results in 20400 (before it was 20200).
I ran an installation test on iPad IOS 14.3 and it installs correctly.
He hoped Harman solves the problem as all these steps slow down the build

**Comment by ajwfrost** [comment]
@MarEGMco  thanks for the workaround details..
Yes we'll be looking at this, there are quite a few updates that we need to make for code signing so this will be addressed as part of an update hopefully in the not-too-distant future!
thanks

**Comment by xangel82** [comment]
I did  @MarEGMco's workaround   but i get an other error:

An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=4):

Now the code sign generated a new Code Directory v = 20400, but after the IOS simulator (14.3) installation (with xcrun) I got the message "Application needs to be updated."

**Comment by pavelzmolik** [comment]
this bug is fixed by new AIR 33.1.1.406 and new ADT.jar
[issue 511](https://github.com/Gamua/Adobe-Runtime-Support/issues/511#issuecomment-785487450)
so i am closing this thread, and hope new public version will be released as soon as possible
thx guys!
