### ISSUE TITLE
[INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

### ISSUE THREAD

**Issue by AlexUrrutia** [Gamua/Adobe-Runtime-Support#60]
## Problem Description

Describe your problem in detail. Include the following information:

**Can't test an empty project app on a real device using _armv8_ (MotoE5 Cruise), it throws this error:**

![Screen Shot 2019-07-03 at 10 46 48 PM](https://user-images.githubusercontent.com/7042361/60638706-0d6f9980-9de5-11e9-92df-3c5a499d8544.png)

* Which AIR SDK did you use? AIR 33.0.0.182
* Describe the affected environment: AIR ANDROID

## Steps to Reproduce

IntelliJ IDEA, File, New, Flash, Android, test.

## Known Workarounds

Use _**armv7**_

**Comment by ajwfrost** [comment]
Hi

Can you please check whether your phone has 32-bit or 64-bit Android running on it? See https://www.howtogeek.com/253461/how-to-find-out-if-your-device-is-running-32-bit-or-64-bit-android/ for instructions.

Then if you open the APK file within a zip application, can yon please confirm what folder name you see under the "lib" folder?

If the device is running 32-bit Android then the APK would need to have /lib/armeabi-v7a; if it's running 64-bit then it should be /lib/arm64-v8a

thanks

**Comment by AlexUrrutia** [comment]
Android 8.0.0 (32-bit)
![Screen Shot 2019-07-03 at 11 38 57 PM](https://user-images.githubusercontent.com/7042361/60640225-c1742300-9deb-11e9-8b79-1a6fd2e5d02f.png)

So, my question is, how do I package for both architectures? am I missing something?

**Comment by ajwfrost** [comment]
For each architecture - armv7, armv8, x86 - you need to create a separate package. These would have the same application ID, but internally they have different version codes as well as the different ABI support, which means the Play Store will work out which one is most suitable to the end user's device.

Given your error, and despite the handset using a 64-bit CPU, I'm wondering whether your build of the Android OS that it's running is actually a 32-bit one..

**Comment by AlexUrrutia** [comment]
Hi Andrew, I see, I have always packaged only 1 APK for my app, this is new for me, so I have to package 2 APK every time I make an update? interesting...

**Comment by ajwfrost** [comment]
If you'd supported x86 previously, you'd have been using two APKs, and then it would be three...
A couple of people have asked whether we could combine everything into a single APK. We'd just followed the existing tool's capabilities i.e. it works the same for ARMv8 as it does for x86, but we can look into what changes would be needed to package the whole lot together.

thanks

**Comment by AlexUrrutia** [comment]
**I guess this says it all:**

> _It is ok to have multiple APKs for single app split by resources or NDK libs, because it reduces APKs sizes. You can upload multiple APKs as single app at Android Play Store, it will select appropriate APK for user before installation._

I'm ok with it
