### ISSUE TITLE
Can not create 64bit binary with AIR SDK 33.0.0.182 that supported Android 64bit

### ISSUE THREAD

**Issue by fan-c-yu** [Gamua/Adobe-Runtime-Support#64]
## Problem Description

Describe your problem in detail. Include the following information:

* Which AIR SDK did you use? Hint: always try the latest version from [Adobe Labs](http://labs.adobe.com/downloads/air.html).
Adobe AIR SDK – for Mac 33.0.0.182 + Animate CC 2019 + macOS Mojave 10.14.5

* Describe the affected environment: Flash vs. AIR, Android vs. iOS, all devices vs. just specific models.
Android(for 64-bit ARM support)

* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?
I reproduce it yourself

* If applicable, link to the Starling/Feathers issues that brought you here.
Not sure if the same problem as https://github.com/Gamua/Adobe-Runtime-Support/issues/57.

## Steps to Reproduce

To support 64-bit ARM I tried these two methods in Release_Notes_AIR_SDK_33.0.0.182.pdf(4.1 and 4.2). Neither worked for me.

#### 4.1 AIR Developer Tool

I add `-arch armv8` into ADT command and get the error below when excute.
```
-arch must be followed by (armv7 | x86)
```

#### 4.2 ADT Architecture Configuration
I created adt.cfg which contains both of the following settings:
```
DefaultArch=armv8
OverrideArch=armv8
```
and placed in the SDK’s lib folder, alongside the adt.jar file. 
Then make the .apk file with ADT command. 
I find the .apk file did not supports 64bit.

<img width="423" alt="image" src="https://user-images.githubusercontent.com/17588286/60877932-b7ce3d80-a279-11e9-96c9-64ad9427b7cb.png">

Have to support 64-bit ARM, any advice to solve the problem?

**Comment by ajwfrost** [comment]
Hi

If you're seeing:
`-arch must be followed by (armv7 | x86)`
then it implies you're picking up an earlier version of the SDK, can you do `adt -version` to check what it says? Please check your path etc to ensure you're calling the ADT library from the v33 sdk.

On the config file, you don't need it if you're able to use the command line, but if you're using Animate then you'll probably want to use it.. please also add `DebugOut=false` into this file, otherwise it's not saving the earlier options..

thanks

**Comment by fan-c-yu** [comment]
@ajwfrost 
Hi

Thank you very much. Problem solved. 
I update the ADT path to SDK 33 and the adt.cfg as your suggestion.
the method `4.2 ADT Architecture Configuration' works for me.

Thanks

**Comment by jeuxdaily** [comment]
hello
this
<application xmlns="http://ns.adobe.com/air/application/32.0">

doesn't change to 33.0

how can I do this

**Comment by jeuxdaily** [comment]
> @ajwfrost
> Hi
> 
> Thank you very much. Problem solved.
> I update the ADT path to SDK 33 and the adt.cfg as your suggestion.
> the method `4.2 ADT Architecture Configuration` works for me.
> <img alt="スクリーンショット 2019-07-10 12 39 14" width="467" src="https://user-images.githubusercontent.com/17588286/60938692-d67f1380-a30f-11e9-96a9-b48b1cd472d4.png">
> 
> Thanks

please how do you slove your problem

thanks
