### ISSUE TITLE
Harman Packaged Browser site lock

### ISSUE THREAD

**Issue by veso266** [Gamua/Adobe-Runtime-Support#648]
Hi there, I was wondering how does Harman Packaged Browser site lock work

is there a mms.cfg or something similar so I can define my own domain in it, because for now Harman Packaged Browser is showing the flash content blocked image because I don't have the right domain

so where can I whitelist my domain then?
Thanks for Anwsering and Best Regards

**Comment by marchbold** [comment]
Please ask your questions in the discussion forum, the issue tracker is for us to report bugs in the AIR SDK.
