### ISSUE TITLE
Insatllation of singed AIR package or Signed native Installer not working on Windows (AIR SDK 33.1.1.345)

### ISSUE THREAD

**Issue by saggelopoulos** [Gamua/Adobe-Runtime-Support#658]
when try to install a AIR application exporting with "Signed AIR package" or "Signed native Package" there is an error.

The error is:
"The application requires an update to Adobe Air that is not available for your system."
where i cant find the updated AIR?

![Capture](https://user-images.githubusercontent.com/37022892/105689707-c5065800-5f03-11eb-8eb0-8f7ed2858b76.PNG)

**Comment by ajwfrost** [comment]
Please check:
https://airsdk.harman.com/runtime
