### ISSUE TITLE
Harman's AIR runtime - version 33.1.1.385 splash screen

### ISSUE THREAD

**Issue by balaedit** [Gamua/Adobe-Runtime-Support#667]
While opening my app, Harman's splash screen is appearing. I had licence of Harman's Air SDK. Why appearing on Desktop App?

Below Image : 

![HarmansSplashScreen](https://user-images.githubusercontent.com/37571867/106120847-e58d1700-617c-11eb-97dd-b4b0be5884cc.png)

**Comment by ajwfrost** [comment]
Can you check the license validity: if you go to your SDK and run from a command line from the 'bin' folder:
`adt -license`
then it should confirm if you have a license.

Have you installed the app via the shared runtime? in which case please check in the application folder, is there a file under the META-INF\AIR folder called "license.txt"?

Possibly it will be quickest if you can send us your app for us to install here and check..?
https://transfer.harman.com/requests/1ZeADxq0h4XuMAgqCH98cu

thanks

**Comment by balaedit** [comment]
Below image the setting for the Harman's AIR runtime - version 33.1.1.385 : 

![SDK_version_33](https://user-images.githubusercontent.com/37571867/106137427-b2548300-6190-11eb-8719-bee0a64cb55e.png)

After packing with Harman's AIR runtime - version 33.1.1.385 in **AIR build** getting error while installing the package :

![SDK_version_33_AirBuild_InstallError](https://user-images.githubusercontent.com/37571867/106137660-0495a400-6191-11eb-854b-50830d1576e0.png)

Packing the package with Harman's AIR runtime - version 33.1.1.385 in Windows Installer getting error while creating the package. Below image of error :

![SDK_version_33_EXEBuild_Error](https://user-images.githubusercontent.com/37571867/106137880-60602d00-6191-11eb-8fd6-27be79f9a0aa.png)

Packing with Adobe Air runtime version 32 as below image :

![SDK_version_32](https://user-images.githubusercontent.com/37571867/106138021-97364300-6191-11eb-909a-3663e2484ef1.png)

Installation is working proper but while running my App, Harman's splash screen is coming before app start :

![HarmansSplashScreen](https://user-images.githubusercontent.com/37571867/106138307-f7c58000-6191-11eb-9c69-c8839b666861.png)

**Comment by ajwfrost** [comment]
Hi
Thanks for those details. So if you're packaging using AIR SDK 32 then yes you'll see the splash screen. But the problem then is happening earlier on, with the packaging process from Animate.

You have two different errors mentioned above: so

1. when creating a .air output, and then trying to install this via the AIR runtime from Harman, you are getting a 'damaged' error. The .air file that you sent us seems to work fine to me, are you able to provide this one where you're seeing the 'damaged' error?

2. when trying to create a native bundle, it's failing with a Windows error 110 in EndUpdateResource - are you trying to get it to create an MSI file here, as I believe this is when it's been writing the MSI database, but we can check on that..

thanks

  Andrew

**Comment by balaedit** [comment]
Thanks for the earliest reply. Below discussion is regarding on **Harman's AIR runtime - version 33.1.1.385 SDK**.

1) When I package application of **.air** output, I get the **.air** output but while installing, I am getting error : **The application could not be installed because the installer file is damaged. Try obtaining a new installer file from the application author. Below is the image for reference.**

![SDK_version_33_AirBuild_InstallError](https://user-images.githubusercontent.com/37571867/106236227-64885b00-6222-11eb-8eb6-5b4f99666b83.png)

Packed **.air file (Air SDK version 33)** is shared on google drive : https://drive.google.com/file/d/17hGfTIuKQMwHsA9th4ZP2SqnO4-sOSBo/view?usp=sharing

2) While packing the application with **Window installer** getting error. Image of error detail is below : 

![SDK_version_33_EXEBuild_Error](https://user-images.githubusercontent.com/37571867/106236411-ce086980-6222-11eb-8069-85b60e23a968.png)

Requested you to solve my any one of the issue facing my me.

**Comment by ajwfrost** [comment]
Hi

I've just tried that AIR file, from the google drive file, but it installs fine for me. The message you've got there is what I would see if I dropped back to AIR 32 runtime though, as there's an expired certificate in AIR 32 now.

Are you able to confirm the version of the AIR runtime DLL in the below folder, via right-click -> Properties -> Details?
`C:\Program Files (x86)\Common Files\Adobe AIR\Versions\1.0`

For the packaging via Animate, we'll look further into that.

In all of this though, I am just wondering whether we may be getting hit by anti-virus quarantines; one of the team here just found one of the tools had stopped working and it turns out this was being quarantined by Symantec. Is it possible to check your AV program to see if it's prevented anything from being run recently?

thanks

   Andrew

**Comment by balaedit** [comment]
Hi Sir,

Below is the image of **Adobe Air Runtime DLL** detail :

![AirDLLversion](https://user-images.githubusercontent.com/37571867/106349843-4b9da980-62f7-11eb-9131-a24a9a81e680.png)

As you told to disable the antivirus (NPAV Antivirus in my case), I did and it's working fine. Thanks.

Why Antivirus not allowing the **.air** installation package to install my app?

**Comment by ajwfrost** [comment]
Annoyingly a lot of antivirus software seems to ignore the code-signing certificates, and base their decisions upon how common certain binaries are. So as soon as we build a new binary, it means that AV software won't recognise as a commonly-used (and therefore "safe") application.
We're looking at how we can persuade these companies to mark things as 'safe' but currently from what I can see, every different company has a different scheme in place for this sort of thing..
