### ISSUE TITLE
AIR 33.1.1.406 iOS IPA failed to install

### ISSUE THREAD

**Issue by pavelzmolik** [Gamua/Adobe-Runtime-Support#694]
## Problem Description

Hello, I downloaded the newest AIR SDK 33.1.1.406 and try compile IPA files for iOS. After compilation i tried install the app on the device to test it. But after copy into device app is not installed. App is not to able to run. It has no icon even I have correct assets in the app.

## Steps to Reproduce

I just try to compile with SDK for Windows and SDK for Mac, and the result is the same. When I compile with the older verision everything is all right.. I try get some digging at the MacOS Terminal, ale found one difference between the newest and the older version.. You can see it at this image
[https://www.pavelzmolik.cz/dl/terminal.png](https://www.pavelzmolik.cz/dl/terminal.png)

there is a difference at the green underlined lines.. I think the version 406 has some bug and doesn't index the resources of the app although it packed it into IPA file. But if I check it by codesign command at the version 406 it doesn't show any. At the older version it shows correctly as you can see.
Btw when I look to codeDirectory version there is 20200 again same as verison 33.1.1.345. 

Please try fix this issue as soon as possible or show me what I do wrong.

## Known Workarounds

Only workaround is using older SDK version (33.1.1.345, is OK)

Thanks and best regards
P.Zmolik

**Comment by ajwfrost** [comment]
Hi

This is related to #511 I believe, it's using a new format for the code directory but it looks like there's an issue with this even when using old certificates. I am coming to the conclusion that we will need two completely separate sets of actions depending on whether someone has an older certificate or a new one that was issued by the newer intermediate CA..

You'd need to re-sign it I'm afraid which is only feasible on MacOS. See instructions at
https://github.com/Gamua/Adobe-Runtime-Support/issues/511#issuecomment-741844598

We have pretty much completed the analysis of the code-signing tool and know the final few steps that need to be put in place to get the code signing details correct.. so we now just need to implement that..!

thanks
  Andrew

**Comment by pavelzmolik** [comment]
[https://github.com/Gamua/Adobe-Runtime-Support/issues/511#issuecomment-785487450](https://github.com/Gamua/Adobe-Runtime-Support/issues/511#issuecomment-785487450)

this problem is fixed by updated ADT.jar so i am closing this issue, hope new public version will be released as soon as possible
thx guys!
