### ISSUE TITLE
ADT error 303: Icon banner320x180.png is missing from package when packaging tvOS

### ISSUE THREAD

**Issue by joshtynjala** [Gamua/Adobe-Runtime-Support#7]
## Problem Description

AIR SDK 26.0.0.118

When I package a tvOS app with ADT, I get the following error.

> ADT error 303: Icon banner320x180.png is missing from package when packaging tvOS

I have an app that I'm developing for both Android TV and tvOS. In my AIR application descriptor, I have a `<banner>` field inside the `<android>` section. This specifies the Android TV banner.

When I package with `apk-captive-runtime`, I include the PNG file in my command line options, and it works fine. However, when I package with `ipa-app-store`, I don't include the PNG file in my command line options because it's not needed on tvOS. I get the error.

Because the `<banner>` field is inside the `<android>` section, it should be ignored when not targeting Android. If the `<banner>` field cannot be be ignored when packaging a tvOS app (or an app for any other platform), it should be moved outside the `<android>` section to avoid confusion. Based on the error message, it seems to be treated like an icon, so the `<icon>` section is a good candidate.

[AIR-4198396](https://tracker.adobe.com/#/view/AIR-4198396)

## Steps to Reproduce

ADT command for tvOS that fails:

adt -package -target ipa-app-store -provisioning-profile path/to/profile -keystore path/to/keystore -storetype pkcs12 -storepass ABC123 SmartTV.ipa source/SmartTV-app.xml SmartTV.swf

AIR application descriptor:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<application xmlns="http://ns.adobe.com/air/application/26.0">
	<id>com.feathersui.examples.SmartTV</id>
	<filename>Smart TV</filename>
	<name>Smart TV</name>
	<versionNumber>3.4.0</versionNumber>
	<description>Smart TV example application built with Feathers UI controls for Starling</description>
	<copyright>2017 Bowler Hat LLC</copyright>

	<initialWindow>
		<content>SmartTV.swf</content>
		<autoOrients>true</autoOrients>
		<fullScreen>true</fullScreen>
		<visible>true</visible>
		<renderMode>direct</renderMode>
	</initialWindow>

	<supportedLanguages>en</supportedLanguages>

	<android>
		<supportsAndroidTV>true</supportsAndroidTV>
		<banner>banner320x180.png</banner>
		<manifestAdditions><![CDATA[
			<manifest android:installLocation="auto">
			    <uses-permission android:name="android.permission.INTERNET"/>
			</manifest>
		]]></manifestAdditions>
	</android>
	<iPhone>
		<InfoAdditions>
		<![CDATA[
			<key>UIDeviceFamily</key> 
			<array> 
				<string>3</string>
			</array>
		]]> 
		</InfoAdditions>
		<requestedDisplayResolution>high</requestedDisplayResolution>
	</iPhone>
</application>
```

## Known Workarounds

Workaround 1: Comment out `<banner>` temporarily.

Workaround 2: Include the extra PNG file when packaging, even though it is useless on tvOS

**Comment by Ankit-Adobe** [comment]
[AIR-4198396](https://tracker.adobe.com/#/view/AIR-4198396) has been fixed in AIR SDK 28. Please download latest AIR SDK 28.
Thanks,
Ankit | Adobe AIR Engineering
