### ISSUE TITLE
macOS BigSur App Crashes asking Microphone Permission AIR 33.1.1.406

### ISSUE THREAD

**Issue by apofis1969** [Gamua/Adobe-Runtime-Support#709]
## Problem Description
On macOS Big Sur the app crashes completely when asking the permission for the Microphone with the new entitlement codesign used for the camera permission.
`codesign --entitlements myapp.plist  -s "Apple Distribution: XXXXXXXXXXXXX" -f -o runtime --strict --timestamp --deep -v MyApp.app `
Please see the attached bug report and screenshot before asking mic permission.
[CrashReportMicPermission.txt](https://github.com/Gamua/Adobe-Runtime-Support/files/6056793/CrashReportMicPermission.txt)
<img width="829" alt="Screenshot 2021-02-28 at 09 03 08" src="https://user-images.githubusercontent.com/25087613/109418522-8f8fd700-79a7-11eb-904e-b469c3035f21.png">

## Known Workarounds
Using a different entitlement codesigning: `codesign -f -v -s "Apple Distribution: XXXXXXXXX" --entitlements myapp.plist MyApp.app.`
But then the permissions have to be asked each time the app will be activated by the user, because Big Sur does not save the permissions. Camera and Microphone are not available without asking for permission in the background when starting the app.

Microphone and Camera Permissions are basic requirements and should work without crashes and workarounds.
Adobe Air should realise if the macOS is BigSur or not, because on Catalina e Mojave the permissions for Camera and Microphone are working different.

**Comment by apofis1969** [comment]
I have to correct myself. The same problem with macOS Catalina. Also only works with `codesign -f -v -s "Apple Distribution: XXXXXXXXX" --entitlements myapp.plist MyApp.app` and asking the permissions each time the app opens in the background.

**Comment by apofis1969** [comment]
@ajwfrost macOS is still crashing with 33.1.1.444 when asking Microphone permission using this code:
`codesign --entitlements myapp.plist -s "Apple Distribution: XXXXXXXXXXXXX" -f -o runtime --strict --timestamp --deep -v MyApp.app`
Is there now an other procedure necessary?
With this code the permissions are working, but have to be asked each time the app opens in the background after the first installation.
`codesign -f -v -s "Apple Distribution: XXXXXXXXX" --entitlements myapp.plist MyApp.app.`

**Comment by ajwfrost** [comment]
@apofis1969 so just to confirm here, you're using the same entitlements list in both of those signing commands? the difference then being due either to 'strict' or to '-o runtime' (which is the more likely I think)?

Do you entitlements include the microphone permission, and has your application descriptor file got the microphone notification string on it?

I'll get someone to extract and package up our test case for this..

thanks

**Comment by apofis1969** [comment]
@ajwfrost this is the macOS addition:
`<macOS>
    <InfoAdditions><![CDATA[<key>NSMicrophoneUsageDescription</key>
	<string>Please allow the app to use the microphone of your device to hear your pet and talk to your pet</string>
	<key>NSCameraUsageDescription</key>
	<string>Please allow the app to use the cameras of your device to monitor your pet</string>]]></InfoAdditions>
  </macOS>`
Also is in the info.plist
if I build the app with `codesign --entitlements myapp.plist -s "Apple Distribution: XXXXXXXXXXXXX" -f -o runtime --strict --timestamp --deep -v MyApp.app` the app crashes
if I build with `codesign -f -v -s "Apple Distribution: XXXXXXXXX" --entitlements myapp.plist MyApp.app` the app works

**Comment by ajwfrost** [comment]
Okay thanks @apofis1969  - just checking that it's a copy/paste bug, but your Info.plist description above has got:
```
<key>NSMicrophoneUsageDescription</key>
<string>Please allow the app to use the microphone of your device</string>
<key>NSCameraUsageDescription</key> to monitor your pet</string>
```
whereas I hope it actually says:
```
<key>NSMicrophoneUsageDescription</key>
<string>Please allow the app to use the microphone of your device</string>
<key>NSCameraUsageDescription</key>
<string>Please allow the app to use the cameras of your device</string>
```

Could you please try:
```
codesign --entitlements myapp.plist -s "Apple Distribution: XXXXXXXXXXXXX" -f --strict --timestamp --deep -v MyApp.app
```
and if this still crashes, could we please get the app to inspect here?

Meanwhile I'll ask someone to see if they can reproduce the same here...

**Comment by apofis1969** [comment]
@ajwfrost hi, it is working with the new codesign line, but the app has to ask at each start the permissions on catalina and big sur. but for me it is ok. I will close this threat and have to open another because there is a bug at Android 33.1.1.444
The app does not connect to the server and sends the error message, that there is no internet connection.
