### ISSUE TITLE
iOS Fullscreen not working with paid license

### ISSUE THREAD

**Issue by CCC200** [Gamua/Adobe-Runtime-Support#710]
## Problem Description
While testing on iOS devices, the application cannot enter fullscreen if a paid `adt.lic` file is provided. 

Using latest AIR SDK (**33.1.1.406**), tested with several older versions as well.
Using latest iOS release (**14.4**)
Compiling using Adobe Animate 2019.

[Link to issue on Adobe Tracker](https://tracker.adobe.com/#/view/AIR-4198947)

## Steps to Reproduce
Compile app for iOS using paid license from Harman, and install via USB on device.

## Actual Result
Top & bottom bar with network info, name, battery etc is always visible, regardless of fullscreen settings. 
![No Fullscreen](https://i.imgur.com/06brfJf.png)

## Expected Result
Top & bottom bar will not be visible with fullscreen enabled, and application will take up entire screen.
![With Fullscreen](https://i.imgur.com/DXkSkRq.png)

## Known Workarounds
Remove license and compile using trial version.

**Comment by marchbold** [comment]
Are you supplying a custom launch screen? Sounds like an issue there.

**Comment by CCC200** [comment]
> Are you supplying a custom launch screen? Sounds like an issue there.

Hi, yes I did include a `Default.png` launch image, it did not make a difference. Additionally, I'm not sure why the trial version would ignore this requirement. Seems to be an issue with the SDK license, as that's the only variable difference between the 2 screenshots I provided.

**Comment by FliplineStudios** [comment]
Have you tried using a LaunchScreen storyboard instead of a launch image?  We haven't had issues like this in any of the recent SDK releases, but we do use a storyboard instead of launch images once Apple made the storyboard mandatory.  I believe Harman's splash is using a LaunchScreen storyboard these days, so it may expect a storyboard (and not just launch images) in order to override it correctly when you have a license.

**Comment by marchbold** [comment]
FYI: http://docs.airnativeextensions.com/docs/tutorials/ios-launchscreens

**Comment by CCC200** [comment]
Thank you both very much, I was unaware of this change as I am new to publishing on iOS. I will close my issue 😊
