### ISSUE TITLE
Unable to Deliver IPA to App Store, getting ERROR ITMS-90034: "Missing or invalid signature"

### ISSUE THREAD

**Issue by robertsayegh1** [Gamua/Adobe-Runtime-Support#737]
## Problem Description

While using the latest available version of Air SDK version 33.1.1.406 to compile and package my app, I am unable to deliver my IPA to the app store, I am getting the below error: ERROR ITMS-90034: "Missing or invalid signature. The bundle 'xxx.xxxx.com' at bundle path 'Payload/Bridgestone mobile.app' is not signed using an Apple submission certificate."

Hope to find a solution for that.

Thanks 

* Which AIR SDK did you use? Hint: always try the latest version from [Adobe Labs](http://labs.adobe.com/downloads/air.html).
* Describe the affected environment: Flash vs. AIR, Android vs. iOS, all devices vs. just specific models.
* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?
* If applicable, link to the Starling/Feathers issues that brought you here.

Furthermore, **always** add a link to one or more analog [Adobe Tracker](https://tracker.adobe.com) issues. This repository is not a replacement for Adobe's bug tracker!

## Steps to Reproduce

Tell us how this issue can be reproduced. Seriously: if you want this issue to be fixed, this is the part you **really** need to get nailed.
Give us a minimal example:

* As little code as possible. Get to the root of the problem!
* As few dependencies as possible. Did the problem pop up with Feathers? Try to reproduce it with Starling only.
* Remove any ANEs (except if they are vital for the problem).
* Include all necessary files (e.g. textures).

## Known Workarounds

Just in case others run into this – do you happen to know of a workaround? Otherwise, just remove this section altogether.

**Comment by marchbold** [comment]
Duplicate #676

**Comment by marchbold** [comment]
@robertsayegh1 I'd suggest adding any additional information you have to that issue to help Harman isolate the issue you are having.
