### ISSUE TITLE
SQLite compact() doesn't work on remote computer

### ISSUE THREAD

**Issue by pol2095** [Gamua/Adobe-Runtime-Support#747]
## Problem Description

SQLConnection.compact() doesn't working when the database file is on another computer ?
//othercomputer/test/base.db

* AIR SDK 33.1
* Air for Windows (only tested)
* link to the [Starling forum](https://forum.starling-framework.org/d/22991-sqlite-compact-and-remote-computer)

## Known Workarounds

copy the file on the computer, compact, copy the file on the remote computer

**Comment by ajwfrost** [comment]
Hi @pol2095 

We've looked into this - our test on a local network worked. Code snippet was below.
```
      conn = new SQLConnection();               
      var folder:File = new File("//server_ip_address/Share");
      var dbFile:File = folder.resolvePath("test.db");

      try 
      { 
            conn.open(dbFile, SQLMode.UPDATE); 
            trace("the database opened successfully"); 
            conn.compact();
      } 
      catch (error:SQLError) 
      { 
            trace("Error message:", error.message); 
            trace("Details:", error.details); 
      }
```

I think if it's not working for you, this may be something related to Windows file handling/permissions perhaps? or see the below issue:
https://www.sqlite.org/faq.html#q5

But also, given there is a workaround here, I'm not sure whether there's anything further that we could do. The workaround is something that could be added in a few lines of ActionScript in the 'catch' block.

thanks

**Comment by pol2095** [comment]
Thanks, I tried on a Linux server and it work.
