### ISSUE TITLE
ios app crash with Attempt to add an app with insufficient id

### ISSUE THREAD

**Issue by idanasher** [Gamua/Adobe-Runtime-Support#752]
i have managed to publish\compile my ios app in **development** mode via animate  with AIR SDK 33.1.1.406 + patched adt.

i then went to my mac and used xcode > devices and install the app on my iphone6.

when opening the app I see the harman splash and it immediately crashes.

the logs shows this:

Attempt to add an app with insufficient id, info {
    BKSApplicationStateAppIsFrontmost = 1;    BKSApplicationStateExtensionKey = 0;
    SBApplicationStateDisplayIDKey = "com.pkama.rummyworld";
    SBApplicationStateKey = 8;
    SBApplicationStateProcessIDKey = 1564;
    SBMostElevatedStateForProcessID = 8;
}

Animate 2020  on Windows 10
Xcode 12.4 (12D4e) on macOS Bug Sur Version 11.2.3

I have created new certificates last month on the beginning of february.

**Comment by ajwfrost** [comment]
Hi @idanasher  - could you please share the output of 
```
codesign -dvvvvv appname.ipa
```
thanks

**Comment by idanasher** [comment]
Where do i run this command?

**Comment by ajwfrost** [comment]
If you open a terminal window and then navigate to the folder where Animate had placed your IPA file, e.g.
```
cd /Users/username/AnimateProject/output
```
basically it needs to be so that if you run the `ls` command, you see the .ipa file in the results..
thanks

**Comment by idanasher** [comment]
ok, so when I ran this command I get

code object is not signed at all

**Comment by idanasher** [comment]
(I develop via animate on window 10 pc then I take the ipa to my mac)

**Comment by ajwfrost** [comment]
Thanks, I was about to wonder how on earth that happened when I realised I missed a step as the IPA files are just archives that contain the app!

So could you please first do:
unzip appname.ipa
And then 
codesign -dvvvvv Payload/appname.app

Actually it might be useful too if you’re able to send us the ipa file..?

thanks

**Comment by idanasher** [comment]
this is what I get when using this command

codesign -dvvvvv Payload/appname.app

Identifier=com.pkama.rummyworld

Format=app bundle with Mach-O universal (armv7 arm64)

CodeDirectory v=20400 size=333368 flags=0x0(none) hashes=10409+5
location=embedded

VersionPlatform=2

VersionMin=589824

VersionSDK=917760

Hash type=sha256 size=32

CandidateCDHash sha1=0ee0fdbcec235ba74912a7720c371075ab47a199

CandidateCDHashFull sha1=0ee0fdbcec235ba74912a7720c371075ab47a199

CandidateCDHash sha256=1db6ed038993f14c4673f4bb8800fed119f8fab3

CandidateCDHashFull
sha256=1db6ed038993f14c4673f4bb8800fed119f8fab31761d884c04afe43f247ce91

Hash choices=sha1,sha256

CMSDigest=73aa02b1679c2d41916c5b19b59f292fc2b85155e99a973473321e1dddf957a1

CMSDigestType=2

Executable Segment base=0

Executable Segment limit=31506432

Executable Segment flags=0x11

Page size=4096

CDHash=1db6ed038993f14c4673f4bb8800fed119f8fab3

Signature size=4840

Authority=iPhone Developer: Edan Asher (9V5E6XCH5N)

Authority=Apple Worldwide Developer Relations Certification Authority

Authority=Apple Root CA

Signed Time=25 Mar 2021 at 13:56:06

Info.plist entries=66

TeamIdentifier=5YJ86YH26C

Sealed Resources version=2 rules=10 files=367

Internal requirements count=1 size=180

**Comment by idanasher** [comment]
Hi Andrew
Any progress with this ?

**Comment by idanasher** [comment]
Hi Andrew
Any progress with this ?

**Comment by ajwfrost** [comment]
Hi @idanasher  - sorry for the delay; the code-signing looks fine for a developer build, but I want to check the IPA in case there's something in there such as improperly formatted entitlements (shouldn't be an issue afaik but there were previous bugs caused on Windows by \r\n pairs..). We'll also check the signing of the included frameworks/libraries..

Do you also have a "working" version of this app from a previous SDK build, or from any earlier point e.g. with your old certificates from last year? it would be good to compare against this..

thanks

**Comment by idanasher** [comment]
Hi Andrew and thank you for your help.

I am now sending you the ipa from last year.
i think it is the latest production ipa version, compiled with a
previous sdk version and old version of my ane's.

Thank you so much
Edan

 logic_rummy_world.ipa
<https://drive.google.com/file/d/1cbXbBKtxPSxsQcGLkV-Nd_vPd1q5n5t5/view?usp=drive_web>

**Comment by ajwfrost** [comment]
Hi

Thanks for those .. so there are a fair few differences between those IPA files! Obviously the old one is a distribution package and the new is signed with "iPhone Developer". The entitlements looked okay although this new one is restricting to 64-bit phones, but that should still work with your iPhone 6.

There are a large number of imports and new functions in the updated application so I am wondering if there are problems with something there - things I know have changed recently include the sqlite usage and also fd_set for socket usage, so we'll double-check that we see the same with test apps (and that they run on iPhone 6..)

I'm wondering whether the best approach here might be to strip back the functionality until it start working so that we can narrow down the area - currently there's nothing obvious that's wrong with it and the code-signing is all seemingly okay. It might be that there's some functionality in there that's requiring an extra entitlement, or a specific iOS version, etc.. - first thing to do perhaps is to eliminate the ANEs as then you can see whether it's a problem in a dependency vs something built-in..

Sorry it's not a quick-fix that we can apply from here!

thanks

**Comment by idanasher** [comment]
Haleluya  !
  
After looking at the crash log  I realized there is a problem with the 'FBSDKLoginKit'  (facebook distriqt's ane library)

so i took another look and saw that the Framework directory was somehow not included in the project.

After including this properly, the app is opening without this crash !

Before closing this tread, just one more question.
You wrote:
"The entitlements looked okay although this new one is restricting to 64-bit phones"

So if I remove this following entitlement it should be to all devices ,  right ?

<key>UIRequiredDeviceCapabilities</key>
<array><string>arm64</string></array>


Thank you Andrew so much for your help & Good intentions.

**Comment by ajwfrost** [comment]
Great! well found :-)

Re that arm64 required capability, yes that would cause what we were seeing - not sure whether you have anything that requires this or not.. there are fewer and fewer Apple devices around that don't have 64-bit support though, so you're probably not missing much..

Are you okay if we close this ticket then?

thanks

**Comment by idanasher** [comment]
Yes, go ahead.
