### ISSUE TITLE
Amazon Store : I have to upload one of my app on Amazon Play store

### ISSUE THREAD

**Issue by balaedit** [Gamua/Adobe-Runtime-Support#762]
I had created the simple app and tried to upload on amazon store but it says it is not compatible will all the amazon tv. Screenshot is attached. Please resolve the issue if I am doing some wrong.

![Amazon](https://user-images.githubusercontent.com/37571867/113270922-9a67bf80-92f7-11eb-9a58-5c53603ca22f.png)

**Comment by marchbold** [comment]
If you go into "View" and find the Fire TV devices the "?" beside the devices should give you some information as to why they are being flagged as not supported.

**Comment by balaedit** [comment]
I have checked the manifest detail on Amazon Playstore and shared the image below : 

![Amazon1](https://user-images.githubusercontent.com/37571867/113709791-8d383f80-9700-11eb-98d7-5d491da48377.png)

external link in the red rectangle are as follows : https://developer.amazon.com/docs/fire-tv/remote-input.html

Please check it.

Thanks.

**Comment by ajwfrost** [comment]
Just checking that you have a ```supportsAndroidTV``` setting within your AIR application descriptor file..?

**Comment by marchbold** [comment]
@balaedit Check the details that show when you hover over the "?"

**Comment by balaedit** [comment]
Just checking that you have a supportsAndroidTV setting within your AIR application descriptor file..?  How to add this setting in descriptor.

Check the details that show when you hover over the "?". I had checked this pop-up. It say's that "Your apk manifest required capabilities not present on this device i.e. android.hardware.location.gps". 

I resolved that gps issue by removing that from the manifest. but error is still appearing that 

"To support Fire TV devices, your app should work with [Amazon controllers](https://developer.amazon.com/docs/fire-tv/remote-input.html), [Display well on TV devices](https://developer.amazon.com/docs/fire-tv/display-and-layout.html) and [Handle multimedia correctly](https://developer.amazon.com/docs/fire-tv/multimedia-app-requirements.html). Without support for these requirements, your app will fail testing and your launch on the Appstore will delayed."

Above links are the same error links, I got.

**Comment by ajwfrost** [comment]
@balaedit for the `supportsAndroidTV` and `banner` settings, please see
https://community.adobe.com/t5/flash-player/12-12-2017-release-air-28-runtime-and-sdk/m-p/9614385

**Comment by balaedit** [comment]
Thanks,

I updated the manifest file with adding tags given below. Below tags are added in between of <android> tag.

<supportsAndroidTV>true</supportsAndroidTV>
<banner>AppIconsForPublish/banner.png</banner>

But during publishing I am getting error "Error creating files. Icon file is missing". 

I am using latest AIR SDK 33.1.1.444 and animate CC 2021 for publishing.

![error](https://user-images.githubusercontent.com/37571867/114292892-75b9d780-9aaf-11eb-903f-cb7a82ed732b.png)

**Comment by balaedit** [comment]
Hi Sir, 
@ajwfrost or @marchbold, I am closing this issue as I had created discussion query of this issue.
