### ISSUE TITLE
33.1.1.444 -- res/drawable/--  Invalid file name: must contain only [a-z0-9_.]

### ISSUE THREAD

**Issue by urthling** [Gamua/Adobe-Runtime-Support#767]
I'm seeing the following failure on Android with .444 release.  If I roll back to an updated ADT that fixed the IPA signing issues 03/19 -- all is well.

```
aapt tool failed:res/drawable/banner 2.png: Invalid file name: must contain only [a-z0-9_.]
res/drawable/mp_warning_32x32_n 2.png: Invalid file name: must contain only [a-z0-9_.]
res/drawable-xhdpi-v4/ouya_icon 2.png: Invalid file name: must contain only [a-z0-9_.]
res/mipmap-ldpi-v4/icon 2.png: Invalid file name: must contain only [a-z0-9_.]
res/mipmap-mdpi-v4/icon 2.png: Invalid file name: must contain only [a-z0-9_.]
res/mipmap-hdpi-v4/icon 2.png: Invalid file name: must contain only [a-z0-9_.]
res/mipmap-xhdpi-v4/icon 2.png: Invalid file name: must contain only [a-z0-9_.]
res/mipmap-xxhdpi-v4/icon 2.png: Invalid file name: must contain only [a-z0-9_.]
res/mipmap-xxxhdpi-v4/icon 2.png: Invalid file name: must contain only [a-z0-9_.]
res/layout/main 2.xml: Invalid file name: must contain only [a-z0-9_.]
res/xml/provider_paths 2.xml: Invalid file name: must contain only [a-z0-9_.]
res/raw/debugger 2.info: Invalid file name: must contain only [a-z0-9_.]
```	

I do notice mention of Android App Bundles under 'Known Problems' of the release notes, assuming this might be related?

**Comment by marchbold** [comment]
That looks like you have duplicated resources in the AIR SDK somehow, potentially when overlaying over an existing SDK?

Try a clean copy of the AIR SDK.

**Comment by urthling** [comment]
Ah, interesting, ok, trying now!

**Comment by LarsLaborious** [comment]
Harman has the following note on their download page: "NOTE for anyone extracting this release over the top of a previous one, please delete the old 'MainWindow.nib' and 'MainWindow-iPad.nib' files from your old SDK location prior to copying the new files. These names are now used as folder names so you would get an error "Missing objects-13.0+.nib" if these did not copy properly."

**Comment by urthling** [comment]
I did do a partial copy/merge before removing the the two .nib files and then continued with the overlay -- which caused the extra resource files.  so my bad!  All is well with a fresh SDK and overlay.
