### ISSUE TITLE
Silent crash on Android 4.4.2 (33.1.1.444)

### ISSUE THREAD

**Issue by sjabberwocky** [Gamua/Adobe-Runtime-Support#780]
I built our game with AIR 33.1.1.444 and it works okay on Android 8.1.0 and Android 10.
Unfortunately, on Android 4.4.2 we have silent crash on start after launch image without any logs in logcat.

On AIR 33.1.1.406 our game works fine on Android 4.4.2.

**Comment by ajwfrost** [comment]
Hi
Looks like we have a third party component that was updated that's giving us a problem on older Android versions - we're just seeing if we can rebuild this to allow it to work with 4.4.2 otherwise we will revert that change for the short term..
thanks

**Comment by P2b10** [comment]
Same issue with Android 6.0 and 6.1

It works fine on Android 10

**Comment by ajwfrost** [comment]
Can I please check whether this is an armv7 or armv8 binary that's causing the problems?

**Comment by sjabberwocky** [comment]
It's armv7 on Android 4.4.2.

**Comment by belka-mobile-dev** [comment]
We want to update to version (33.1.1.444)
We see this problem, did you analyze it?
A problem for everyone?

**Comment by glushko** [comment]
> Hi - we've just found the issue here which was a change to the ndk level due to an updated dependency -> caused a reliance on a function that's not in the libraries on older handsets. It looks like we have a workaround for this and can sort this out in the next release which we'll kick off as soon as we've sorted out the https problems on the 64-bit platforms..

Thank you.
The https problem is long ago and we learned how to work with it. But with the problem of starting the game, it is very painful.
It is possible to think about priorities
(I may be wrong, but these are my thoughts on the android)

**Comment by ajwfrost** [comment]
@glushko @sjabberwocky this is fixed now and released in 33.1.1.476
thanks
