### ISSUE TITLE
Adobe Air 33.1.1.444 not loading Pandora.air

### ISSUE THREAD

**Issue by dlschwerin** [Gamua/Adobe-Runtime-Support#792]
pulled adobe air 33.1.1.444 from the harman website and receiving error "The application could not be installed because the installer file is damaged. Try obtaining a new installer file from the application author."

the previous adobe air version was able to load the pandora.air package, so unsure what happened with this build?

**Comment by balaedit** [comment]
Disabled antivirus and it will working fine.
