### ISSUE TITLE
Unable to build iOS Package 

### ISSUE THREAD

**Issue by Shaunmax** [Gamua/Adobe-Runtime-Support#796]
I just migrated my project from my old mac to a new mac & unable to build iOS package as I am getting the following error

![image](https://user-images.githubusercontent.com/16576562/115125167-075fa280-9fe4-11eb-9b3c-18ae6eed5d18.png)

Everything works fine on my old mac with Catalina OS, the new mac also has the same OS but throws error 

Please help & let me know what changes needs to be made?

**Comment by ajwfrost** [comment]
What's your Java version there? The code-signing stuff uses the internal security classes from the sun/oracle JVM so it looks like it's something to do with this..

**Comment by Shaunmax** [comment]
> What's your Java version there? The code-signing stuff uses the internal security classes from the sun/oracle JVM so it looks like it's something to do with this..
![image](https://user-images.githubusercontent.com/16576562/115126463-cddf6500-9fec-11eb-839c-47743c9bb6c4.png)

**Comment by ajwfrost** [comment]
Okay so that looks fine ... but, what are you using to package up the application with? The initial error shows a dialog with the error report headed "Create iOS Package". I would guess that whatever this is, it's launching ADT into a Java environment that's not the same as the official/Oracle version that you have there... Are you able to build from the command line so that you pick up this 1.8.0 build of Java?

thanks

**Comment by Shaunmax** [comment]
> Okay so that looks fine ... but, what are you using to package up the application with? The initial error shows a dialog with the error report headed "Create iOS Package". I would guess that whatever this is, it's launching ADT into a Java environment that's not the same as the official/Oracle version that you have there... Are you able to build from the command line so that you pick up this 1.8.0 build of Java?
> 
> thanks

Ok, I just installed the below jdk inside intellij and everything is working fine! 

![image](https://user-images.githubusercontent.com/16576562/115127519-b5734880-9ff4-11eb-9a96-437c0e105e5e.png)

Thanks for the help! 
Appreciate it!
