### ISSUE TITLE
AIR app rotation broken on iOS 11 Beta 3 when using -platformSDK

### ISSUE THREAD

**Issue by tuarua** [Gamua/Adobe-Runtime-Support#8]
## Problem Description
Using AIR SDK 26 on any iOS device with iOS 11 Beta 3 installed.

Rotate device into landscape mode.
App doesn't rotate and is now upside-down. Clicking home button and reopening corrects the orientation but the stage position is now mostly offscreen and reveals the splash screen underneath

[https://tracker.adobe.com/#/view/AIR-4198406](https://tracker.adobe.com/#/view/AIR-4198406)

## Steps to Reproduce

1) Use device with iOS 11 beta 3 installed
2) Specify -platformSDK as iOS SDK included with Xcode 8.3 (or Xcode 9.0) /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
3) Launch basic sample app from https://github.com/tuarua/iOS-11-beta3-rotation-bug

## Known Workarounds

None

This may well be an iOS bug and although iOS 11 is still in beta I believe this behaviour should be tracked in case it is a core change in iOS. I would like to implement ANEs for ARKit, PDFKit, Vision and this is now preventing me.

**Comment by tuarua** [comment]
Update - Problem still persists in Beta 4

**Comment by tuarua** [comment]
Update - Problem still persists in Beta 5

**Comment by hardcoremore** [comment]
Is this fixed in latest AIR  27 beta from August 23?

**Comment by tuarua** [comment]
I retested using iPad Pro and I still saw the issue.
N.B. This issue only occurs if you use -platformSDK try with an iOS SDK greater than the one included with AIR (> 10.1)
If you commit -platformSDK there is no problem

**Comment by Warface** [comment]
Pretty sure that's because AIR haven't updated their iOS SDK to 11 yet...

**Comment by tuarua** [comment]
AIR 28 beta (with it's upgrade to iOS 11 SDK) appears to have fixed this issue
