### ISSUE TITLE
adt - unable to install ipa on iPadOS 13 Beta 8

### ISSUE THREAD

**Issue by tuarua** [Gamua/Adobe-Runtime-Support#86]
## Problem Description
iOS 13 is now split into 2 versions, 1 for iPhone, 1 for iPads. The iPads OS will be called "iPadOS" from version 13 onwards. With this name change adt is unable to install apps. Assumption being that adt code is unable to handle the os name change

```
adt -installApp -platform ios -device 4 -package /Users/Example.ipa 
Error connecting to your device!
```

`adt -devices -platform ios`
works OK

Describe your problem in detail. Include the following information:

* Which AIR SDK did you use? 
33.0.1.220
* Describe the affected environment: 
AIR iOS on iPad Pro 10.5 with iPadOS 13 Beta 8 installed
* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?
Will affect developers with iPads who upgrade to iPadOS 13 (unable to install iOS on iPads from 13 onwards) iPadOS is due for **release mid September**

## Steps to Reproduce

* Install iPadOS 13 Beta on iPad 
* Run adt -devices -platform ios
* adt -installApp -platform ios -device 4 -package /Users/Example.ipa 

## Known Workarounds
ipa can be compiled and installed using Xcode and runs OK - but unable to debug from IDE or using adt

**Comment by tuarua** [comment]
Note: This may not be confined to iPadOS but affecting iOS 13 also. I have no way to confirm as I only own iPads and don't have an iPhone to confirm issue is not observed with iOS 13 Beta there.

The error is generated by lib/aot/bin/iOSBin/idb which is called by adt.

eg This results in same error
`/Users/AIRSDK/lib/aot/bin/iOSBin/idb -install /Users/project/bin-release/device/Example.ipa 4`

Looks like iOSBin is derived from components of this project.
https://github.com/libimobiledevice

**Comment by tuarua** [comment]
EDIT: confirmed this also affects iOS 13 Beta on iPhone

**Comment by nanhuichen** [comment]
I got the same issue on iPhone7.

**Comment by ajwfrost** [comment]
Hi all

We're aware of this one, and are looking into it, hope to have a fix pushed out before too long. I believe it's possible to download the apps via an old version of iTunes, or via Xcode, as a temporary workaround..

thanks

**Comment by tuarua** [comment]
Fine for me now in .288
