### ISSUE TITLE
[Android][iOS] Read "position" property of the async opened FileStream after writing data from Socket cause application crash

### ISSUE THREAD

**Issue by itlancer** [Gamua/Adobe-Runtime-Support#97]
## Problem Description
Read "position" property of the async opened FileStream after writing data from Socket cause application crash with Android and iOS devices.
It has been tested with many different AIR versions even with latests AIR 32.0.0.144 beta and AIR 33.0.1.228 with different Android and iOS devices and OS versions.
Same problem in all cases. The same problem also with URLStream (not just with Socket) but it little harder to reproduce.
All it works fine with Windows and macOS.

Tracker and related issues:
https://tracker.adobe.com/#/view/AIR-3982883
https://tracker.adobe.com/#/view/AIR-3568404
https://forums.adobe.com/message/7519594
http://forum.starling-framework.org/topic/android-async-filestream-socket-data-read-position-property-crash?replies=1#post-80022

## Steps to Reproduce
1) Open file for writing via openAsync method.
2) Receive data from socket connection (as a client via Socket ProgressEvent.SOCKET_DATA event) and read it to temp ByteArray.
3) Write temp ByteArray to opened file.
4) Read FileStream "position" property (trace it, for example). There will be application crash.
Launch attached application example and click (**with high-end devices you need to fast click many times, may be 5-30**) anywhere on stage to receive data via Socket.

Application example with sources attached.
[async_filestream_crash.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/3559590/async_filestream_crash.zip)

```
package {
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.events.MouseEvent;
	import flash.filesystem.FileStream;
	import flash.filesystem.File;
	import flash.filesystem.FileMode;
	import flash.utils.ByteArray;
	import flash.events.ProgressEvent;
	import flash.net.ServerSocket;
	import flash.events.ServerSocketConnectEvent;
	import flash.net.Socket;
	
	public class AsyncFilestreamCrash extends Sprite {
		private var serverSocket:ServerSocket;
		private var clientSocket:Socket;
		private var fs:FileStream;
		private const port:int = 12346;
		
		public function AsyncFilestreamCrash() {
			addEventListener(Event.ADDED_TO_STAGE, init);
		}
		
		private function init(e:Event):void {
			removeEventListener(Event.ADDED_TO_STAGE, init);
			
			serverSocket = new ServerSocket();
			serverSocket.addEventListener(ServerSocketConnectEvent.CONNECT, serverSocketConnected);
			serverSocket.bind(port);
			serverSocket.listen();
			
			stage.addEventListener(MouseEvent.CLICK, click);
			addEventListener(Event.ENTER_FRAME, enterFrame);
		}
		
		private function enterFrame(e:Event):void {
			graphics.clear();
			graphics.beginFill(uint.MAX_VALUE * Math.random());
			graphics.drawRect(0, 0, 100, 100);
			graphics.endFill();
		}
		
		protected function serverSocketConnected(e:ServerSocketConnectEvent):void {
			var data:ByteArray = new ByteArray();
			for (var i:int = 0; i < 10000; i++) {
				data.writeUTFBytes("test string");
			}
			e.socket.writeBytes(data);
		}
		
		private function click(e:MouseEvent):void {
			var file:File = File.applicationStorageDirectory.resolvePath("test.txt");
			fs = new FileStream();
			fs.openAsync(file, FileMode.WRITE);
			fs.addEventListener(Event.CLOSE, projectFilestreamClosedForStart);
			
			clientSocket = new Socket();
			clientSocket.addEventListener(ProgressEvent.SOCKET_DATA, clientSocketDataHandler);
			clientSocket.connect("127.0.0.1", port);
		}
		
		private function clientSocketDataHandler(e:ProgressEvent):void {
			 var ba:ByteArray = new ByteArray();
			clientSocket.readBytes(ba, 0, clientSocket.bytesAvailable);
			fs.writeBytes(ba, 0, ba.bytesAvailable);
			trace(fs.position);//This line cause crash
		}
		
		private function progress(e:ProgressEvent):void {
			trace("progress", e.bytesLoaded, e.bytesTotal);
		}
		
		private function projectFilestreamClosedForStart(e:Event):void {
			trace("closed");
		}
		
	}
}
```

**Actual Result:**
Application hangs (crash). Square in top-left corner don't change it color anymore (just to "see" hang/crash).

**Expected Result:**
Application shouldn't crash.

## Known Workarounds
1) Use synchronous open method for FileStream (but it cause lags in real applications usage).
2) Don't read "position" property of async opened FileStream after writing bytes from Socket (but it's not possible in many real applications).

**Comment by ajwfrost** [comment]
Don't you just hate complex multithreading and critical sections...

Hang caused by the async FileStream thread being in critical section A and trying to enter critical section B, whilst the main thread was already in critical section B in order to call the AS3 callback, which has the call to access the FileStream.position property which needs to get into critical section A - hence both threads are stuck.

Looks like we can delay the FileStream's attempt to get into critical section B until it's exited A which should fix this issue.

**Comment by itlancer** [comment]
@ajwfrost, may be sample of code too complex but it with it you can 100% reproduce core problem.
Real life usage where such hang/crash occurs - just simple large file (> ~20 MB) downloading via URLStream and write receiving bytes by chunks to async opened file.
That can be hangs/crash without complex multithreading. Just async instensive receiveing bytes with async write its.
It looks that it's not problems with delay but something with trying to add (write) new part of bytes ("chunk") to async opened file when previous "chunk" not yet wrote to disk and something in the "queue".

**Comment by ajwfrost** [comment]
Hi

To clarify my comment, I didn't mean that the code sample that you provided was too complex, I was referring to the AIR source code where there are multiple threads and mutexes that need to be accessed always in the correct order to avoid deadlock or livelock.

It is indeed because of writing things to the queue whilst also processing things, and is partly due to the nature of the runtime where queues that are being processed can result in calls back into ActionScript and from there the user can call another function that then results in another queue modification.

Anyway - we believe we have a fix for this, it will be out shortly.

**Comment by itlancer** [comment]
Issue seems to be fixed with AIR 33.0.2.246 for Android (cannot reproduce it anymore) but still exists for iOS.

**Comment by itlancer** [comment]
With AIR 33.1.0.16 it fixed for iOS too.
Waiting for production release.
Cannot test it with tvOS because of this issue: https://github.com/Gamua/Adobe-Runtime-Support/issues/209. Attached here application example just hangs on start.

**Comment by itlancer** [comment]
With latest AIR 33.1.0.50 it works fine for Android and iOS.
Also it works fine with AIR 33.0.2.338 and below with tvOS. But cannot test it with AIR 33.1.0.50 and tvOS because of this issue: https://github.com/Gamua/Adobe-Runtime-Support/issues/234
